### ISSUE TITLE
Brackets

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#10]
If Henson uses square brackets, we propose to change these to round ( brackets to differentiate from editorial use of square brackets. Is this agreeable?

**Comment by dpl0js** [comment]
@KPalmerHeathman I'm not sure about this.  Does he ever use square brackets in black?  I'm pretty sure he doesn't, in which case there's no problem. See top of p. 24, (7), for how to render coloured square brackets, thus indicating that they are his.  (We would never use coloured square brackets for our interpolations.
Let me know if you come across black square brackets used by Henson!

**Comment by KPalmerHeathman** [comment]
@dpl0js sorry my query wasn't clear. The issue came up today because Henson uses black square brackets in several places in Vol. 15.  He is not using them differently to how he usually uses round brackets, along the lines of 'X and Y came to tea [Z also came]. Afterwards we walked to the Cathedral.' A concern was that preserving the use of black square brackets loses the differentiation between our editorial interpolations and Henson's writing, when it seems that Henson in these cases doesn't seem to prefer either round or square in this volume and uses them fairly interchangeably.

**Comment by dpl0js** [comment]
@KPalmerHeathman Thank you Katie, I'm with you know, and yes, we should indeed change his square brackets to round brackets to avoid confusion.  But where he is offsetting text for possible inclusion (or exclusion) in the Retrospect, we should keep his square brackets and use bold for colour (??)

**Comment by peterwebster** [comment]
So, if I am understanding correctly, there are three possible cases:

(i) HHH uses a square bracket instead of a curled one in the run of text as he is writing: Treatment:  replace square with curled.
(ii) HHH uses a coloured square bracket at a date later than the writing to mark off text for Retrospect:  Treatment: we retain the square brackets and add bold.
(iii) Editorial interpolations in square brackets, no bold.

Does that cover it? @dpl0js

**Comment by dpl0js** [comment]
@peterwebster @KPalmerHeathman 
thank you for summarising the new policy.  I shall update the style sheet.
