### ISSUE TITLE
Missing mark-up: letters and quotes

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#100]
I noticed some markup was being ignored.

Quotes: `<div type="quote">` [example](http://10.245.28.108:3000/journals/05-02-12-05-17)
Is styled in the standard HTML "blockquote" way, is this okay? The quote gets indented with a light grey line on the left side.
![journal-quote](https://user-images.githubusercontent.com/1181194/41158505-1a880ab4-6b21-11e8-957a-3d369189b3e4.png)

Letters: `<div type="letter">` [example](http://10.245.28.108:3000/journals/01-02-18-03-07)
Wasn't being recognised as special styling at all. I've now done this as a blockquote too. I'm not sure what to do to distinguish it as a letter (rather than a quote), but then I'm not sure it's needed (as that's clear by the text).
![journal-letter](https://user-images.githubusercontent.com/1181194/41158509-1d661a46-6b21-11e8-856f-26dc0ca43626.png)

Side note: So far there are only 2 quotes, and [the other one](http://10.245.28.108:3000/journals/00-11-15-11-21) is from a letter anyway. How lazy of Henson not to copy the letter out in full!

**Comment by peterwebster** [comment]
Could @DurHHHI take a look at this in conjunction with #94 and let me know what you think of the look. I incline to think that the grey line may not be necessary.

**Comment by peterwebster** [comment]
@nomoregrapes good spot: see also the third type (div=verse), with example at #94 
With verse, I think we need indentation and single line spacing (so if the lines are given in individual <P elements, we may need to enforce a narrower line spacing. I'd be against a grey vertical line on the left

**Comment by DurHHHI** [comment]
@peterwebster Yes, I agree. I don't think the grey line and indent ads anything with div-letter, personally. I do like it with div-quote though! 

A follow up query from #94 : should div-verse be doing anything format-wise at the moment? I know the bullets are coming out (appreciated). Will the text between a 'div-verse'/div eventually reflect as single space, indent?

**Comment by DurHHHI** [comment]
Ah @peterwebster beat me to it - yes thanks, that would be my preference too with a div-verse format!

**Comment by peterwebster** [comment]
@DurHHHI  So, let's say that we'd like:

letter - indent only
quote - indent and line
verse  - indent, no line, single spacing

What say you, @nomoregrapes ?

**Comment by DurHHHI** [comment]
@peterwebster Yes please! @nomoregrapes Help us, Obi-wan. ;)

**Comment by nomoregrapes** [comment]
> @nomoregrapes Help us, Obi-wan. ;)

I'll give her all she's got cap'n

**Comment by nomoregrapes** [comment]
Those style rules are now implemented.
Example links are in my 1st comment, and additionally [03-11-08-12-21](http://10.245.28.108:3000/journals/03-11-08-12-21) has examples of: verse, verse with a table in it, and letters.

**Comment by peterwebster** [comment]
To test on Monday @DurHHHI @KPalmerHeathman unless you're able to take a look at it before then and report back.

**Comment by DurHHHI** [comment]
@peterwebster having a fair bit of problems getting the site to work. Cannot return to home page and refresh not working, delaying confirmation. @nomoregrapes perhaps you're doing something with the site at the moment, if so - apologies - will try again later!

**Comment by DurHHHI** [comment]
This looks good to me @peterwebster - see my comment in #146 about the div quote, but this honestly could just be my eyes!

**Comment by peterwebster** [comment]
OK, closing this now...
