### ISSUE TITLE
Amend Excel settings to avoid saving of existing number strings as dates

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#102]
@peterwebster  - reminder to myself for the next time we talk. 

Regardless if I check in excel or textpad and despite setting columns to text dozens of times, still seem to have issue with any full month dates (ex. May, June, July,  anything not followed by a full stop) formatting incorrectly in full date column of ref TSV.

Same issue with page range column. If page range starts with 1, reformatting despite column edits to text to a date format.

**Comment by peterwebster** [comment]
Assigning this to me, having altered the title to reflect the new state of play: 14 and 15 to be edited only in text editor to avoid repetition. I shall investigate the Excel settings to instruct it not to rewrite existing number strings as dates each time it saves a TSV file (particularly an issue in ref.tsv )

**Comment by DurHHHI** [comment]
@peterwebster just a quick update - accents corrected in the ref tsv file, then manual text edit change and save to hopefully correct odd date and page range reformats for everything in the file at present (14-15-16)

**Comment by peterwebster** [comment]
@DurHHHI I had a hunt for solutions to this, and it seems that this feature cannot be turned off in Excel, which is just an astonishingly awful design decision from MS, I can hardly believe it.

So, we'll need to work around this.
(1) when working in Excel, if you have a page range that seems to get converted to a date, write it out as 1xxx24; then, just before we send the TSV off for ingest, we'll need to do a search-replace operation in Notepad to replace xxx with the dash.

We need also to come up with some rule for the dates that keep getting messed up; which formats of date is there a problem?

**Comment by peterwebster** [comment]
@DurHHHI  Note also the unusual Saturday working: I normally try to avoid it ( https://websterresearchconsulting.com/values/ ) but sometimes needs must.

**Comment by DurHHHI** [comment]
@peterwebster Ah, good idea - will do this moving forward -- date format is messing up with the four letter months (where JS does not want this abbreviated). Date format does not seem to be an issue when utilising abbrev.period. (ex. Oct., Dec., Jan.). Could try doing June., July., etc. with the period and then making a note to find and replace just before TSV ingest.

Yes, weekend work not ideal.

**Comment by peterwebster** [comment]
It may still decide that even with the period it's a month: better Junex  Julys Mayx ; anything, so long as we're consistent.  @DurHHHI

**Comment by DurHHHI** [comment]
@peterwebster 
I've just tried it - and it is accepting the period. Do you want me to change?

At the moment.

Date format:
June.
July.
May.

Page range:
0xxx-
1xxx-
2xxx-
to 9xxx-

**Comment by peterwebster** [comment]
Sure, so your search and replace operations are:

June. > June
July. > July
May. > May
xxx- > -  
or just 

xxx >  nothing.

**Comment by DurHHHI** [comment]
@peterwebster  Yes sir - I've corrected the ref.tsv file now. Given the ingest potential Monday, want me to action these replace options in textedit?

**Comment by peterwebster** [comment]
I haven't been able to check that the TSV columns match those in the data model document, and are in the same order horiz ntally, but I think @DurHHHI has. If that's the case, then yes, go ahead with this; I doubt we'll be uploading before lunchtime Tuesday now.

**Comment by DurHHHI** [comment]
@peterwebster I've searched and replaced extra characters in affected date and page range entries in textedit. The columns in ref.tsv reflect the correct order as per Saturday's emailed word doc.

**Comment by peterwebster** [comment]
OK, @DurHHHI you'll be delighted to hear that there's a tweak needed here (from 16 on) in light of #118 

In #118 we decided that we need to maintain just one TSV file for each data type, the whole of which we ingest every time we're preparing for an ingest of new XML. So, you've merrily been adding 11xxx123 as you go along, and just before the ingest, you search/replace it to 11-123. Great.

But (oh no) when you then open the TSV to start adding data relating to the next volume you work on, Excel reformats them all as dates. Aargh.

Fear not. To avoid this, you need to save a new copy of ref.tsv at the point that we close it off in preparation for a new ingest. In that new copy, you do the search and replace operation, and that copy is ingested.
When work resumes on the next volume's annotations, your original version still has 1xxx123 in it, so you work on that and Excel doesn't botch it; problem solved. 

Does  that make sense?

**Comment by peterwebster** [comment]
@durHHI could you confirm that this makes sense to you? Then I can close this down.

**Comment by DurHHHI** [comment]
@peterwebster  makes sense to me! I'll close.

**Comment by peterwebster** [comment]
Thanks @DurHHHI - reopening just to remind me to update the documentation. Once we've got clear of these next few weeks, I have a big master document that lays out the processes we go through.

**Comment by peterwebster** [comment]
All documented now.
