### ISSUE TITLE
Test and adjust style for mobile

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#103]

**Comment by nomoregrapes** [comment]
On most phones, the "grey nav" (Journals, People,...Help) takes up a lot of space.

* We could hide it completely.
* We try reducing the text size and spacing, but that will make it harder to tap the links.
* We could replace it with a standard menu button, which opens/closes that nav. This would still take up some space.
* We could leave it as-is.
* Other clever thoughts?

![mobile-journal](https://user-images.githubusercontent.com/1181194/46298548-44cfc200-c597-11e8-9575-9cbbeb977549.png)

**Comment by peterwebster** [comment]
@nomoregrapes it's actually slightly worse on my phone, as the Journal/People appear in a list rather than spread across horizontally.
I would favour the menu approach. Can you add the five options to the same menu that currently includes Bookmarks and History?

On the font size (in the journal text, I mean): it seems quite small as it is, and certainly shouldn't be reduced. Experiment with a larger font?

The search box: it seems quite wide (because it has to make room for the dropdown options). But, I'm not sure what to do about it, if anything. You could remove the dropdown, and have the search always be for Journals and Annotations, but I'm wary of losing functionality. What do you think?

**Comment by peterwebster** [comment]
On /journals, we may be able to live without the date picker - to discuss.

**Comment by nomoregrapes** [comment]
I've pushed my mobile updates to the [test server](https://henson-test.durham.ac.uk/journals). Mobile can be more tricky/surprising, so it might good for you (and @KPalmerHeathman & @DurHHHI ?) to try it out a bit. In particular, keep an eye out for anything that is tricky to click/tab with fingers.

As for /journals, if you choose to keep it then I should at least fix the "Select" button to be at the end.

**Comment by peterwebster** [comment]
It would be particular helpful if @KPalmerHeathman and @DurHHHI could look at this if they have either or both an iPhone and iPad or other tablet. I only have an Android phone.

**Comment by KPalmerHeathman** [comment]
Hahaha I have a Windows Phone, everything overlaps horribly but tbh I expect that on my dire phone. I can check on my husband's iPad later.

**Comment by DurHHHI** [comment]
Iphone is tight - sorry for all the visuals! Don't know if that is helpful to see.

![43062515_548811675562983_7278164245936603136_n](https://user-images.githubusercontent.com/32575577/46357507-f4229c80-c65c-11e8-83a8-2358504d9ba9.jpg)

![42940199_1953430814949690_1064745121645330432_n](https://user-images.githubusercontent.com/32575577/46357501-f08f1580-c65c-11e8-99c3-fc0de8ca7b6d.jpg)

![43062448_2122988674386402_8224905656520409088_n](https://user-images.githubusercontent.com/32575577/46357521-fab11400-c65c-11e8-9e87-db308e802205.jpg)

![42983388_928421220690021_4972875605331673088_n](https://user-images.githubusercontent.com/32575577/46357524-fd136e00-c65c-11e8-9269-b394b493c82b.jpg)

![43057117_314305272686965_6034566232135434240_n](https://user-images.githubusercontent.com/32575577/46357545-0270b880-c65d-11e8-892f-1c4f6ced5306.jpg)

![42988614_1189165017903892_3470666353529061376_n](https://user-images.githubusercontent.com/32575577/46357554-06043f80-c65d-11e8-8eb7-89a24b05625a.jpg)

**Comment by nomoregrapes** [comment]
@DurHHHI Visuals demonstrate that you're using production/live and not test. Test should look much better right now (until I update the production/live version tomorrow afternoon).

**Comment by peterwebster** [comment]
@nomoregrapes here are my suggestions (on the repo):

- [x] on the site-wide search box, lose the filter drop down: 'journals and annotations' will never fit if we are to leave enough space for the search field itself. Users can either limit their results by type, or go to the Persons/Orgs pages, so no functionality is actually lost.

- [x] The date picker could stay, but could we reduce the width? And (as you mentioned) move the Select button to below the 'To' options.

- [x] When not logged in, on the mobile version, hitting 'History' gets the error page; on the desktop you get the desired 'You have no history'.

**Comment by nomoregrapes** [comment]
Changes made.

**Comment by peterwebster** [comment]
OK, I think we live with this for a while and play with different devices, and create new tickets as and when we want to change anything. @nomoregrapes
