### ISSUE TITLE
Create delayed/scheduled tasks

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#104]
The ingest process does a lot of stuff while the admin user waits for the page to load. These tasks could be put into a schedule/queue and potentially run faster, or avoid running when the website is busy serving visitors.

**Comment by nomoregrapes** [comment]
I've implemented this somewhat, although I could make more use of it.

Self note: it could be worth adding [resque-status](https://github.com/quirkey/resque-status) for the larger tasks, so you can see it's "10% processed annotations in the new XML files", but currently I feel it's too time consuming to setup. I may just note that link in documentation for "dev things that could be done".

**Comment by peterwebster** [comment]
Agreed @nomoregrapes : do please just note this in the documentation as a someday-maybe task.

**Comment by nomoregrapes** [comment]
The resque-status isn't actually that helpful the way all the technical stuff has come together.

There is a "Logs" page in the manage area, that shows when background process jobs started & ended - you can start to learn how long. I.e. Volume 15 might have post-ingest jobs that take 30 minutes, and Volume 16 is of a similar/smaller/larger size.

**Comment by peterwebster** [comment]
I shall watch the logs in action and, if necessary, add some documentation.

**Comment by peterwebster** [comment]
Nothing to do here, closing ticket.
