### ISSUE TITLE
Ingest validation & reporting

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#106]
The ingest could validate the data it reads. It could also produce a better report as to what has been ingested/skipped.

I wrote a note "see 9th May", but can't see a relevant e-mail on that date.

This will be more essential/wise to do after #104

**Comment by nomoregrapes** [comment]
Validation examples: missing XML files, XML well-formed, did it find the annotations it needs(non-critical error, especially if display=no).

**Comment by peterwebster** [comment]
@nomoregrapes as you've now got as far as is sensible with delayed/scheduled tasks, ( #104 ) , this one now comes back into play.

**Comment by peterwebster** [comment]
Agreed that admin dashboard requires an alert (as part of the ingest of a new volume) that the application has found control data without a matching XML file.
User then retrieves file(s), manual addition to Github, and triggers an 'Insert' ingest to solve the issue

As for missing control data for an XML file, see #160

**Comment by nomoregrapes** [comment]
Note to Greg, read http://www.nokogiri.org/tutorials/ensuring_well_formed_markup.html

Ideal would be to use "strict mode", handle badly formed by adding message to ingest report (suggest user checks that entry), but save the auto-fixed version of the XML.

**Comment by nomoregrapes** [comment]
Not done yet.

Part of the way there, I've added a demonstration to the Journal editing page.
* Find a journal and click edit.
* Change something in the content (don't click update), like removing a `>`
* Click the "Refresh preview" button
* A red box will appear if there is an XML error, although it continues to find a way to cope & the preview might look the same.
* Fix the errors, click "refresh preview", ensure red box has gone before clicking "update".
* If you were testing, just go to another page (don't click "update") to discard changes.

Removing one character can trigger about 5 errors. It doesn't always report the line number or what text was involved.

When I add this to the ingest report I think I will only count 1 error(s) per journal entry and report something like `Potential xml errors were found in 3 entries. They were [list entry dates & link to them]` instead of saying 15 errors were found and trying to name all the errors.

**Comment by nomoregrapes** [comment]
The log page reads from top to bottom, and will show messages like this.
![henson-log-xml-errors](https://user-images.githubusercontent.com/1181194/47146555-32a69100-d2c4-11e8-9155-0c312dac37f5.png)

Journal entries without problems won't be listed.
I can't do a total count of how many journals had XML errors, because they're checked as individual tasks (using the process queue) after the control TSV is imported.

**Comment by nomoregrapes** [comment]
**Notes for usage documentation...**

False error to be aware of... `EntityRef: expecting ';'`  that occurs when an entity isn't followed by a space, e.g. `M&amp;Ms`.
I think that is fine & valid, but if I suppress the error (as I have for other false errors) then it would also suppress where it is a true error about the entity, e.g. `So &amp So` missing the semicolon.

If there are errors, then I find it easier to copy the content into a good text editor (that displays line numbers) and when you think you've fixed the issue, paste it back into the GUI to check it or save it.

Below the dashboard you can click "Rescan all XML" (usually if you've added annotation data that was mentioned in already-uploaded journals) it will include a check of the XML well-formedness.
The log will update as the process runs, but might take an hour to check all the journals.


**These changes are now on the test server, and I'm running a scan of the XML so the log will start updating with the reports of what's broken.**

**Comment by nomoregrapes** [comment]
These are the journals (on the test server) that have XML errors/issues.

```

[2018-10-18 12:35:52][henson] In journal 02-11-09-11-13, the XML content had errors. Edit that entry and use the preview for more detail.
[2018-10-18 12:44:45][henson] In journal 03-05-13, the XML content had errors. Edit that entry and use the preview for more detail.
[2018-10-18 12:51:41][henson] In journal 03-10-25-11-04, the XML content had errors. Edit that entry and use the preview for more detail.
[2018-10-18 13:33:28][henson] In journal 05-11-12-11-18, the XML content had errors. Edit that entry and use the preview for more detail.
```

If you don't understand any of the error details on them, let me know and I can explain.

**Comment by peterwebster** [comment]
Does the 'Refresh Preview and Check XML' only work for some errors @nomoregrapes?

I ask because this one has a missing quote in an attribute towards the end, but the check doesn't throw an error https://henson-test.durham.ac.uk/journals/03-10-25-11-04/edit
However, it *is* one of the list generated above.

**Comment by nomoregrapes** [comment]
As discussed...
That journal is too long for the check to run (it doesn't show a red or green result for checking errors, and the preview doesn't update). I just need to deploy to test server for the bug fix to be applied.

**Comment by peterwebster** [comment]
Checked that example, looks good.

So, assigning to me for later feedback when we come to ingesting 16, whenever that turns out to be. @nomoregrapes

**Comment by peterwebster** [comment]
Remaining enhancement in this ticket now at #234 , so closing this one for the sake of clarity.
