### ISSUE TITLE
XML validity check on edit

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#107]
When editing a journal entry, a check could be done to say whether it's well-formed XML or not.

Low priority, as the preview will generally look odd if a tag is not closed.

**Comment by peterwebster** [comment]
This a low priority, but if it isn't implemented, documentation needs to guide users to always use the preview.

**Comment by peterwebster** [comment]
As time is pushing on, I've decided that this can be shelved. Assigned to me rather than @nomoregrapes in order to update the user documentation.

**Comment by nomoregrapes** [comment]
Yep, I think this ticket crept in as something that wasn't massively requested/required.

When editing journals there is a "Refresh preview" button. Terribly invalid XML will make the preview look bad, you can also check annotations by hovering/clicking them in the preview before you save.
