### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#108]
For both Wordpress frontend and for repository. Will need to request uni analytics accounts from CIS.

Don't forget, but easier to do once we have the sites in place & their URLs setup.

**Comment by peterwebster** [comment]
To be set up on Gregory's gmail and shared with Peter

**Comment by nomoregrapes** [comment]
I've set this up on [Google Analytics](https://analytics.google.com/analytics), there are two "properties" which you can flick between by clicking "All Accounts/All Web Site Data" in the top-right.
* WP pages - the wordpress part
* Repository - the Samvera/rails app.

I have tested both, however the later is now configured to only track visits to our "production" site (i.e. not my computer and not the test server, just the one that the domain name will point to).

For the repository, you'll also be able to look at Behaviour, Events, Overview to see how many people are clicking the annotation popups (and which ones). That interaction isn't counted in page views/loads so I spent 5 minutes setting them up as events.

Me and @peterwebster have full access so can add/remove users. Other users should only need the "read" and "collaborate" permissions.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes : assigning this to me so I can test once we've deployed the repo to production.

**Comment by peterwebster** [comment]
Having had a look at this, and seeing it track real time data on production from today (as well as WP data for a few weeks), closing this now. Many thanks @nomoregrapes
