### ISSUE TITLE
Silent editing Greek alpha and beta

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#11]
Can we amend these to (a) and (b) as they are used only to indicate items on a list? As below:

On Monday there was a clergy-council at which we resolved (α) to start a Church Lads Brigade.  (β) to start a Club for the Lewisham Street boys.  I called on
1.	Mrs Bedford	
2.	Miss Tomlinson     3 Richmond Terrace.
3.	Miss Geary	11 Victoria St.
4.	Mr & Mrs Wise	  11 Victoria Street.
5.	Mrs Milman

**Comment by dpl0js** [comment]
@KPalmerHeathman and DurHHHI
Hmm.  I'd rather keep it as he left it.  Is there a reason for changing to a) an b)?

**Comment by KPalmerHeathman** [comment]
Adding @peterwebster to this thread in case technical input is needed (and because I can't remember the outcome of that discussion earlier today - as far as I recall the Greek alphabet was possible but not advisable?).

**Comment by peterwebster** [comment]
Greek characters are possible, as are practically every character you can think of, but they must be encoded properly. I would need to experiment to see whether these are carried through from the Word into XML properly encoded (they may be). If not, that Unicode character will need to be added in the XML; I may be able to do this at scale, but it depends on what comes through the conversion. If I can't then @KPalmerHeathman and @DurHHHI will need to add them manually, either in Word or XML.

So, perfectly possible but with some work. Do we have a sense whether this is a frequent device of Henson's? If so, then the investment of time may be justified. If this is a one-off, or very infrequent, there may be a case for changing to plain a and b. @dpl0js

**Comment by KPalmerHeathman** [comment]
Another instance found today in Vol 15:

1.	That in view of the great & rapid increase of the population it is desirable that amicable relations shd be established with the leading Nonconformist bodies with a view to common action in respect of (α) pastoral visitation (β) aggressive religious work (δ) social reform.

**Comment by dpl0js** [comment]
@KPalmerHeathman @peterwebster 

Okay, I guess we could change to a) and b) etc; it would not involve too much violation of the original text.   I have made a note to discuss this at the weekly meeting of the Durham team on Wednesday, just to confirm.

**Comment by peterwebster** [comment]
I wonder whether you were able to confirm this yesterday @dpl0js ?

**Comment by dpl0js** [comment]
@peterwebster yes, we agreed to change to Greek to English letters.  We decided, too, to start a new folder in which to note editorial interventions, which will form the basis of 'A Note on the Text' at the start of the edition.

**Comment by dpl0js** [comment]
@peterwebster @KPalmerHeathman @DurHHHI @williamsonphilip 
Apologies, Peter, but can we please re-open this question?   I seem to have misremembered the outcome of our discussion yesterday.  We wondered whether it would be possible for you to include the Greek letters in the XML code: it would be a pity to lose H's erudition.  There may be occasions, too, when he writes the odd phrase or even sentence in Greek.

**Comment by peterwebster** [comment]
I shall indicate how these should be marked in the Word files to faciliate conversion.

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman an afterthought: when do you expect to finish volume 15 in Word? Reinserting these might be the last task.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI when you find these in Word, please replace them with alphagreek, betagreek or gammagreek (just those letters, no punctuation or additional styling.) My Stage 2 script will then turn them into something that will parse in Firefox.
Volume 15 can be our test of how it goes.

**Comment by peterwebster** [comment]
Script now amended and tested satisfactorily in process_dev

@KPalmerHeathman @DurHHHI once you're happy with this, do feel free to close the ticket.
