### ISSUE TITLE
Speed-up admin dashboard

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#111]
There is an admin/manage dashboard that shows counts for each data type.

This is slow to load. Could speed it up, or cache the numbers.
Having the numbers cached might also allow us to save/display information like "date of last ingest" for each data type. Or identify if changes have been made since the TSV was last exported to Github.

**Comment by peterwebster** [comment]
Your call, but I'm happy to cache the numbers, with an option to trigger a refresh if required?

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Thanks @nomoregrapes
