### ISSUE TITLE
Creation of new annotations in the GUI

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#112]
We may already have this covered, but there is a use case that may crop up, where:

(i) there is an element set with attribute display=no in the XML
(ii) there is NOT in the relevant annotations a matching record set to NoIndex
(iii) project team wants to add a newly composed annotation and unhide the element in the text.

I know we have an editor that allows the team to intervene in the XML to remove the display attribute, but is it possible in the GUI to 'Add New Annotation'? If not, we will need it.
It will need to allow the user to specify what the ID should be, rather than minting a new one on the end of the existing sequence.

**Comment by peterwebster** [comment]
This is already enabled, but needs to be included in user documentation.

**Comment by peterwebster** [comment]
Hi @nomoregrapes : we obviously discussed this in a call, but I don't recall how it was possible to do this. 

There isn't anything like an Add Annotation/ New Annotation button at http://10.245.28.108:3000/people/person311  .
Did we conclude that one just made a one line TSV with the new one, and ingested it from the admin dashboard?

**Comment by peterwebster** [comment]
@nomoregrapes aha, I see these now, at http://10.245.28.108:3000/people

This creates a new issue, however. Presumably the application gives the new person an ID which is next in the sequence (as far as it knows it, ie the last number so far ingested plus one).
BUT offline, the sequence of IDs for each has already continued beyond that, as the work on the next volume has gone on. So, we will have clashing IDs, since the number the application creates will already be in use offline.
Can the application allow the admin user to specify the ID of the new annotation? If so, we're OK.
If it can't (or not easily in the next two weeks) we need to hide this function as it create issues every time it is used.

**Comment by peterwebster** [comment]
On creation of new annotation, need new number field in which staff can enter the appropriate ID.

Some light validation of that input is a nice-to-have (is this a number? is this an ID already in use in the repo?)

**Comment by nomoregrapes** [comment]
Done for new people.
Need to repeat for the other types.

**Comment by nomoregrapes** [comment]
Done for the other types, needs testing.

References probably still needs some work (was there a ticket about editing reference dates?) and tidying up.

**Comment by peterwebster** [comment]
Thanks @nomoregrapes  I can test this once we've got some data in `henson-test`

**Comment by peterwebster** [comment]
Issue #170 is related to this, but I think you mean @nomoregrapes the issue of the date defaulting to today when editing a reference in the GUI. I can't find the ticket for it, strangely, but this is critical.

**Comment by peterwebster** [comment]
On the issue of the DateFull defaulting to today's date when editing a reference @nomoregrapes :  you've added a note that reads ' If set to today, no date will not be saved.' I guess you mean 'no date will be saved', and so the issue is resolved? Is that right?
I tried opening a reference that already had a date prior to today, and that is not overwritten with today's date (which is good)

[30 Aug: discussed with @nomoregrapes and, yes, this is resolved, so pass on to the matters below.

**Comment by peterwebster** [comment]
I created a new person, 9999, but on hitting Create Person, I get an error.

I assumed that this was because I had obeyed the instructions, formatting the ID as person9999, but it also fails as pers.9999

**Comment by peterwebster** [comment]
Same issue for organisations and references, haven't yet looked at place @nomoregrapes

**Comment by nomoregrapes** [comment]
I can't recreate this problem.

When you clicked "Create Person", what page(URL) did it take you to? Was there a message (in a blue box)?

**Comment by peterwebster** [comment]
Look in the log at 11.39 for an attempt to create person10000.

The result is:  
![image](https://user-images.githubusercontent.com/5520710/45088351-9d2eb380-b100-11e8-8451-2b508294bba8.png)

@nomoregrapes

**Comment by nomoregrapes** [comment]
@nomoregrapes to add more debugging notes. Can recreate it on test server but problem unknown.

**Comment by nomoregrapes** [comment]
Fixed this.

Note to self: code for rescuing `ActiveFedora::ObjectNotFoundError` doesn't get run before the application_controller rescue block gets run. Odd that this behaviour would be different out of development environment.
Might need to check the other instances of `ActiveFedora::ObjectNotFoundError` to see if they behave as intended or not.

**Comment by nomoregrapes** [comment]
Answer to self:
Rescuing from `ActiveFedora::ObjectNotFoundError` is fine on the server, so long as it doesn't try redirecting. No other code changes need to be made.

**Comment by peterwebster** [comment]
Same issue with this one  - person 10005, organisation 10001

Not for this week, but opening this again @nomoregrapes

**Comment by peterwebster** [comment]
Since new annotations can be added another way, by means of a one-line TSV ingest, not a priority.

**Comment by nomoregrapes** [comment]
Caused by a different issue, error for future note is
```
F, [2018-09-06T16:50:13.530327 #7934] FATAL -- : [6f9b2023-ea05-4447-aa71-43b7bc00665b] NoMethodError (undefined method `match?' for /^person[0-9]+$/:Regexp
Did you mean?  match):
F, [2018-09-06T16:50:13.530362 #7934] FATAL -- : [6f9b2023-ea05-4447-aa71-43b7bc00665b]   
F, [2018-09-06T16:50:13.530406 #7934] FATAL -- : [6f9b2023-ea05-4447-aa71-43b7bc00665b] app/controllers/people_controller.rb:308:in `create'

```

**Comment by peterwebster** [comment]
Keeping this open as one of the first things for @nomoregrapes once back in a couple of weeks time. Using Dev Phase 2 lable to keep these together.

**Comment by nomoregrapes** [comment]
This issue was due to specifics on the test/production library servers, and is now fixed and deployed to test.

**Comment by peterwebster** [comment]
https://henson-test.durham.ac.uk/people/person11000
https://henson-test.durham.ac.uk/places/place10001
https://henson-test.durham.ac.uk/organisations/organisation11111

All these are fine, but there seems to be a continuing issue with references, which I shall need to investigate further. This ticket is a bit long now, so I shall close it and start a new one shortly.
