### ISSUE TITLE
Set all applications and scripts to encode in UTF-8

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#113]
@DurHHHI @KPalmerHeathman at some point on a Skype call, when I can see your machines, we need to check the settings of various programs for their default character encoding settings. This means Excel, Komodo, Notepad, and anything else you use to edit XML or TSV.

If Hilary and I can have a call this week with Skype, we can make a start on this.

**Comment by DurHHHI** [comment]
Excellent - sounds good - can speak for Komodo only at the moment. UTF-8, for reference.

**Comment by peterwebster** [comment]
Could you screenshot what you see in order to make that determination?  @DurHHHI

**Comment by DurHHHI** [comment]
Ouch ;) 
<img width="1075" alt="screen shot 2018-06-18 at 1 34 28 pm" src="https://user-images.githubusercontent.com/32575577/41536079-6ecd7b3a-72fc-11e8-9273-8ba0df92a8ad.png">

**Comment by peterwebster** [comment]
Thanks @DurHHHI : that tells us what the file is already encoded in as you received it. What we need is the setting for what Komodo will save it out as. I'll see what I can find out.

**Comment by DurHHHI** [comment]
Less ouch ;) Ok, that's helpful!

**Comment by peterwebster** [comment]
Adding this to H&K return label with a view to looking at it in Durham next week.

**Comment by peterwebster** [comment]
Now done in Notepad++ on two office machines
Also on Excel on two office machines
Both done on Hilary's laptop
Still to do on Katie's.

Consider creating Word documents with encoding set in which keyers can begin work for each new volume.

**Comment by peterwebster** [comment]
Assigning to Katie in relation to her laptop. Once that's done, ping it back to me.

**Comment by KPalmerHeathman** [comment]
Done on my laptop now so closing this.
