### ISSUE TITLE
Solr: test downgrading

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#114]
This is the current "big/critical" task, making sure the repository can run with the existing library setup. I need to **downgrade from Solr 6.3.0 to Solr 4.10.3.**

I've gone through the change files between those versions. The main changes are lots and lots of performance increases and bug fixes (potentially security fixes).
* Version 5.1 added some facet stuff that we may need (especially for searches for a specific type)
* years before 1582 could be problematic, will need to make sure References store dates as strings only (not actual dates) and we should be fine.

Creating a ticket for any progress/notes I want to keep. Also for this image of rough notes, in-case my notepad burns. If things don't work with Solr 4.10.3, these will be my hints why it doesn't work.
![solr_downgrading](https://user-images.githubusercontent.com/1181194/41609049-d451e60e-73e1-11e8-9590-2cf768d62a86.jpg)

**Comment by nomoregrapes** [comment]
Update is to abandon this, and..
- [x] run Solr 6 on Helios (Boguslaw's server)
- [ ] run Fedora and Rails etc on the library servers (cisvirhyd).
- [ ] have a nice error returned if the Helios is not available.

Yet still it relies on CIS...
Currently waiting for it-webteam to give my account access to the Durham github, so I can push my code to cisvirhyd.

**Comment by peterwebster** [comment]
If you don't anywhere soon with the web team, perhaps @BoguslawObara might give them a prod?

**Comment by nomoregrapes** [comment]
As a prod, I've put it in as a CIS support call too.

**Comment by nomoregrapes** [comment]
If something happens to Helios (running Solr) then any repository page will redirect to a 503 error page, that currently looks like this.
![solr_503](https://user-images.githubusercontent.com/1181194/42273280-abda819a-7f80-11e8-9a3d-e0af5d698d28.png)

Along with the 404 page, this error page uses a very cut-down style so that it's not reliant on the usual template files. I can change the text if desired.

The issue could be something that resolves itself in <10 minutes, or it could be something more serious that someone in CompSci (not CIS) needs to check out(may need prompting). I'll probably be finding out exactly what time scale should be expected for that.

**Comment by nomoregrapes** [comment]
Solr is now setup on Helios and completely accessible from the library Hydra servers.

**Comment by peterwebster** [comment]
@nomoregrapes were you able to deal with the issue with the 503 page as well?
