### ISSUE TITLE
Create approved list of HTML entities for pasting into XML

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#117]
@DurHHHI through no fault of her own (I think) introduced an additional character in the middle of the entity references for e acute etc. (Sometimes what you see is not all you get when copying from a webpage). I'm fixing this in 14 and 15, but before we do any more XML work in 16 or subsequent volumes, I need to create a .txt file from which @KPalmerHeathman and Hilary can safely copy and paste.

**Comment by DurHHHI** [comment]
Oh no! Apologies, and thanks @peterwebster - yes, this was a cut and paste job on the accent corrections!

**Comment by nomoregrapes** [comment]
Commenting to say it's not Hilary's fault, I'm surprised such a dodgy website exists for such a mundane thing.

If you're intrigued, this is related to [how strange text can crash your computer](https://www.youtube.com/watch?v=hJLMSllzoLA). I recommend Tom Scott's channel, he has a few videos about the joys of text encoding!

**Comment by peterwebster** [comment]
Done.
