### ISSUE TITLE
Managing entities in XML that need to be set to display=no

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#118]
@DurHHHI @KPalmerHeathman : something for us to think about in August, when we've got 14 and 15 launched.

For each volume (or more precisely, each upload), I need a list of IDs of persons, places etc. that may have occurred in the volumes concerned that we need to hide because there is no annotation for it.
When we first thought about this, I had imagined we might be dealing with a couple of dozen of these, but it now turns out there are hundreds (if not indeed more than a thousand). So, it will help me a lot if we can manage the list in a way that makes creating a script as easy as possible.

Is it possible that in volume 21 (say) you may mark up a person who is already set to hide in the TSV we have for 14/15, and who needs still to be hidden? I imagine it is, so I think we need to maintain a master TSV file as we do now, and each time I create a single script that checks for every person/place etc. that is *at that time* set to No Index, right back to ID=1, even if the vast majority of lines in the script do not find anything to alter (as many people in v15 will not recur in v21).

The alternative is to run a script which only covers the range of IDs for the volumes concerned. That is, I've just dealt with IDs 1-2007 for persons, and so for 16 we might only include 2008 - whatever the last one is. However, for reasons given above, this will not cover some persons who need to be covered.

**Comment by peterwebster** [comment]
A query for @nomoregrapes 
Can the ingest deal with lines in the TSV with IDs that it has previously ingested? If so, that means that the easiest option for managing the data before ingest is to have a single file for each type, each of them starting with ID=1, which is reingested each time. It will be slower at ingest, but I'm not too concerned about that.

**Comment by nomoregrapes** [comment]
When you ingest (which is done 1 type at a time) you choose between two options...
* Insert = if a matching ID is found, then skip ingest.
* Update = if a matching ID is found, overwrite it with the values from the TSV(even if they're blank).

Insert is slightly faster, because it processes less data but both options have to look for existing IDs.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI here's what we discussed yesterday, which also supersedes #123 and #124 which I will close shortly.

As Gregory confirmed above, it is possible at every upload time to reingest *all* the TSV, from ID=1 in each case, asking the application to overwrite old versions with whatever it finds in the TSV with the same ID.  [EDIT:  need to use the Insert option at upload, not Update/Insert, as the latter overwrites edits in the GUI:  22 August]

So, our process for unhiding persons/orgs etc in volumes 16- that have been hidden in 14/15 is.

(i) K&H decide that person.123, hidden in 14, should be revealed in 16,17,18 etc.
(ii) in the TSV, K&H ensure that index=no is reset to blank for person.123, and include a nice new annotation to go with him/her.
(iii) just before ingest time, I make a new script each time from the TSV, using the index=no field as my indication that person.123 is not hidden in 16/17/18. When that script runs, it sets all those in 16/17/18 to hide which should be hidden, no longer including person.123.
(iv) on ingest, the application finds the annotation, and ensures that person.123 appears now in the search.

At this point, person.123 is now visible in 16, and searches for him/her find results for 16. Neither is true for 14. So:

(v) K&H keep some sort of list of IDs of those who were once hidden and have been resurrected.
Then either:
(vi) if you know where they appeared in 14, amend the XML directly in the edit facility in the application, which you haven't seen in action yet, but it's quite a lot like a text editor; or
(vii) save them up, and periodically I can grep through the XML of past volumes to see where they occurred (producing a list of filenames in a .txt document), making it easier to find.

If there turn out to be lots of these, then I can look at some automated way of changing them in past volumes, but the version control problems are quite significant with reingesting new versions of XML files. As we've said, I'm not sure there will be time for many of these, as there is an army of new persons to be dealt with in each new volume.

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI let me know if this doesn't seem clear, and which of (vi) and (vii) you'd rather work with.

Actions now:
(i) I need to update my master workflow document to reflect this change;
(ii) when it comes to volume 16, I need a little script to cater for (vii) if that is what is needed.

**Comment by nomoregrapes** [comment]
I think you're missing this small clarification:
* If person 123 is indexed (via a TSV ingest) then they will be searchable.
* A search result for Mr 123 will take you to `.../people/person123` which lists _all_ 14/15/16/etc journal mentions, regardless of whether the mention has a display=no or not.
* vol 16 entries mentions of him, the popup will have a link to `.../people/person123` for viewing other journal mentions, so you'll discover the vol 14 mentions.
* vol 14 entries(where he was less-important) could have display=no and it will not be able to trigger the popup.

For that last point, you will of course want to update vol 14 and remove display=no. However, you can use the repository website itself to find the entries that need updating.

**Comment by peterwebster** [comment]
@nomoregrapes thanks for that, which means that once a new load of XML is ingested, along with the TSV in which person.123 is now set to index (where he had been hidden before), @KPalmerHeathman and @DurHHHI can in fact then use the site search itself (during the checking phase before the volume is made public) to find references in the earlier volumes. They click through to the journal entry, hit Edit and amend the XML to remove display=no, thus enabling the popup.
That is, an aid to (vi) above, and thus (possibly) lessens the need for (vii).

**Comment by peterwebster** [comment]
This is now added to the documentation.
