### ISSUE TITLE
Add Places to navigation options, on WP and repo

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#121]
@nomoregrapes this would be good to do, if possible, by the meeting on Wednesday, unless it is a great deal of work.

Grey bar then reads: Journals People Organisations Places

Once it is written, there will also be something like Search Help to add #97

**Comment by peterwebster** [comment]
OK, I figured out how to do this in WP, but it should be reflected in the repo.

**Comment by nomoregrapes** [comment]
Now done, this is how the repository top-bar now looks like...
![top-bars](https://user-images.githubusercontent.com/1181194/42097166-555bbb88-7baf-11e8-9ff7-f17a0afe3da3.png)


It's worth noting that we intended the repository homepage to redirect to the wordpress homepage. So the logo/title will effectively link to the same place as the "Guidance/Help" that is in the blue bar. We've avoided duplication for other links/searches, but I think duplicating the logo link is fine.

Do we want to keep the "Bookmarks" and "History" links in the blue bar? If so, we should start a Github ticket for me to tidy up those pages. Bookmarks has a handy "citation" feature, but I need to know the appropriate citation format, and probably make it list the full URL as part of that.

**Comment by peterwebster** [comment]
Hi @nomoregrapes , some answers on this.

- [x] In the very top, I think we need to keep the login somewhere, but as it is only for admin users, we could perhaps move it to the footer instead? 
- [x] We can lose the Guidance/Help if it just goes to the WP home. The 'Help' option in the line below actually goes to the real help pages.

History (being, I guess, just a certain number of back links oould be useful to retain, as could be Bookmarks, but they're not priorities. So, I'll create a new ticket, assigned to me, to come back to in August.

**Comment by peterwebster** [comment]
Login to go in a footer or somewhere less prominent.

Guidance and Help can go because the Help option in the grey bar does the same job.

**Comment by nomoregrapes** [comment]
This is how the homepage looks now...
![header](https://user-images.githubusercontent.com/1181194/43782555-8adfb3b0-9a57-11e8-908b-2039ea9cc89b.png)


I moved the login link to be a discreet key icon in the footer, but do you want to consider further the footer? currently it's the key to annotations, and now a login link.
![footer](https://user-images.githubusercontent.com/1181194/43782636-afdd6784-9a57-11e8-8c09-82872b8c0400.png)


The repository "homepage" now redirects to the Wordpress homepage as per our final intention, the sudden change might confuse @DurHHHI & @KPalmerHeathman

**Comment by peterwebster** [comment]
Moving the issue of whether or not to look at the layout of the footer to a new ticket for clarity.

Could @nomoregrapes confirm that the Help link in the grey bar (in the repo) goes to http://community.dur.ac.uk/henson.project/index.php/help/ ?
If it does, we can close this ticket.
