### ISSUE TITLE
Resurrect IDS currently set as 'do not index' - what to do previous volume entries where ID was set as 'do not index' 

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#124]
i.e. * If ID created for person in Vol 15, and person returns and annotation written for ID in vol 21, 'what to do with him/her in 15'

Personally, I think that if an ID is 'resurrected' because they become 'more important' or there is more information about them in a later volume to correctly identify, the person should be viewable across the journals. 

This might be another question, but still helpful for today's discussion to clarify - is it easier or more difficult to 'resurrect' IDs to display across journal volumes or is it better to identify what volume the ID should start to be displayed?

@peterwebster 
@KPalmerHeathman

**Comment by peterwebster** [comment]
Now documented at ##118.
