### ISSUE TITLE
Change wording on date picker 'Search' button

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#125]
Having two search buttons has caused some confusion today. In a ten minute gap at the end of a day, could you change it to 'Show entries'?

Open to suggestions of better wording. 'Show days'? @DurHHHI @KPalmerHeathman

**Comment by peterwebster** [comment]
I shall confirm the preferred wording, bearing in mind that there is only really space for six characters.

**Comment by peterwebster** [comment]
The best contender seems to be 'Select', which I think works quite well. There's a end-of-day job for @nomoregrapes ;-)

**Comment by nomoregrapes** [comment]
Done.
