### ISSUE TITLE
Maintain consistent TSV headings.

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#126]
Volume 15_v2 control file was missing the first 2 headings. The first line should be exactly,
`SortKey	FileName	DateFrom	DateTo	Volume	PageFrom	PageTo	Issues/controversies (separated by commas)`
I've fixed it on my local copy, so that I could do the ingest.

The annotation TSVs have `0` as the first heading instead of `ID`. I could adjust the code so that either is acceptable.

**Comment by peterwebster** [comment]
So, first line must match exactly, but columns accepted in any order.  

All existing top rows are now acceptable.
