### ISSUE TITLE
Icons displaying on line above

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#127]
![image](https://user-images.githubusercontent.com/32575539/42087740-038a5cee-7b8f-11e8-8694-110c2e963bb9.png)
Hi @nomoregrapes and @peterwebster, not sure how well you can see it in the above screenshot, but the person icons for Mrs Talbot and Miss Talbot are appearing on the line above, in 'December' and 'dined with', rather than attached to the Talbots. This is in Firefox.

**Comment by peterwebster** [comment]
Curious. *assigns to @nomoregrapes *

Nice desktop....

**Comment by KPalmerHeathman** [comment]
Sorry about the double screenshot, no idea how to make it only capture one screen!

**Comment by peterwebster** [comment]
By disconnecting one monitor, alas. @KPalmerHeathman

**Comment by nomoregrapes** [comment]
Yet you haven't told us where the photo is of! When I was forced to use Windows, I had [FSCapture](http://www.faststone.org/FSCaptureDetail.htm)(free download) which I think you can select the area to screenshot.

Curious desktop, curious bug too.
It's specific to **Firefox** and I can recreate, so I will work on fixing this later. [link to journal](http://10.245.28.108:3000/journals/00-12-02-12-14)

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/42210556-38ff529a-7ea9-11e8-8413-9322b131efb7.png)
Cheddar Gorge!

**Comment by peterwebster** [comment]
@nomoregrapes see more examples at #145 , now closed.

**Comment by nomoregrapes** [comment]
This seems to be fixed, probably as a result of other style changes.

@KPalmerHeathman could you confirm on Firefox that the icons are on the correct line. E.g. [link to journal](http://10.245.28.108:3000/journals/00-12-02-12-14) with Miss Talbot and you original screenshot.

**Comment by KPalmerHeathman** [comment]
Fine in Talbots example now.

**Comment by peterwebster** [comment]
Reopening this, as it seems to be browser-related. See the results in FF (with icons from the third line appearing on the first), and Chrome which is OK.

![image](https://user-images.githubusercontent.com/5520710/46294674-3335ec80-c58e-11e8-8432-69ede17ef2ef.png)
 
![image](https://user-images.githubusercontent.com/5520710/46294685-392bcd80-c58e-11e8-9031-3214f9225742.png)

If you refresh the page, it seems to clear the issue, so this is perhaps something to do with the order in FF loads the page. @nomoregrapes

**Comment by peterwebster** [comment]
Another example that you may be able to test. This page in FF first loads with the icon out of place (end of the first line of the letter) but if you then hover over it, it jumps back into the correct place.
![image](https://user-images.githubusercontent.com/5520710/46347947-33dd8a00-c645-11e8-8f06-310e9f009488.png)
@nomoregrapes

**Comment by nomoregrapes** [comment]
I don't think this is the same as the original bug where they appeared directly above (though it's similar enough to be in the same issue).

I can often make them dance all over the page when I resize the Firefox window.
![firefox-troubles](https://user-images.githubusercontent.com/1181194/46354712-2af5b400-c657-11e8-854d-7a342ce465b8.png)


This is bizarre, tricky to recreate with the same result each time, and will be tricky to debug. As it corrects itself, usually when you click anywhere or even just move your mouse near the icon, I'm inclined to call it a Firefox Bug not a Henson bug.

**Comment by peterwebster** [comment]
Yes, I agree @nomoregrapes . I shall close this now.
