### ISSUE TITLE
Spacing of multiple pop up annotation boxes.

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#129]
![image](https://user-images.githubusercontent.com/32575539/42168172-270c0188-7e08-11e8-9eb4-84c3e5f8921f.png)

**Comment by DurHHHI** [comment]
For reference, this is involving event=160 and ref=119

**Comment by peterwebster** [comment]
Me to check what is going on in relation to the event that is not showing here.

**Comment by nomoregrapes** [comment]
This is in 01-01-27-02-07
`My <listEvent><event xml:id="160"><ref xml:id="119">sermon</ref></event></listEvent> took exactly`

Can we agree you shouldn't have an annotation inside any other annotation? So it should instead look something like this...
`My <listEvent><event xml:id="160">sermon</event></listEvent><ref xml:id="119"></ref> took exactly`
(aka, not my problem)

**Comment by KPalmerHeathman** [comment]
So how should we now be marking up families/couples? At the beginning we were advised:
`I went to see the <persName id="123"><persName id="124">Murrays</persName></persName> at their house`
I have a couple to markup now, so want to make sure I'm doing it right.

**Comment by peterwebster** [comment]
Two separate issues in play here:

1. @KPalmerHeathman @DurHHHI the particular example here, where there is both an event and a ref should probably be dealt with by <event mark up and cross-reference to the publication. Strictly speaking, the thing being marked up is not (at this point in the journal) a publication.

2. But, the point about people being referred to collectively that Katie points out is a real one. @nomoregrapes : will your suggested markup above produce two icons next to each other after the marked up text? If so, that's fine, but there will be nested examples in various places in existing XML. Is it a real headache to allow the nesting?

**Comment by DurHHHI** [comment]
Many examples of this issue - difficult to click to second box, if even permitted. How best to rectify? 
![icon double - no does not display event unbolded sermon](https://user-images.githubusercontent.com/32575577/42335451-5652ce96-8078-11e8-996e-f7b97a5987cb.JPG)
--//--
![icon double - two persons one visible - not working well_3](https://user-images.githubusercontent.com/32575577/42335478-6fd19de8-8078-11e8-9068-953bb22cdf37.JPG)
--//--
![icon double - two persons one visible - not working well_2](https://user-images.githubusercontent.com/32575577/42335481-745f03d2-8078-11e8-932a-a33be7a146ef.JPG)

Oddly, this one did work just fine -
![icon double - working well](https://user-images.githubusercontent.com/32575577/42335502-83e6c402-8078-11e8-8936-ec5c95343d36.JPG)

**Comment by peterwebster** [comment]
@nomoregrapes implementXSLT to allow two nested persons, displaying with a single icon with both annotations in one box.

@KPalmerHeathman @DurHHHI in future XML, we should not mark up anything with more than one type (ref and event, say) but mark up as one and use a cross-ref to the other.
We'll need to review existing to see how many of these there are already, and figure out how to redo them.

Q: are there pairs of orgs, or places, or any other type that might be referrred collectively as these people are? If so, we'll to do the same as persons for them.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI 
Could you think about this question: "are there pairs of orgs, or places, or any other type that might be referrred collectively as these people are? If so, we'll need to do the same as persons for them."

**Comment by peterwebster** [comment]
Could @KPalmerHeathman and @DurHHHI feed back on the question above.

If not many, we can contemplate:
unnesting the tags, so giving two icons, or
marking up one, and using the cross-refs

**Comment by DurHHHI** [comment]
@peterwebster I can't think of any instances off the top of my head where there are pairs of orgs, places, etc. in nested tags. People, yes.

**Comment by KPalmerHeathman** [comment]
I can't think of any either.

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman that's great thanks. So, after talking to @nomoregrapes , dealing with the nested pairs of persons may well be possible, but is not instantly straightforward. I've asked Gregory to spend a little longer on this, but not too long, and to report back. In the meantime, if it proves to be very consumptive of time at this stage, what do you think about either:

(1) unnesting the pair, so you have:
`<person1>Smiths</person1><person2></person2>`, 

giving rise to two person icons side by side, or:

(2) removing person2 markup and relying on a cross-reference from the annotation to  person1.

Both involve some manual XML fixing in the GUI (more fiddly stuff, for which many apologies) but perhaps there are not hundreds of these, and I can probably generate a list of them to speed things up.

**Comment by peterwebster** [comment]
@nomoregrapes rereading the ticket above, if we took option 1, we'd need to think about the spacing of the two icons, as they each need to be easily clickable.

**Comment by nomoregrapes** [comment]
I've managed to make it work like this...
[example of nested people](http://10.245.28.108:3000/journals/02-07-09). Note that the 2nd Wilberforce(pers1757) doesn't have an indexed annotation so won't pop-up. The " Abps." shows two annotations in one box.
![journal_double-annotation](https://user-images.githubusercontent.com/1181194/43130165-fa645c98-8f2d-11e8-92d5-05587d695483.png)


However an annotation nested in an annotation of a different type (e.g. event in a reference) won't work. Our original [example](http://10.245.28.108:3000/journals/01-01-27-02-07) doesn't seem to do that, did we already change the markup?




Preferred [example of an annotation following an annotation](http://10.245.28.108:3000/journals/01-01-14) works, but is a tricky to click the 2nd icon. The option is to either use a cross reference, or put a space between the tags so that
`the <persName xml:id="130">Lord Mallard</persName><note xml:id="11" n="1"></note> was borne`
becomes
`the <persName xml:id="130">Lord Mallard</persName> <note xml:id="11" n="1"></note> was borne`

**Comment by DurHHHI** [comment]
Ok, thanks for this heads up @peterwebster / Gregory. - should be able to find these occurrences in XML.
@peterwebster, I'm assuming any instances where this occurs in 14/15 will have to be fixed via direct editing of the repository text once this is enabled?

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI take a look at the archbishops example and feedback? If we're happy with this, then on our next call we need to establish that we're clear on how to handle these in XML in future. Then we can close this ticket.

**Comment by peterwebster** [comment]
Having discussed with Katie and Hilary, this is now a matter for documentation only.
