### ISSUE TITLE
Straight quotes vs. curly quotes

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#13]
@KPalmerHeathman  
Julia, just to note as you will be checking transcriptions before sending to Peter for XML conversion, Peter says that we do not need to manually change single/double curly quotation marks to straight quotes in the transcription file. This will be done on Peter's end before being returned to us for XML markup. 
Great news, as saves a little time in the transcription check!

**Comment by dpl0js** [comment]
@KPalmerHeathman Splendid. Phew! Less scope for error.
