### ISSUE TITLE
Names including special characters in the search

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#132]
An issue with the search annotations:  if you have a person with a name with a special character, we should expect that users will not search using the special character: is there any way to enable a search for 'regime' to find instances of r [e acute]gime ?

**Comment by peterwebster** [comment]
See screenshot at #130

**Comment by nomoregrapes** [comment]
An example is `Caröe, William Douglas` should be searchable by `Caroe`.

I'll research the best way to technically do this, which should mean I don't have to make my own list of characters for transliteration.

**Comment by nomoregrapes** [comment]
I've been looking into the solr schema settings for this, but haven't been able to get it working (yet).

It might be helpful if I find another example. Perhaps one where special characters are used in journal text (not annotation data).

**Comment by peterwebster** [comment]
05-02-26-03-11.xml:         <p>There was a Lev&#x00E9;e afterwards  	</p>

04-11-08.xml:         <p><persName xml:id="648">Car&#x00F6;e</persName> the designer of that odious <persName xml:id="187">Farrar</persName> monument came to see me, &amp; together we went to the church, &amp; I authorised the erection.</p>

01-01-27-02-07.xml:               <cell rend="No_Spacing">&#x00A3;35</cell>

@nomoregrapes

**Comment by nomoregrapes** [comment]
Special characters are now searchable, both literally and similarly.
I.e. a search for "Caröe" will return the same results as "Caroe", which is 2 people and 3 journal entries.

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI take a look at the search, and try some examples of search terms without special characters: levee, regime, Caroe. If they look OK, do close this one down.

**Comment by KPalmerHeathman** [comment]
Seems to working as it should.
