### ISSUE TITLE
Cross-ref including people not specifically identified in TSV as linked

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#133]
<img width="1248" alt="screen shot 2018-07-02 at 3 11 56 pm" src="https://user-images.githubusercontent.com/32575577/42169002-70a27dd4-7e0a-11e8-9f6a-773b05dec28d.png">

**Comment by DurHHHI** [comment]
Clicking on Rosa, I found that beyond her brothers - the two IDs that are linked to her by manual input in TSV - she is also linked with Archibald Primrose - this is incorrect and doesn't seem to be coming from a TSV input error.

@peterwebster @KPalmerHeathman

**Comment by peterwebster** [comment]
In the TSV, Rosa [ID=713] is correctly cross-refd with Albert [222] and Edwin [293] but the ref to Primrose [292] is incorrect, and it all seems to be correct in the TSV.

**Comment by nomoregrapes** [comment]
This is another example of the problems at the end of the discussion for #116 
My checking is that Rosa and cross-refs to/from her now match the TSV.
