### ISSUE TITLE
Issue in table spacing

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#134]
In our call earlier @KPalmerHeathman @DurHHHI we identified a curious looking table in 03-02-01-02-02.

The XML looks like this:

![image](https://user-images.githubusercontent.com/5520710/42171230-abd9129a-7e10-11e8-9ace-4627247d686c.png)

**Comment by peterwebster** [comment]
Table cells, if not specifically instructed to do otherwise (ie. by fixing their width/height either in the stylesheet or in the XML) default in the browser to the width of the shortest span of text in them. In this case, for some reason, there are actually two tables (see the opening and closing tags in the highlighted section).
So, since all of the left-hand cells in the second table are empty, it hardly shows, pulling the right hand column to the left.
If you remove the extra table tags, making one continuous table, it should all line up.

Suggest you do this directly in the edit interface once it is available, so keep this ticket open until then.

**Comment by DurHHHI** [comment]
Done!
