### ISSUE TITLE
Display of person titles

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#135]
In this search, Sir Ian Malcolm appears just as 'Sir' in the search results.
![image](https://user-images.githubusercontent.com/32575539/42277731-3df0c1ca-7f90-11e8-9eed-d0a70fc8c325.png)

**Comment by KPalmerHeathman** [comment]
Also the case for other 'Sirs'

**Comment by peterwebster** [comment]
Without being able to see them, I think persons should be listed in this context as:

Surname, FirstName

and where there is a title

Surname, Title Firstname

**Comment by nomoregrapes** [comment]
This is non-issue.

@KPalmerHeathman the tell-tell sign is that the other people are not displaying with any name at all. This happens after I work on the code and don't restart the system (I still don't really know why it does that). It shouldn't happen when we have a stable system and I've stopped breaking things.

Proof that Sirs display correctly...
![search_people](https://user-images.githubusercontent.com/1181194/42376174-19fe3d88-8116-11e8-92c3-fd1bacfc526e.png)
