### ISSUE TITLE
History and Bookmarks

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#137]
Once repo is live and accessible offsite, I shall review both these and specify how to deal with them.

Includes deciding on the appropriate citation format in Bookmarks.

**Comment by peterwebster** [comment]
In Bookmarks, need to remove Email button

I need to define the citation format for the Cite option.

In History, remove Save.

I need to think about explanatory wording on both pages.

PW to think about what a download option for all bookmarks might look like.

**Comment by peterwebster** [comment]
In History, we need this bit of text:

'Your [n] most recent searches are given below. These are not saved, however, and will expire at the end of your session.'
And lose the heading 'Your recent searches'

**Comment by peterwebster** [comment]
In Bookmarks:
Let's have the citation format as:
The Henson Journals, Entry for [date], [URL]
The Henson Journals, Entry for [date to date], [URL]
The Henson Journals, Note 57, [URL]
The Henson Journals, [Title Firstname Surname], ......
...... [Place Name]
..... [Organisaiton Name]
...... [Author, <i Publication title</i]

And [if we have time], the results download could be structured the same way: three columns in XLSX and CSV

**Comment by peterwebster** [comment]
In Bookmarks, also add:

'Your bookmarked items from this session are listed below. Please be aware that these will expire at the end of your session.

**Comment by nomoregrapes** [comment]
For the citation format, I'm trying to keep use of the function that shows titles in search results.
![citations](https://user-images.githubusercontent.com/1181194/44410436-45b71200-a55c-11e8-85ce-c028f75ebaf0.png)

* "Journal entry for" gets replaced with "Entry for"
* References need the addition of author.
* People needs to be opposite order (no spaces). Should Title(Mr/Sir/Mrs) be included too?

**Comment by nomoregrapes** [comment]
I don't think search history has a maximum number, it will empty when the session expires (or is cleared by the server restarting). I've set "[n]" to how many searches are currently saved, I could just remove that number.
That whole paragraph will only appear if there are messages.

**Comment by nomoregrapes** [comment]
I've pushed the changes to henson-test.

Still need to work on the Bookmarks download feature.

**Comment by peterwebster** [comment]
- [x] Revised explanatory text to Bookmarks page
- [x] Remove email option from Bookmarks page
- [x] Remove Save option from History
- [x] Add explanatory text in History page
- [x] Implement human-readable format for citations
- [ ] Bookmarks download

**Comment by peterwebster** [comment]
Many thanks for all this @nomoregrapes: some feedback:

(i) in History, I think we can lose the [n] from 'Your [n] most recent searches'
(ii) in the citation format, I think we either need a line break before the URL, or perhaps a colon:

![image](https://user-images.githubusercontent.com/5520710/44449428-0208ea80-a5e6-11e8-95ee-49f2e856ed0b.png)

**Comment by peterwebster** [comment]
I think the download is probably only a medium priority, although nice to have @nomoregrapes : if, however, we don't get to it, we need to remember to remove the link

**Comment by nomoregrapes** [comment]
Updates made.
Download button removed, until I return to work on it again.

**Comment by peterwebster** [comment]
Will test bookmarks email and citation format once there is data in `test`.

**Comment by peterwebster** [comment]
This looks really good @nomoregrapes and would be just fine as it stands.

*If* there's time, I think on reflection a colon would look better in the citation format, giving:

The Henson Journals:  Entry for 20 February 1905

and particularly so for

The Henson Journals: Bailward, William Amias

What do @KPalmerHeathman and @DurHHHI think? Log into henson-test, search, bookmark some results and look at Cite function in Bookmarks.

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/44845175-bf2dbf00-ac44-11e8-9db5-b71f594502d8.png)
Tried clicking cite in my bookmarks view....

**Comment by nomoregrapes** [comment]
@KPalmerHeathman can you make some bookmarks on https://henson-test.durham.ac.uk/bookmarks (test_server) and then test again.

The "development" version continues to be unstable, and the pink stripes are ugly anyways.

**Comment by KPalmerHeathman** [comment]
sorry - knew it would be me doing something wrong!

**Comment by DurHHHI** [comment]
![topmarks](https://user-images.githubusercontent.com/32575577/44853360-aed60e00-ac5d-11e8-9644-56ad311ef5c3.JPG)

Looks good @nomoregrapes !

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman and what do you think about the colon vs comma issue after 'The Henson Journals' ?

**Comment by DurHHHI** [comment]
@peterwebster - I would prefer colon, but I'm not dying on that hill if there are other things to prioritize in the remaining hours. 'Tis just a scratch!

**Comment by nomoregrapes** [comment]
A colon requires using twice as many pixels as a comma. I might have to demand a shrubbery for all that work.

**Comment by peterwebster** [comment]
OK, this looks great now @nomoregrapes 
Leaving the ticket open as a reminder to me about the download, though I now doubt there would be time for it now.

**Comment by peterwebster** [comment]
Closing this now and creating a new ticket with label 'Dev Phase 2'
