### ISSUE TITLE
Missing annotation?

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#138]
@peterwebster 
Noticed this just by chance as JS sent an email about Dean's Yard (a drafted placename). It is not hidden in the TSV but does not appear as a placename option when searching for it on the website.

**Comment by peterwebster** [comment]
Could you screenshot this for me @DurHHHI ?

**Comment by DurHHHI** [comment]
@peterwebster Can ref to the pic in #144 as this was the search. I didn't screenshot because there was no visible placename option for the Dean's Yard tag.

**Comment by peterwebster** [comment]
@nomoregrapes could this be related to #132 , in this case, the difference between a curly and straight quote?
