### ISSUE TITLE
Icon annotation present but text 'not found'

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#139]
@peterwebster 
Have been going through the journal website page by page to try to find hiccups - seeing a few. Apologies, you're about to be inundated with github tickets - hopefully most of these can be closed quickly.

Seeing many examples - a few screenshots taken below to illustrate - of icons present without annotated text in the boxes. If these should be display=no they are still visible, if they are not supposed to be 'hidden', the text is not reflected.

![annotation not found_1](https://user-images.githubusercontent.com/32575577/42334457-30b14d46-8075-11e8-8e8a-7eee7a2776d6.JPG)

--//--

![annotation not found_2](https://user-images.githubusercontent.com/32575577/42334473-360b0c1e-8075-11e8-8962-922cd7e00f4a.JPG)

--//--

![annotation not found_3](https://user-images.githubusercontent.com/32575577/42334481-3cd8c8d8-8075-11e8-8fa0-50dac2d4ed45.JPG)

**Comment by peterwebster** [comment]
Could you take a look in the TSV and see what is supposed to happen with these? (I'm not sure which ones are the issue, from the screenshot) @DurHHHI

**Comment by DurHHHI** [comment]
Weird discoveries here, @peterwebster.

I've looked in the TSV for the first image example above - filename: 01-06-04-02-03-12. It has not been modified or opened since 24 March 2018.

Looking at this file, you can see under 'London Diocesan Conference' that, if there was an org markup tag, it has been removed.

<img width="833" alt="screen shot 2018-07-11 at 1 30 53 pm" src="https://user-images.githubusercontent.com/32575577/42571331-bacec6c8-850e-11e8-9111-bfdd13a3386e.png">

When checking under the the folder Master Data - Stage 6 Final, as you can see the orgName tag still appears.

<img width="1078" alt="screen shot 2018-07-11 at 1 32 17 pm" src="https://user-images.githubusercontent.com/32575577/42571621-95a81e20-850f-11e8-84d8-9f87b74df512.png">

**Comment by DurHHHI** [comment]
Now understand what is going on with the first example 'London Diocesan Conference'. Can/will fix this when have facility to edit within the repository directly.

The second issue with the above image is that in the third paragraph, the note after 'deep impression on the Conference' is supposed to appear. It is not set as 'do not display' in the TSV. Currently, it shows an annotation icon, but no text in the annotation box.

<img width="1078" alt="screen shot 2018-07-11 at 1 32 17 pm" src="https://user-images.githubusercontent.com/32575577/42571621-95a81e20-850f-11e8-84d8-9f87b74df512.png">


@peterwebster

**Comment by peterwebster** [comment]
@DurHHHI before I pass this on to Gregory, could you just confirm that it is still an issue today (it could be one of the temporary issues created when Gregory is under the bonnet.)

**Comment by DurHHHI** [comment]
@peterwebster checked on the website - fine today - text box appearing.

**Comment by peterwebster** [comment]
:-)

**Comment by DurHHHI** [comment]
@peterwebster I'm so sorry Peter, this might be temporary issues again but 'London Diocesan Conference' (orgID 148) in the example should also display text and after a refresh on the website and a double check in the TSV and XML, it still reflects an empty box on the website.

**Comment by nomoregrapes** [comment]
* [journal entry](http://10.245.28.108:3000/journals/01-06-04-02-03-12) refers to "London Diocesan Conference" but popup says "_Sorry, this annotation could not be found._" because orgID 148 doesn't exist.

Only 22 organisations were ingested (don't know why).
Reingesting... 
167 now ingested.
[London Diocesan Conference](http://10.245.28.108:3000/organisations/org148) now exists.

No idea why that happened, all working now? @DurHHHI

**Comment by DurHHHI** [comment]
Thanks @nomoregrapes !

**Comment by peterwebster** [comment]
If you're happy this is fixed @DurHHHI could you close this ticket?

**Comment by DurHHHI** [comment]
@peterwebster Closed this as orgs ingested and clickable but still noticing icons missing data.

For example:

<img width="1253" alt="screen shot 2018-07-20 at 12 51 00 pm" src="https://user-images.githubusercontent.com/32575577/43001087-dfcdb0a6-8c1b-11e8-91dc-3953b5a2c965.png">

Henry Graham definitely has an annotation in the TSV but his deets are not appearing.

**Comment by peterwebster** [comment]
@DurHHHI having spoken to @nomoregrapes we think this is now fixed; could you check around and close the ticket if you're happy?

**Comment by KPalmerHeathman** [comment]
Just spotted some odd characters in the organisation annotation for 'The Seven': Henson's clerical club in the St Alban's diocese, forerunner of the Brotherhood before Henson's translation to Westminster.ÃŠAs well as Henson, its members includedÃŠThomas Marsden, Richard Swallow, John Russell, John Pelham, William Dawson, and Henry Lake.

**Comment by KPalmerHeathman** [comment]
I can't see anything.
