### ISSUE TITLE
Treatment of passages relating to more than one day

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#14]
In volume 15, there are several instances where many days are related in ways that are hard to separate out, as well as being interspersed with lists, interleaved letters and the like. The issue is how these should be split, given that the governing structure is the daily journal entry in its own file (and thus viewed as a single item by the user).

After discussion with @KPalmerHeathman and @DurHHHI we propose the following:

(i) where a journal entry is dated by Henson, but includes narrative relating to one or more preceding days, this should be dated as at the day of writing, but (in the control file), a date range entered to reflect the spread.
(ii) in cases where there is a succession of what appear to narrations of particular days, but these are not securely dated by Henson, they are kept together with the preceding dated entry. This may therefore encompass interleaved letters, miscellaneous lists and other undated materials.

In the control sheet, the date range ensures that users browsing by any date within the range will find the entry. We have also inserted (in the control sheet) a Title field, in which such an entry may be labelled "1st March - 27th March with letters" or such like.

Could Katie or Hilary attach a Word document with some examples of the kind of clusters of material that would end up in a single file?

**Comment by dpl0js** [comment]
@peterwebster and KPalmerHeathman and DurHHHI

Got this now.  Thank you and agreed.

**Comment by peterwebster** [comment]
OK, closing this as agreed @KPalmerHeathman @DurHHHI
