### ISSUE TITLE
Icon with apostrophe issues ('s examples)

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#140]
Hey @peterwebster - still many examples where the ''s' wasn't corrected through the script fix and the icon is appearing before the 's. Is there a fix here (for now and future eps) or is it manual intervention when time allows?

Some examples here:

![apostrophe - still several examples of not fixed](https://user-images.githubusercontent.com/32575577/42334608-a1c634f6-8075-11e8-97f8-ff74091c96e4.JPG)

--//--

![apostrophe - still several examples of not fixed_2](https://user-images.githubusercontent.com/32575577/42334626-ab8918c8-8075-11e8-9515-d6701c52597b.JPG)

--//--

![apostrophe - still several examples of not fixed_3](https://user-images.githubusercontent.com/32575577/42334636-b11c6cfe-8075-11e8-8045-d97763662c90.JPG)

**Comment by peterwebster** [comment]
@DurHHHI could you let me know which filenames these are in?

**Comment by DurHHHI** [comment]
@peterwebster - these are just a few examples, there are unfortunately more. Two of the filenames would be 01-01-01 and 01-05-14, and I can track down the other for you.

**Comment by peterwebster** [comment]
@DurHHHI no, don't worry, these will do for now.

**Comment by peterwebster** [comment]
As per an email, this is a manual fix in 14 and 15 (apologies again). So, I leave this open as it cannot be acted on until we have the keys to the GUI.

**Comment by DurHHHI** [comment]
Hi @peterwebster As with the previous github ticket, @KPalmerHeathman has worked through this with the 14/15 entries that she has manually made public one by one. We've noted and will catch any remaining that might be lurking since the entire V14/15 has been made public when we move in and out of the repository. I think safe to close and we'll address as/when/if we see them?

**Comment by peterwebster** [comment]
Always pleased to close a ticket @DurHHHI ;-)
