### ISSUE TITLE
Frontmatter Vol 15 Display Issue 

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#141]
@peterwebster As you can see, something funny going on with vol 15 frontmatter:

![display vol 15 frontmatter](https://user-images.githubusercontent.com/32575577/42334758-12345830-8076-11e8-9139-94ef2dc80614.JPG)

**Comment by peterwebster** [comment]
Some sort of issue with the padding in the top of the display window @nomoregrapes

**Comment by nomoregrapes** [comment]
This was because the spacing in the style rules expect a journal entry to start with a paragraph (`<p>`).

Now fixed with better style rules.

**Comment by peterwebster** [comment]
@DurHHHI could you test this out, and close the ticket?

**Comment by DurHHHI** [comment]
@KPalmerHeathman just FYI if you get to this first

**Comment by KPalmerHeathman** [comment]
Yes this is fine now.
