### ISSUE TITLE
Tags sometimes unbolding when in bold underline

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#142]
@peterwebster Noticed several instances where tags appear to be 'unbolded' within a bold underline series. A couple of examples below.

![tag unbolding - multiple examples of this](https://user-images.githubusercontent.com/32575577/42334840-55669f0a-8076-11e8-8625-c116541756f8.JPG)

--//--

![tag unbolding - multiple examples of this_2](https://user-images.githubusercontent.com/32575577/42334854-5b2da442-8076-11e8-9426-762231a48a41.JPG)

**Comment by peterwebster** [comment]
What's the filename of the first one @DurHHHI ? Are they by any chance supposed to be double underlined?

**Comment by DurHHHI** [comment]
@peterwebster - no, this is supposed to be standard bold underline - have just checked this in the XML. The filename for the first image is 01-06-04-02-03-12.

**Comment by peterwebster** [comment]
@nomoregrapes some sort of issue with multiple style rules in the stylesheet ?

**Comment by nomoregrapes** [comment]
[link](http://10.245.28.108:3000/journals/01-06-04-02-03-12) and [link](http://10.245.28.108:3000/journals/02-11-08).
References(no other annotation) had some specific style rules that over-ruled the bold. Might have been left from early days of the website styling.

Fixed now.

**Comment by peterwebster** [comment]
@DurHHHI there you go..
