### ISSUE TITLE
Annotation box fail

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#143]
@peterwebster - I tried clicking everywhere to leave this annotation box but the website was having none of it. Only refresh or a move to previous or forward page killed it.

![screenshot-2018-7-5 the henson journals](https://user-images.githubusercontent.com/32575577/42334939-a892c47e-8076-11e8-92a6-3dec475e97f3.png)

**Comment by peterwebster** [comment]
Could you check it again next week and see if it recurs? While @nomoregrapes is under the bonnet strange things happen, but then he'll be away.

**Comment by DurHHHI** [comment]
@peterwebster yes, this can be closed - fine today!

**Comment by peterwebster** [comment]
@DurHHHI super....
