### ISSUE TITLE
Search results for dean's yard

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#144]
Searching the 'journals & annotations' option for deans yard brought me this view - persons and place tags not identified and an odd 'Sir' (this turned out to be Craik). I imagine you guys are already on this for annotation IDs but just in case, a screenshot.

![search - dean s yard](https://user-images.githubusercontent.com/32575577/42335063-0ade1c0a-8077-11e8-91a9-8717311252ef.JPG)

**Comment by peterwebster** [comment]
If you were try this again @DurHHHI , I suspect it has been solved.

**Comment by peterwebster** [comment]
Hhi @DurHHHI : could you check and see whether this is still an issue?

**Comment by DurHHHI** [comment]
@peterwebster Searchable now (though still with added nonsense characters) - 'place5'

<img width="1291" alt="screen shot 2018-07-20 at 12 12 46 pm" src="https://user-images.githubusercontent.com/32575577/42999612-52b76860-8c16-11e8-8b16-c0b09ef25010.png">
<img width="1258" alt="screen shot 2018-07-20 at 12 12 56 pm" src="https://user-images.githubusercontent.com/32575577/42999615-55b1bc5a-8c16-11e8-9838-d3d2a223fafb.png">

**Comment by peterwebster** [comment]
Hi @nomoregrapes : two things going on here:

(i) probably a curly quote not displaying right in the annotation
(ii) names of orgs, places, persons not showing in the search results.

**Comment by nomoregrapes** [comment]
Fixed these.
