### ISSUE TITLE
Font size presentation

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#146]
A few different instances noticed with font size and/or justification.

1) with bulleted lists (hidden bullets) - font size appears smaller/perhaps different justification also

![font size - tables or bulleted lists](https://user-images.githubusercontent.com/32575577/42335769-56643fa4-8079-11e8-89c4-2eff8b1fd7ce.JPG)

--//--

![font size - tables or bulleted lists_2](https://user-images.githubusercontent.com/32575577/42335774-5dc31c34-8079-11e8-985c-0c35e18e8957.JPG)

--//--

![font size - tables or bulleted lists_3](https://user-images.githubusercontent.com/32575577/42335782-62979348-8079-11e8-9c33-45165093373c.JPG)

**Comment by peterwebster** [comment]
@nomoregrapes could you confirm whether the font is different, differently coloured, or perhaps just with narrower line spacing in lists?

**Comment by peterwebster** [comment]
@DurHHHI it looks to me as if the first character in an unnumbered list is justified to the same position as a number would be. Is this a major issue?

**Comment by DurHHHI** [comment]
@peterwebster Not a major issue for me, just anticipating comments. It does look different when compared against the rest of the entry/ies.

**Comment by peterwebster** [comment]
@DurHHHI I meant the justification of the lists, rather than the font. Do you mean to say there are other lists that behave differently, or just that numbered and unnumbered are different to each other but consistently so.

**Comment by DurHHHI** [comment]
Hey @peterwebster - I believe it is the latter.

**Comment by peterwebster** [comment]
Let's wait and see whether this becomes an issue @DurHHHI

**Comment by peterwebster** [comment]
As this has occasioned no more comment since July, closing it now.
