### ISSUE TITLE
Manual fix of odd characters in annotations

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#147]
@peterwebster  The odd unwelcome character/symbol is still present when clicking through annotations and within the journal text as well.

Some examples to view:

![extra symbols - annotation 14 412](https://user-images.githubusercontent.com/32575577/42336061-5625c1f6-807a-11e8-9769-cf27da6378a9.JPG)

--//--

![extra symbols - annotation 15 44](https://user-images.githubusercontent.com/32575577/42336068-614101ea-807a-11e8-90ad-2cec550652f5.JPG)

--//--

![extra symbols - annotation 15 48](https://user-images.githubusercontent.com/32575577/42336074-66612d94-807a-11e8-8382-5e44fe5651fb.JPG)

--//--

![extra symbols 15 44](https://user-images.githubusercontent.com/32575577/42336079-6b16e630-807a-11e8-943c-5d9f0f10af9b.JPG)

**Comment by peterwebster** [comment]
Let's keep this one open until we have the repository in its final home. Then we can use them as training examples of fixing stuff in the interface itself, and at the same time it looks to me as if it's a matter of opening the TSV (in the text editor) and just deleting whatever there is in those places.
FWIW, this is one of the disadvantages of our workflow, in that stuff gets pasted from the web into our GDoc, which brings all sorts of invisible nonsense along.

**Comment by peterwebster** [comment]
See also #140 which may be worth doing at the same time @KPalmerHeathman @DurHHHI

**Comment by peterwebster** [comment]
As we've done our "training", adding this to the list of stuff to edit once the production deployment is available.

**Comment by DurHHHI** [comment]
This can close I think - we're on the look out for these. I've just recently been through the Persons TSV to clear out extra characters. Pulled out quite a few surplus '?' but, in doing so, ready for next ingest.

**Comment by peterwebster** [comment]
OK, closing this down now.
