### ISSUE TITLE
Date sorting of journal results in annotation views

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#149]
![image](https://user-images.githubusercontent.com/5520710/42382414-2086bf3e-812c-11e8-883a-5f625f3628e1.png)

**Comment by peterwebster** [comment]
@nomoregrapes are these sorting at the minute according to Solr relevance ranking?

**Comment by KPalmerHeathman** [comment]
Not sure if this is supposed to have been sorted, but these are still not displaying in date order.

**Comment by nomoregrapes** [comment]
There are 2 things that need fixing in #69 which covers this. I'll leave the examples there for me, and close this issue.
