### ISSUE TITLE
Font size in certain passages of <hi rend="bold"

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#151]
As in this example:  
![image](https://user-images.githubusercontent.com/5520710/42383553-732376f8-812f-11e8-91af-511926b45faa.png)

Could @DurHHHI take a look at the XML and report back on any differences from the usual? This is just bold text, in theory.

**Comment by DurHHHI** [comment]
@peterwebster - I'm not seeing anything unusual in the TSV - like you said, marked up as bold text.

**Comment by peterwebster** [comment]
Can anyone spot the mistake @DurHHHI @KPalmerHeathman ?  (This is a test whether you've become true XML monkeys yet).

`<p>
		 <p>
            <hi rend="bold">[417]</hi>
         </p>
            <hi rend="bold">Friday, November 23</hi><hi rend="bold superscript underline">rd</hi><hi rend="bold">, 1900</hi>
         </p>`

**Comment by peterwebster** [comment]
And, once you've spotted the mistake, a supplementary Q: how come this parses properly?

**Comment by DurHHHI** [comment]
@peterwebster '<'p'> <'p'>' ?

**Comment by peterwebster** [comment]
Full marks @DurHHHI !  This parses OK because it is, strictly speaking, well-formed. However, having a para within another para obviously interferes with the action of the stylesheet, so (once the GUI is ready), you should pick this one out and fix it. That is, move one of the opening <p tags to after the </hi </p
@KPalmerHeathman

**Comment by KPalmerHeathman** [comment]
Sorry!

**Comment by KPalmerHeathman** [comment]
fixed this example now.
