### ISSUE TITLE
Font and colour in <div

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#152]
@DurHHHI I think it's a different font, but @nomoregrapes can confirm. Do you dislike it, or were you just raising it as something to check?

![image](https://user-images.githubusercontent.com/5520710/42383743-12af4d32-8130-11e8-86b9-e47adfd83258.png)

**Comment by DurHHHI** [comment]
@peterwebster - raising as something to check, anticipating comments.

**Comment by peterwebster** [comment]
@DurHHHI closing this, but it can be reopened if it is disliked.
