### ISSUE TITLE
Extract instances of <..Name within <..hi in v16

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#155]
As per #85 , K&H need a list of all instances in 16 where these occur

`grep -E -o ".{0,25}ame></hi>.{0,20}" *.xml `

**Comment by peterwebster** [comment]
`05-12-17.xml:me id="113">Harold</persName></hi>.</p>
05-12-17.xml: id="208">Beeching</persName></hi> preached in S. Marg
05-12-17.xml: id="121">Custard </persName></hi>came in to supper, a
05-12-17.xml:y="no">Col: Dunlop</persName></hi>, just returned from
05-12-17.xml:56">Jim Dennistoun</persName></hi> is captain.  He see
05-12-18.xml:splay="no">Visitor</persName></hi>.  The Dean displaye
05-12-31.xml: id="117">Rashdall</persName></hi> &amp; <persName id=
06-01-14.xml:d="109">Archdeacon</persName></hi>: they are both exul
06-02-04-02-17.xml:5">Principal Story</persName></hi>.  At dinner to meet
06-02-04-02-17.xml:>George Adam Smith</persName></hi> on Saturday; and on
06-06-10-06-16.xml:y Mead&#8211;Waldo</persName></hi>. <persName id="951"
06-07-15-07-21.xml:711">Miss Montague</persName></hi>
06-09-09-09-15.xml:ame id="1104">Ware</persName></hi> preached on the Par
06-11-04-11-05.xml:>George Mackarness</persName></hi>, (33, Handforth Roa
06-11-18.xml:>George Mackarness</persName></hi> came in to supper. 
06-11-23.xml:e id="89">Athenaeum</orgName></hi>
06-12-30.xml:e id="215">Asquith</persName></hi><hi rend="i"> was in
07-01-27-02-01.xml:me id="1019">Addis</persName></hi> preached in the Abb
07-01-27-02-01.xml:me id="14">Raleigh</persName></hi> called at tea&#8211
07-01-27-02-01.xml:e id="121">Custard</persName></hi> was back from Switz
07-03-24.xml:ame id="403">Dicey</persName></hi> sitting beneath the
07-05-22.xml:M. Merle d'Aubigny</persName></hi>, a son of the <pers
07-07-07-07-11.xml: id="398">Morrison</persName></hi> was there bursting 
07-08-04-07-08-10.xml:me id="113">Harold</persName></hi>.</p>
07-08-04-07-08-10.xml:play="no">his wife</persName></hi>: also <persName id=
07-08-04-07-08-10.xml:me id="228">Warden</persName></hi><hi rend="i">. So I 
07-10-06-10-11.xml:38">Louis Philippe</persName></hi>.  In the evening he
07-12-29-12-31.xml: id="77">my sister</persName></hi>. Save for <persName
08-04-06-04-11.xml:Derville Teichmann</persName></hi>.</p>
08-07-12-07-16.xml:d="130">Cosmo Lang</persName></hi>, a Ritualist</cell>
08-07-26-07-29.xml:id="114">Conference</orgName></hi>.</p>
08-08-02.xml:22">North Carolina</persName></hi>.</p>
08-08-09-08-22.xml:display="no">Black</persName></hi>. <ref id="232">'Kil
08-08-09-08-22.xml:John Oliver Hobbes</persName></hi>. <ref id="233">'The
08-08-09-08-22.xml:id="1153">Jowett's</persName></hi> <ref id="234">Trans
08-08-09-08-22.xml:id="1443">Abbott's</persName></hi> <ref id="235">Philo
08-08-09-08-22.xml:id="1496">Maclaren</persName></hi>. <ref id="236">Grah
08-08-09-08-22.xml:="no">Oswald Dykes</persName></hi>. <ref id="220">'The
08-08-09-08-22.xml:liamson</persName></persName></hi>. <ref id="238">'My 
08-08-09-08-22.xml:lay="no">O'Donnell</persName></hi>. <ref id="240">Para
08-10-04-10-10.xml: id="117">Rashdall</persName></hi> was the preacher.</
08-10-04-10-10.xml:id="624">Caldecott</persName></hi> preached well on 'Y
08-10-04-10-10.xml:id="1938">Williams</persName></hi> for the <orgName id
08-10-12.xml:"250">Prof. Watson</persName></hi><hi rend="i"> called
08-10-12.xml:ont Central Mission</orgName></hi> in Pentonville, whe
08-10-13.xml:id="431">Masterman</persName></hi>, who seemed to me t
08-10-18-10-24.xml:e id="1862">Bonney</persName></hi> preached in the Abb
08-10-18-10-24.xml:ame id="898">Peile</persName></hi> preached at 7 p.m. 
08-10-25.xml:15">Prime Minister</persName></hi>. Probably he expect
08-10-29-10-31.xml:6">Durward Moffatt</persName></hi>, aged 17, a lad who
08-11-01-11-13.xml:ian Edward Malcolm</persName></hi> in S. Margaret's at
08-11-01-11-13.xml:Name id="427">Inge</persName></hi><hi rend="b">.</hi> 
08-11-01-11-13.xml:64">Balfour Wilson</persName></hi> ran up to me after 
08-11-01-11-13.xml:5">national society</orgName></hi>, where (as Russell 
08-11-29.xml:26">Ernest Bennett</persName></hi> accompanied me to t
08-12-02.xml:adys Mabel Lowther</persName></hi>, infant daughter of
08-12-03-12-04.xml:d="128">Archbishop</persName></hi>. In the crucial div
08-12-08.xml:shop of Colchester</persName></hi>. It is just 20 year
08-12-08.xml:1">Winfred Burrows</persName></hi> has declined the Ab
08-12-08.xml: id="1083">Loisy's</persName></hi><hi rend="i"><ref id
08-12-13-12-19.xml:me id="335">Hutton</persName></hi> arrived in good tim
08-12-13-12-19.xml:me id="14">Raleigh</persName></hi>, <hi rend="u"><pers
08-12-13-12-19.xml:ay="no">Waterfield</persName></hi>, &amp; <hi rend="u"
08-12-13-12-19.xml:46">Alan Henderson</persName></hi> came to tea after s
08-12-27-09-01-01.xml:56">Jim Dennistoun</persName></hi> went off in his mot
08-12-27-09-01-01.xml:"468">George Rudge</persName></hi> came into the vestr
08-12-27-09-01-01.xml:e id="922">Waggett</persName></hi>, whom I met on my w
09-01-03-01-06.xml:drey Margaret Hall</persName></hi>
09-01-03-01-06.xml:e Daphne Radcliffe</persName></hi> in <placeName id="6
09-01-10-01-16.xml: id="1083">Loisy's</persName></hi><hi rend="i"> chapte
09-01-10-01-16.xml:Hine&#8211;Haycock</persName></hi> brought in a friend
09-01-10-01-16.xml:no">Anthony Browne</persName></hi> also brought in his
09-01-10-01-16.xml:isplay="no">Philip</persName></hi>.  After supper I to
09-01-17-01-23.xml:Goss&#8211;Custard</persName></hi>, my Organist, to <h
09-01-17-01-23.xml:>Lilian Mary Jones</persName></hi>: afterwards I atten
09-01-17-01-23.xml:d="214">Freemantle</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml:4">Llewelyn Davies</persName></hi>, <hi rend="u">Barne
09-01-17-01-23.xml: id="398">Morrison</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml:e id="429">Manning</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml: id="449">Atkinson</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml:play="no">Rosedale</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml: id="208">Beeching</persName></hi>, <hi rend="u"><pers
09-01-17-01-23.xml:id="1911">Channing</persName></hi> (the solitary layma
09-01-17-01-23.xml:e id="444">Handley</persName></hi>, &amp; myself were 
09-01-17-01-23.xml:lin Scott Moncrief</persName></hi><hi rend="i"> &amp; 
09-01-17-01-23.xml:d="1910">Willcocks</persName></hi><hi rend="i"> was pu
09-02-21.xml:ydney Hewitt Still</persName></hi>, one of the choir&#
09-03-14-03-20.xml:="no">Mary Marsden</persName></hi>.</p>
09-09-19-09-28.xml:d="15">Oxford House</orgName></hi> round the Abbey.</p
`

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI I found this ticket again after it was too late to fix these in the XML. Here are the instances in v16 where there is a person nested within a <hi tag, giving rise to the issue noted in #85 . 
If you could fix these in the GUI after ingest,  that would be great. 

After that, should there be any to worry about in 17 and onwards? If so, I'll keep this ticket open.

**Comment by peterwebster** [comment]
@DurHHHI can you recall whether there is still an issue here, or can I close the ticket?

**Comment by DurHHHI** [comment]
@peterwebster I cannot recall. I'll close for time-being.
