### ISSUE TITLE
Configure this Github repo as the master repo for project data

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#156]
Just a note to self/us that this will need doing.

**Comment by peterwebster** [comment]
Unless we think that the Library Github is a better idea (discuss) @nomoregrapes

**Comment by peterwebster** [comment]
Give Olli access to this also

**Comment by nomoregrapes** [comment]
Config changed to this repo.

You can [see I did a test](https://github.com/peterwebster/henson/commits/master/journal-entries/14/00-10-01.xml) editing of a journal. If you click the 7-digit code to the right of a commit, you can see what changed on that commit.

Each [commit](https://github.com/peterwebster/henson/commits/master) will be attributed to whichever user was logged in doing the edit.

**Comment by peterwebster** [comment]
Sorry to be a dummy, but how do I create a new folder at https://github.com/peterwebster/henson/tree/master/journal-entries into which to upload all the XML for volum 16 when the time comes? I can create a new file, but not a new folder?  @nomoregrapes

**Comment by nomoregrapes** [comment]
It would be better to set up git on your computer. It's a bit like having dropbox, in that a folder on your computer becomes a copy of the github folders/files. You will then be able to create a folder named "16", copy the xml files into that folder in bulk (or work on them in that folder). The difference to drop box is that you have to intentionally tell it which changed files you want to commit back to Github.

I wrote some overly-detailed instructions "using git". I'll add a clarification for new volumes and send it to you tomorrow.

**Comment by peterwebster** [comment]
Done   https://github.com/peterwebster/henson/tree/master/journal-entries  @nomoregrapes

**Comment by peterwebster** [comment]
- [x] Olli invited
- [x] @nomoregrapes instruction retrieved from email
- [x] local clone set up on my machine
