### ISSUE TITLE
Tweak to WP stylesheet re indetation of unnumbered lists

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#157]
In light of how this looks, we could do with a tweak to the indentation of lists:  <ul

http://community.dur.ac.uk/henson.project/index.php/editorial-policies/

**Comment by nomoregrapes** [comment]
I've changed it so the bullets are with the paragraph (no longer in the margin) and thus the text is indented. Is that all that you wanted for the lists?

**Comment by peterwebster** [comment]
What do @KPalmerHeathman @DurHHHI now think of the indenting of bullets?

**Comment by DurHHHI** [comment]
Personally, I like this solution - thanks @nomoregrapes.

**Comment by KPalmerHeathman** [comment]
Thanks @nomoregrapes, it does look more elegant now.
