### ISSUE TITLE
Consider the layout of the footer

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#158]
@DurHHHI @KPalmerHeathman in the footer of the pages in the repository, we have the key of abbreviations to the left, and the login icon to the right. 

How much of a priority is it to recast this?

**Comment by peterwebster** [comment]
I shall specify which pages the key to the annotaitons should appear on.

@nomoregrapes to shift the login to the left.

**Comment by peterwebster** [comment]
Need to agree some sort of copyright statement and other information to be placed below the annotation key but above the login symbol. @nomoregrapes

**Comment by peterwebster** [comment]
In the annotation key, change 'Reference to published item', to 'Publication'

**Comment by peterwebster** [comment]
OK @nomoregrapes : let's have the annotation key on journal pages and search results, 

but not on the People/Places pages ( http://10.245.28.108:3000/people/person10 and http://10.245.28.108:3000/people  
And the same for Places, Orgs, and also Journal Entries

**Comment by peterwebster** [comment]
Also, lose them on the Saved Searches and Bookmarks pages.

**Comment by nomoregrapes** [comment]
I've set this to remove it from specific annotation pages (people/person10, organisation/org10,...) the annotation indexes (people, organisations,...), removed from journal entries (journals/04-10-10,...), and removed from the bookmarks page(/bookmarks).
It will still appear on the journals index (/journals).

Would it not make sense to keep it on "Bookmarks", because the icons are shown there (as they are in search results)?
How about Search History (doesn't show icons), should we remove the annotation key from there?

**Comment by peterwebster** [comment]
Apologies, I've confused the issue here, but it can be sorted out by:

- [x] (i) showing the key on journal entry pages (journals/01-01-01) but not at (journals/)  [I expressed this poorly earlier on]
- [x] (ii) [as you suggest] showing the key on Bookmarks.
- [x] (iii) removing from Search History

Sorry to be making you redo things.

**Comment by peterwebster** [comment]
Also @nomoregrapes :  the copyright statement agreed for the footer is now:

Copyright: the dean and chapter of Durham Cathedral, Durham Cathedral Library and the Henson project. 

If you can come up with the nice copyright symbol (c) then all well and good but not essential.

**Comment by peterwebster** [comment]
Marking up to critical as we definitely must have the copyright statement

**Comment by peterwebster** [comment]
I think we're all done here, so closing ticket: many thanks @nomoregrapes
