### ISSUE TITLE
Front and back matter in volumes

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#16]
There are several instances of back and front matter in the various volumes, which are not obviously related to a daily entry: lists of Henson's publications for the year, newspaper cutting pasted, a biographical conspectus of his life (front of 15).

I suggest that these are given their own files, named V14front.xml or V15back.xml, with (in the control sheet) an appropriate date range, for the whole volume if necessary, and a title "Front matter to volume 15" or 'Back matter to volume 14".

**Comment by peterwebster** [comment]
On the newly created Title for each file, see #14

**Comment by peterwebster** [comment]
Bringing @KPalmerHeathman and @DurHHHI into the conversation...

**Comment by dpl0js** [comment]
@peterwebster @KPalmerHeathman @DurHHHI Sounds good.  Perhaps we could ask the transcribers to include transcriptions of back and front matter in future.

**Comment by peterwebster** [comment]
@dpl0js I believe they already are - @DurHHHI and @KPalmerHeathman and I were inspecting various examples from 14 and 15 yesterday.
