### ISSUE TITLE
Iterate through XML files on Github to check existance

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#160]
Have a feature that iterates through all the XML files on Github, checking they have a matching journal (control metadata) in the repository. A no would have occurred if it was missing from the control file.

Report list of filenames missing from repository, and provide link to `journals/new` that is prepopulated with the filename and XML content.

This feature will be done per volume (folder on Github).

**Comment by nomoregrapes** [comment]
Partially done, but now I'm holding off work on this to first work on the bugs.

**Comment by peterwebster** [comment]
Although this would in principle be nice, the issue it is designed to catch is being prevented by manual checks further upstream, so closing this now.
