### ISSUE TITLE
Journals, editing

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#163]
Functionality in the editing of a journal...
- [x] Add dateFrom & dateTo fields.
- [x] add issues/controversies (topics) field.

**Comment by peterwebster** [comment]
@nomoregrapes this in file 05-01-01-01-04 , though it may only have been an issue in the preview

**Comment by peterwebster** [comment]
On the ampersand, also the case 02-12-04-12-07  - we checked the XML and they are there as &amp; so there may be an import issue

**Comment by peterwebster** [comment]
For ampersands see #176

**Comment by nomoregrapes** [comment]
I've learnt how to configure the date fields better(for non-recent dates), so on the journal editing form...
* date fields will be set to blank if no date is set (inc if you're creating a new journal) rather than "current date"
* blank dates will have the year drop down give options for 1900-1940
* if the date is already set, the drop down options are -5 years to +5 years of the date it is saved to.
* you can dates further afield by saving, editing again, repeat. Not that there should be need to edit dates at all.


When creating a new journal, it's worth remembering you need all the XML fluff to start of the content, or no content will appear (not that I would get confused when doing a quick test).

**Comment by peterwebster** [comment]
Thanks @nomoregrapes : I'm assuming that the reason for setting the dates this way is an issue with dates before 1 Jan 1900. This is fine, but I need to add a note to the documentation about it. Will test.

**Comment by nomoregrapes** [comment]
Using drop-downs for date fields uses less  of my own code and is generally more tested (more certain it will save a calid date of any time period).

The downside is that having a long drop down can be tricky UI. The default was +/- 5 years of today, so I altered that only slightly but I could make it a specific range or increase the range.

**Comment by peterwebster** [comment]
Successfully changed both DateFrom and DateTo, and added a new topic.

However, @nomoregrapes on save, I get the 'we're having an issue with the repo' error message, even though the change has been made.

**Comment by peterwebster** [comment]
This seems to be OK now @nomoregrapes so assigning to me for the documentation.

**Comment by peterwebster** [comment]
On reflection, this seems self-explanatory, so closing ticket.
