### ISSUE TITLE
Back/front matter

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#164]
The file name needs to be consistent, e.g. "V15front" (decide if it's front, frontmatter, front_matter)

Greg to then recognise those filenames and display as "Volume 15 front matter" as the title.

**Comment by peterwebster** [comment]
@nomoregrapes let's agree that the format in the control sheet (and thus the filename) should always be

V15_front
V14_back

- [x] @nomoregrapes to implement
- [ ] @KPalmerHeathman @DurHHHI to note for future reference
- [x] I shall update my documentation

**Comment by peterwebster** [comment]
Over to you @KPalmerHeathman @DurHHHI : do shut this down once you've noted the change in practice for future reference.

**Comment by peterwebster** [comment]
@nomoregrapes on the test server, I can see search results in the old format
![image](https://user-images.githubusercontent.com/5520710/44450146-13eb8d00-a5e8-11e8-9acc-29df343e3d7d.png)

**Comment by nomoregrapes** [comment]
Sorry, I hadn't actually pushed the changes to henson-test. I have now.

**Comment by peterwebster** [comment]
OK, this looks good to me @nomoregrapes 
Assigning to @KPalmerHeathman to acknowledge the change in working practice in relation to filenames, and close the ticket.

**Comment by nomoregrapes** [comment]
@peterwebster also for documentation on this, the filename is case sensitive. If the control file capitalisation doesn't match the file on github, it won't pick it up for the content.

**Comment by peterwebster** [comment]
Noted in docs.
