### ISSUE TITLE
References (publications) display

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#165]
Should be `Title:subtitle` (colon not comma).

**Comment by nomoregrapes** [comment]
Notes...
Subtitles are always joined by a colon (not a comma).
Unless it's a periodical or a book chapter, the subtitle will be in italics (em).
The Title+Subtitle will always be wrapped in single quotes, unless it's a Book (and not a Book chapter).

This is now done.

**Comment by peterwebster** [comment]
All good, now closing this.
