### ISSUE TITLE
Sermons (events)

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#166]
Agreed to ditch this as an annotation.

- [x] hide icon in the stylesheet of Journal XMl/content so it is not an annotation.
- [x] remove option in the search dropdown
- [x] delete all events, so that they're not found on search

**Comment by peterwebster** [comment]
Thanks for this @nomoregrapes although it doesn't look as if you've pushed these to test yet.

**Comment by nomoregrapes** [comment]
I've pushed the changes now.

My work is held up that I can't get the background processes working on the test-server. This is also needed to delete all the events (or unpublish them all, which is easier & similar to existing functionality).

**Comment by nomoregrapes** [comment]
Events are all set to unpublished. The line on the manage dashboard has a grey background, but events could be reingested (and published if desired).

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes for leaving the pipes open for this in future. Closing the ticket now.
