### ISSUE TITLE
Search results, bookmark all

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#167]
Add a bookmark all button to the search results page.

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes this looks good.

One more thing, then this can be closed. The 'Bookmark all' button actually appears in the Bookmarks view, which is superfluous and should come out.   https://henson-test.durham.ac.uk/bookmarks

**Comment by nomoregrapes** [comment]
Now removed on the bookmarks page.

**Comment by peterwebster** [comment]
Magic, thanks @nomoregrapes
