### ISSUE TITLE
Adjust rounding of numbers in places/organisations/people pages

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#171]
http://10.245.28.108:3000/journals
Over 230 journals have been transcribed, annotated, and made available here. Either search below, or select a particular day or range of dates.
Perhaps play around with the spacing between the two.

http://10.245.28.108:3000/people
I'm assuming that this number is auto-generated.
'Henson mentions over 700 different people within the transcribed journals. Search for them below.

And then replicate this one for organisations and places.

**Comment by peterwebster** [comment]
On the journals page, perhaps we could lose the dropdown (which currently defaults to Journals) since it just replicates the options that are available at the top of the page. Just the search box and the button? Low priority, however.

Changes outstanding on people/organisations/places.

**Comment by nomoregrapes** [comment]
Done.
The counts are rounded down to 10s. Doesn't have to rounded, but possibly makes it read better. People was rounded to 100, but that results in "over 0" for organisations!

**Comment by peterwebster** [comment]
Like the rounding of the counts. 'Over 1176' did read strangely; 'over 1170' is better. 'Over 1100' is the ideal, I think (ie. 100s), but I take the point about Orgs (although I think you mean Places)
I suppose Places could be set to 10s and the others to 100s, but it's a tiny point, so will mark this down to low priority, but there is one tiny thing:

in the journals page, I remember Philip preferred 'over 230 journal entries' in the narrative, which makes me think that the title should just be Journals (matching the text in the Menu). My fault, I missed that in the wash-up after the meeting.

**Comment by nomoregrapes** [comment]
This has been done.

**Comment by peterwebster** [comment]
Apologies @nomoregrapes I wasn't very clear. As well as changing the page title to Journals (which is done), but in the narrative, it should read ' over XXX journal entries have been..'

**Comment by nomoregrapes** [comment]
changed.

**Comment by peterwebster** [comment]
I'm sure this is fine, but it doesn't look as if it has been pushed to test yet  @nomoregrapes

**Comment by peterwebster** [comment]
There's a typo:  'Over 200 journal entriess'

**Comment by nomoregrapes** [comment]
Fixed

**Comment by peterwebster** [comment]
So all that remains of this is adjusting the rounding, but it's such a small point, adjusted to low priority.

**Comment by peterwebster** [comment]
See #209
