### ISSUE TITLE
Saved Searches

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#172]
At the minute, we have this visible for logged in users only  http://10.245.28.108:3000/saved_searches

but I don't think that the search results enable those users to save a search in the first place.

If this is trivial to enable, let's do so. If not, let's lose it entirely.

@nomoregrapes could you assess how much effort is involved. Whichever we do, it should be the easiest thing to do.

**Comment by peterwebster** [comment]
Saved Searches removed as an option, closing ticket

**Comment by peterwebster** [comment]
Ah, reopening this as the option to save a search is still available here for logged-in users  https://henson-test.durham.ac.uk/search_history

**Comment by peterwebster** [comment]
So (for the avoidance of doubt) let's remove the Save option there too @nomoregrapes

**Comment by nomoregrapes** [comment]
Removed.

**Comment by peterwebster** [comment]
Thanks @nomoregrapes, closing ticket now.
