### ISSUE TITLE
Ampersand not showing in journal entry page and in edit preview

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#176]

**Comment by peterwebster** [comment]
Transplanted from #163 

this in file 05-01-01-01-04 , though it may only have been an issue in the preview
Also the case 02-12-04-12-07 - we checked the XML and they are there as & so there may be an import issue

**Comment by nomoregrapes** [comment]
This is fixed, tested locally. It requires the journals be saved again(or reingested).

Due to #188, a reingest on test_server does not completely work right now.

**Comment by peterwebster** [comment]
OK, assigned to me to test once #188 is resolved.

**Comment by peterwebster** [comment]
Tested now and all good. Closing ticket.
