### ISSUE TITLE
Error on adding items to bookmarks (test)

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#177]
![image](https://user-images.githubusercontent.com/5520710/44449291-9a529f80-a5e5-11e8-8591-cae710a83115.png)

**Comment by peterwebster** [comment]
This was on 'Bookmark all results on this page'; seems to be related to the Issue result.

**Comment by peterwebster** [comment]
This makes me think that we should probably treat a search result for a topic slightly differently, as they have no descriptive content attached to them, they are just a pointer to journal entries. So, let's say that they shouldn't be added to Bookmarks using this function, but shouldn't throw an error either. @nomoregrapes

**Comment by nomoregrapes** [comment]
This does work on the development version (it bookmarks the topic).
The error is because the topic doesn't exist yet, so a link to it can't be saved.

I don't know why those non-existing results are appearing on the test site. I've created #178 to track that though.

**Comment by peterwebster** [comment]
OK @nomoregrapes , if it works on the dev version let's keep it. Keeping this open in order to test on `henson-test` once there is a topic for it to create a link to.

**Comment by peterwebster** [comment]
This is still an issue on test, so passing back over to Gregory.

**Comment by peterwebster** [comment]
@nomoregrapes I had a look at what was going on:

There are topics that exist and show up in search results (Revised Version)
https://henson-test.durham.ac.uk/?f%5Bsubject_ssim%5D%5B%5D=4c%2Fde%2F1d%2F27%2F4cde1d27-e5f0-41e4-ac45-70fd4b513bcb&q=Revised+Version&search_field=all_fields

and that also show up on journal entries
https://henson-test.durham.ac.uk/journals/00-12-02-12-14

but if you hit the link it throws an error:
https://henson-test.durham.ac.uk/topics/4c%2Fde%2F1d%2F27%2F4cde1d27-e5f0-41e4-ac45-70fd4b513bcb

**Comment by peterwebster** [comment]
@nomoregrapes this looks as if it is now solved; I've successfully bookmarked two topics from search results and then viewed them in Bookmarks. 
If you're happy you've done what you need to, close this one down.
