### ISSUE TITLE
Henson-test specific problems

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#178]
Not imported any journals yet. 
Need CIS to setup a process worker, so all the ingest steps can be done. Will also make it easier for me to do other things to check/fix data.

Seems that journals appear in search results, despite not existing yet. Could be that the search index of development and test_server is mixed up.

Olli has reported problems on the test server for other rails applications. Not clear if this is due to Henson, needs to be investigated by Olli/CIS with much importance.

**Comment by peterwebster** [comment]
@nomoregrapes annotating this regarding the Publish All functions in Admin dashboard on test.

**Comment by nomoregrapes** [comment]
The issue is fixed on test_server.
Taking so long to fix this is due in part to a bad bit of coding by me that I think I added while trying to solve the problem.
