### ISSUE TITLE
Removing undocumented elements at Stage 7

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#18]
Acting on advice from KPH, HI, either strip out ID attributes from undocumented elements, or add another attribute that instructs the application to not display.

**Comment by peterwebster** [comment]
@nomoregrapes at the final stage of XML processing, there will be some elements (persons, etc) who (it will have been decided) are not worthy of their own annotation in persons.tsv. I propose to go through the XML and change the markup to reflect this. What would you prefer:  an ID set to zero, or some sort of new attribute: display="no" or somesuch. 
The result will need to be that there is no icon shown to the user.

[ @KPalmerHeathman @DurHHHI : there's allso be a need to remove these people/places etc from the TSV store, so they don't crop up in the search indexes. Let's discuss on Monday.]

**Comment by nomoregrapes** [comment]
I would prefer an attribute like display="no".

For your second point, how about having a column in the TSV named "skip" or "ignore". I can adjust the ingest script so that it ignores any row with the value of "yes" (or some similar word you decide). This allows the data to remain in the TSV(unindexed) in-case decisions change.

**Comment by peterwebster** [comment]
@nomoregrapes just rounding this one up. 
(1)  Let's agree that in the XML, elements without corresponding annotations will have attribute display="no" (I'll revise the XML schema to that effect)
(2) As discussed by Skype, each annotation TSV file will have a NoIndex field which can be set to No, which keeps that ID out of the indexing. (I shall revise the data model document to reflect this.)

**Comment by peterwebster** [comment]
Closing this as it is superseded by #96
