### ISSUE TITLE
Height of search button in WP

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#180]
A minor point, but perhaps one for a spare five minutes.

The search button is slightly squashed in WP, so the text is not centred vertically.

![image](https://user-images.githubusercontent.com/5520710/44717127-1b150e00-aab4-11e8-9cd8-43985e4db995.png)

**Comment by nomoregrapes** [comment]
Done.
Test in Chrome and Firefox.

**Comment by nomoregrapes** [comment]
This is done.
Tested in Chrome and Firefox.

**Comment by peterwebster** [comment]
Marvellous @nomoregrapes
