### ISSUE TITLE
Retain Gregory's Bitbucket access after contract end

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#181]
@nomoregrapes just a aide memoire on this, as your access is I think tied to your Durham email, and so someone (within CIS) will probably need to do this, and may require Julia's authorisation to do so, so it may take a couple of days.

**Comment by nomoregrapes** [comment]
If my Durham user account/email is retained, then all things dependent on that will likely be okay. Julia would have to request for my account to be extended to a specific date before it's deleted. I'm not sure how quickly/often CIS delete accounts, but it's the contract-end date they look at unless other agreements have been made.

Bitbucket is barely used now.
Durham's enterprise version of Github (https://source.dur.ac.uk/) is more important, and my access to that requires me to have my Durham uni account (it got put in a special group).

**Comment by peterwebster** [comment]
OK, I'll drop Julia a line and ask her to contact CIS and extend for a while to allow us some wriggle room.

**Comment by peterwebster** [comment]
Email now sent; keeping this open until it is resolved. @nomoregrapes

**Comment by peterwebster** [comment]
So, not yet resolved so far as I know, but in hand. Closing ticket.
