### ISSUE TITLE
Push to Github? checkboxes should default to no

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#187]
To prevent changes made in henson-test GUI being pushed to the master data in Github, these should default to No:  

/journals/xxxx/edit

It doesn't seem to be there on the annotation edit views (/person123/edit), nor on the create-annotation view (/people/new),, so perhaps there is only one.

**Comment by peterwebster** [comment]
I need also to write up the process under which I might upload volume XX to henson-test in order to make sure that there are no silly issues in the data, to avoid having to fix them manually in production

**Comment by nomoregrapes** [comment]
@peterwebster Would it be better if this defaulted to *unticked* on the test_server but defaulted to *ticked* on the production server?
The benefit being that Github serves as an audit trail (e.g. who made garbled edits on the production site & what other journals did that edit on that day?) so they can then be fixed.

For documentation...
The annotations aren't individual files, so on the /manage dashboard there is an "Export to Github" for each type. It recreates the full TSV for the type and saves that to Github (although bare in mind that it won't have index=no rows).

**Comment by peterwebster** [comment]
Yes, that sounds good: defaults to unticked on test, but to ticked on production. (Do you have to code it so it checks which server it is on before loading the pages?)

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Tested on test, will check on production tomorrow.

**Comment by peterwebster** [comment]
Tested on production, all good. Closing ticket.
