### ISSUE TITLE
Topics, problems on servers

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#189]
Topics = issues, controversies, or keywords attached to Topics or Events.

If the topics get created (ingest or manually) on the server, there are problems that make it seem like they don't exist (or cause broken links). This is due to the IDs.
Rather than let the system decide on the random ID, I will control this a bit. They will still look random, so URLs will be like "/topics/5ac749fbeec93607fc28d666be85e73a" but will not have slashes or dashes in. They will actually be "random" based on the topic title(text), so if we have to delete them all and reimport then the IDs will be the same.

**Comment by peterwebster** [comment]
@nomoregrapes this looks as if it is solved? I've added new topics to a journal entry, including more than one at once. They also seem to crop up in search, and I can bookmark them ( see #177 ).

If you're happy, assign this to me, as I have various things to document.

**Comment by peterwebster** [comment]
To document:

(i) new topics can be added from the Edit Journal view, which also allows a search first to check existence of similar or same issues and check spellings;
(ii) it isn't possible to remove a topic from a single journal entry. Instead, click through to Edit Topic and set to Admin.
(iii) from Edit Topic, also possible to change the title of the topic, which then applies across the site.

**Comment by nomoregrapes** [comment]
Yes, this is solved.

(i) Additional note... searching for "Grooming" would also find a topic "grooming" (case insensitive). However adding a topic (via journal ingest or editing) you should type in a case-sensitive match of the existing topic, so that it doesnt create a new (different) topic. Same as if the topic title has a hyphen, space, etc or not (e.g. choir-boys, choir boys, choirboys, will create 3 topics).

(ii) could be a future development task.
There will need to be some work to tidy up topics, e.g. set "choirboys" to admin & ensure all those journals get "choir boys" added as the topic. Being able to remove "choirboys" from journals would make it clearer that it was a disused topic. I'm sure K&H will manage, and with future volumes will become more careful with topics.
