### ISSUE TITLE
Circled list numbers

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#19]
I've found a couple of instances of numbered lists (usually within copied letters in the journal) where Henson has circled the numbers with his coloured crayon at a later date. If we are treating coloured underline as bold underline, and coloured marginal lines as italic, should these circled numbers be a) bold underlined or b) italicised? I think bold underline is more noticeable as it's just a single digit, but would prefer to check.

**Comment by dpl0js** [comment]
@KPalmerHeathman @peterwebster @DurHHHI @williamsonphilip 
I agree with your solution:  bold underline.

**Comment by KPalmerHeathman** [comment]
Thanks Julia, I'll go with that.
