### ISSUE TITLE
Document V16 ingest

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#190]
This is a good example.

I was ingesting Volume 15 on test_server and it alerted me `An error was encounted reading the file from Github.` It actually stopped the ingest from that point onward (maybe I should change it so it attempts the others, but it could be a symptom of Github being offline etc).
I look on the logs page, and scroll to see a row...
`[2018-09-05 17:42:55][henson] ERROR: Could not read XML from Github. 02-11-30-12-02.xml`

I can open up the control file I was ingesting. It includes this row...
`150046	02-11-30-12-02	30-Nov-1902	02-Dec-1902	15	131	134	grooming of choir boys`
Looks fine, so I look in the files on Github. 
Closest thing to it is `02-11-30-12-03.xml`
I check the contents, and it only goes up to the 2nd.
Must have been a typo in the filename.

It's possible that filename has been fixed elsewhere, but I can the make the filename change and upload it to Github. Then I can run the ingest again.

**Comment by peterwebster** [comment]
Thanks @nomoregrapes : a couple of questions/comments.

(i) where did you get the 'An error was encountered..' message - on the dashboard?

(ii) yes, let;s change it so the application doesn't stop at the first error but tries to process every line in the control sheet.

(iii) also, change that filename and we'll use that file as the canonical version from now on.

**Comment by nomoregrapes** [comment]
(i) Yes. However by doing (ii) it will not be possible to show it. Instead you'll get the usual message `Journal data and contents were imported. W rows read. X entries created/updated. Y rows skipped. Z rows caused errors.`. If Z is greater than 0 then looking at the logs page is good advice.

(ii) changes made, will be in next push

(iii) already did that.

**Comment by peterwebster** [comment]
OK @nomoregrapes : I shall at some point do a test ingest of some of v16 to henson-test, and will look out for this, and document.

**Comment by peterwebster** [comment]
As I plan to test the ingest process on volume 16 when the time comes, closing this ticket.
