### ISSUE TITLE
Publish All buttons on dashboard fail

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#191]
The Publish All buttons for Topics, References and Notes all seem to fail, and redirect out to the WP homepage.
This was after I added hit the same for Journals, Persons, Places and Organisations, all of which seemed to work: I got the 'XX will be published' message in each case.

**Comment by peterwebster** [comment]
Although, the resque shows that all the jobs are in the queue, so the issue may just be with what the GUI reports that it is doing (rather than with whether it is doing it or not)

**Comment by nomoregrapes** [comment]
As you observed, Topics, References and Notes do create the jobs.
They then try to redirect to the homepage (which redirects to WP & that can't display the blue box message), but they need to redirect to the manage dashboard.
It's a simple thing for me to fix.

**Comment by nomoregrapes** [comment]
This is done.

**Comment by peterwebster** [comment]
Tested this out, and all fine. Many thanks @nomoregrapes : closing ticket now.
