### ISSUE TITLE
Bookmarks download

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#192]
Implement the option to download accumulated bookmarks, probably in CSV and/or .xlsx

**Comment by peterwebster** [comment]
There is already some code for part of this, but the option is hidden from the end user.

**Comment by nomoregrapes** [comment]
This is now done, and available on [test](https://henson-test.durham.ac.uk/bookmarks).

When opening a CSV file, LibreCalc asks how it is delimited (commas, quoted fields). I think Excel usually insists it's guess is correct so could somebody try downloading their Henson bookmarks and opening the file in Excel.

The file is based on the format in the citation view. We can change it around if you want, or assume people will change the file to suit their needs anyway (e.g. numbering the rows).

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI could one of you who has Excel test this out: go to the test server, bookmark some things, hit Download in the Bookmarks page and see what happens when you open the file in Excel?
Being a Microsoft refusenik, I can't test this one.

**Comment by peterwebster** [comment]
@nomoregrapes tested this out this morning, and the file and the formatting look fine. However, it only outputs the first page of bookmarks; I think the expected behaviour will be that it outputs them all.

**Comment by nomoregrapes** [comment]
FYI...
After the first page(10) bookmarks, the order might not be matched between the CSV and the web page. It will potentially be slow if you have loads of bookmarks.

This is now done.

**Comment by peterwebster** [comment]
This is great @nomoregrapes . I think there are probably things we might (in the longer term) consider adding to this download, such as date information and other associated data, but for now I shall close the ticket.
