### ISSUE TITLE
Annotation icons partially obscured by underlining of line above

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#193]
In some cases this occurs. We might want to consider increasing the line spacing, but this may have a more general effect across the whole site that we dislike. For discussion.

See p. 404 in https://henson.durham.ac.uk/journals/00-10-21-11-03

**Comment by nomoregrapes** [comment]
Done this and pushed to [test](https://henson-test.durham.ac.uk/journals/00-10-21-11-03).

You can play Spot the Difference...
![journal-line-spacing_1](https://user-images.githubusercontent.com/1181194/46282215-d3791a80-c568-11e8-8bb7-1286473eb193.png)

On the first paragraph (no bold) it's barely noticable which one has more spacing.
![journal-line-spacing_2](https://user-images.githubusercontent.com/1181194/46282220-d6740b00-c568-11e8-89f9-2115a61ac12e.png)

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman 

Spot the difference:  

More space between lines
https://henson-test.durham.ac.uk/journals/00-10-21-11-03

Less
https://henson.durham.ac.uk/journals/00-10-21-11-03

**Comment by DurHHHI** [comment]
@peterwebster Maybe it is my browser (chrome) but I'm not seeing much of a difference. Am I supposed too?

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman sorry, rather enigmatic, that. The questions are:

(i) is there now enough clearance between underlining and an annotation icon on the line below, and if so)
(ii) since Gregory has achieved that by widening the spacing between lines, is this spacing now too wide?

**Comment by peterwebster** [comment]
@nomoregrapes this is now a browser variation: for me it looks great in FF, but not so good in Chrome.

![image](https://user-images.githubusercontent.com/5520710/46294088-eb629580-c58c-11e8-988f-b9636bf3e421.png)

Perhaps experiment with a little more extra spacing, or (I'm not sure how easy this is), having a less thick underline?

**Comment by nomoregrapes** [comment]
I thought I had fixed this, and it looks okay in Chrome (Linux). @peterwebster could you [look again](https://henson.durham.ac.uk/journals/00-10-21-11-03) for me?

**Comment by peterwebster** [comment]
@nomoregrapes yes, not sure how this one slipped through the net; I just had a look in FF, Chrome and IE (all on Windows) and it looks fine. So, closing the ticket.
