### ISSUE TITLE
Total number of organisation not populated in Organisations view

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#195]
https://henson.durham.ac.uk/organisations

**Comment by nomoregrapes** [comment]
"over 0 different organisations" is not untrue.

It's doing (69/100)*100 = 0. 
So the code will need to be changed to 10s, or it will correct itself once there are 100+ orgs.

**Comment by peterwebster** [comment]
See #171

**Comment by peterwebster** [comment]
See #171
