### ISSUE TITLE
Add page titles

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#196]
Another stylistic thing that might be considered worthwhile...

Adding page titles (i.e. the text you see on tabs or at the top of the browser).
* [search result for ella](https://henson.durham.ac.uk/?utf8=%E2%9C%93&search_field=all_fields&q=ella) shows "ella - The Henson Journals"
* [bookmarks](https://henson.durham.ac.uk/bookmarks) shows "Bookmarks - The Henson Journals"

But a lot of pages like [People](https://henson.durham.ac.uk/people) shows the same default title "The Henson Journals", and that is trivial to change.

**Comment by nomoregrapes** [comment]
This is now done.

Most of these I'm using the page title, plus the section, plus the site name.
E.g. `Scarletts - Organisations - The Henson Journals` and the index page is `Organisations - The Henson Journals`

For journal entries I skipped the section, because it seemed better to have `4th October 1904 - The Henson Journals`, however the journals index page is still `Journals - The Henson Journals`

**Comment by peterwebster** [comment]
This is looking very good @nomoregrapes : many thanks.

One tiny thing, which in itself doesn't matter much. Is there a reason why the order is different search results: Law - The Henson Journals Search Results, rather than Law - Search Results - The Henson Journals ?  In itself it's fine, but just inconsistent.
https://henson-test.durham.ac.uk/?f%5Bhas_model_ssim%5D%5B%5D=Journal&q=law&search_field=all_fields

**Comment by nomoregrapes** [comment]
Good spot, that's a terrible & ugly inconsistency from Samvera/Blacklight. I since tried overriding the title on search results but it hasn't taken.

Leave this assigned to me and I might manage to fix it later.

**Comment by peterwebster** [comment]
@nomoregrapes thanks Gregory. As I said, not a big deal.

**Comment by peterwebster** [comment]
@nomoregrapes assigning this to me for the time being, as I think there are other things ahead of this in the queue.

**Comment by peterwebster** [comment]
As this is native to Samvera, I'm going to close this one. @nomoregrapes had one attempt at overriding it but it didn't take, and I don't think it a good use of time to try too much more. It is a very long way down the queue.
