### ISSUE TITLE
No italics at all in journal entries!

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#199]
I don't know how we haven't noticed this before, but I've just spotted it while checking entries to make public. Italicisation we have put in to represent the marginal lines in the journals is not displaying. Putting it in manually just seems to make the enclosed text disappear altogether. HELP!

**Comment by peterwebster** [comment]
@KPalmerHeathman could you let me have an example or two?

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/45823677-196eec80-bce6-11e8-91bf-9281e0146e96.png)
Above in the cleaned transcription before splitting to XML files. Below as appearing online.
![image](https://user-images.githubusercontent.com/32575539/45823727-428f7d00-bce6-11e8-9d25-c922411270f2.png)

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/45823794-66eb5980-bce6-11e8-8e57-957c1fedb408.png)
![image](https://user-images.githubusercontent.com/32575539/45823823-78346600-bce6-11e8-8c7e-4da7c251ff8e.png)

**Comment by peterwebster** [comment]
In 03-06-07, these are marked up hi rend="italic bold underline", so I guess that the stylesheet doesn't know what to do with these. Assigning @nomoregrapes

**Comment by nomoregrapes** [comment]
Not a result of that specific combination, but was an error with any italic text in the content.

Fixed, and will be in the next update.

**Comment by peterwebster** [comment]
FYI  @KPalmerHeathman    https://henson-test.durham.ac.uk/journals/03-06-07   https://henson-test.durham.ac.uk/journals/03-05-21 

Thanks @nomoregrapes . Closing now.
