### ISSUE TITLE
Identify suitable location on Durham shared drives for versions of record of data

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#2]
The Durham-based team will need a set of file directories in which to keep:
(i) Word transcriptions
(ii) volumes in progress of markingup
(iii) persons/places/organisations information
(iv) versions passed to @peterwebster for conversion
(v) and stages thereafter, including the final versions for ingest to the repository.

@peterwebster will specify this workflow shortly, but a location accessible to the whole team in Durham should be identified first.

**Comment by peterwebster** [comment]
I'm assigning this to Julia @dpl0js and also drawing you into the thread by means of an @ message.

**Comment by peterwebster** [comment]
The workflow is now drafted at https://github.com/peterwebster/henson/wiki/Data-workflow

**Comment by peterwebster** [comment]
This is also relevant to issue #3 and so I connect the two by means of a hashtag ( FYI @dpl0js )

**Comment by peterwebster** [comment]
@dpl0js I've now suggested a set of folders to go somewhere that the whole Durham team can access, at https://github.com/peterwebster/henson/wiki/Data-workflow (at the end). Do note also the suggestion about Dropbox.

**Comment by dpl0js** [comment]
Dear Peter,


Thank you again.  This looks excellent, including the new stage of file-splitting and provision for a separate folder for annotation.


Philip has emailed to say that we can't now occupy the room in the College we had been allocated previously; but he has received an assurance that the new room will definitely be in the Palace Green area, and will be up and running by 2 October.  It will have 3 desks, which could be very useful!


J



________________________________

**Comment by peterwebster** [comment]
As discussed @dpl0js , it should hopefully look something like this, and be accessible to all four of the Durham team.

![image](https://user-images.githubusercontent.com/5520710/30803502-b8b547a6-a1e1-11e7-97b5-27d3a9d67129.png)

**Comment by dpl0js** [comment]
Dear Peter,


Thank you, I will ask for help from the CTS field team in setting it up.


Best wishes,

Julia

________________________________

**Comment by peterwebster** [comment]
That's great @dpl0js . When you reply to a comment, could you possibly tag me as @peterwebster ? That way, I receive an alert.

**Comment by dpl0js** [comment]
I have requested a facility for shared files across departments from CTS.  I will be contacted soon.  There might be a facility for guest access, too.

**Comment by peterwebster** [comment]
If there is the option for me to have direct access to these folders, that will certainly help @dpl0js but it isn't essential.

**Comment by dpl0js** [comment]
Ok, I will do what I can @peterwebster.  Thanks for your guidance on tagging and attaching files.  Did you receive the induction programme for K and H, also attached here. 
[Induction programme (Hilary and Katie) Oct 2017.docx](https://github.com/peterwebster/henson/files/1330688/Induction.programme.Hilary.and.Katie.Oct.2017.docx)
