### ISSUE TITLE
Illegible word?

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#20]
Can anyone make out the underlined words below? I think it's 'bene esse' and 'esse', which according to the wisdom of google is 'well being' and 'essence'.

![illegible words](https://user-images.githubusercontent.com/32575539/31669976-7dfefa02-b34e-11e7-9d24-40e5611678a5.png)

'Bishops who would accept for ordination a candidate, otherwise eligible, who held that episcopacy is of the ?well being? but not of the ?essence? of the Church'.

Can anyone with Latin confirm?

**Comment by DurHHHI** [comment]
@KPalmerHeathman  - leaning towards bene esse with rudimentary latin

**Comment by dpl0js** [comment]
@KPalmerHeathman @DurHHHI agreed (for now)! But will confirm.

**Comment by williamsonphilip** [comment]
Yes, the Latin for 'well being' or maybe something closer to 'best interest'.  It perhaps has a more technical legal meaning (anything in Halsbury?), but this seems to be adequate here.  I'd be inclined to leave it without explanation, but it is a fine point.   If more Latin appears, it might be useful to find if there is a good online Latin-English dictionary, although Google Translate gets the gist.

**Comment by KPalmerHeathman** [comment]
Thanks @williamsonphilip. I think we can now be sure that bene esse and esse are what's written. I've just check Halsbury and there's nothing on either.

**Comment by peterwebster** [comment]
The difference between the two is a staple of ecclesiological argument: of
what (ultimately) is necessary for a 'true church'. Episcopacy is often the
fault line for Anglicans, as in this extract. Well-being seems to be a
commonly used translation.

**Comment by dpl0js** [comment]
@peterwebster thank you, we made a special note of this point at yesterday's meeting.
