### ISSUE TITLE
Styling of blockquote in WP

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#202]
In these, where <blockquote is used, could we lose the marginal line on the left, and also the italics, and instead indent?  
Examples http://community.dur.ac.uk/henson.project/index.php/henson-and-his-journals/

**Comment by peterwebster** [comment]
FYI @DurHHHI @KPalmerHeathman

**Comment by KPalmerHeathman** [comment]
I mean, we only used the built in blockquote style because I couldn't work out how to indent, so if anyone can explain how to do it, I don't mind changing it.

**Comment by peterwebster** [comment]
@KPalmerHeathman if it's simple enough for @nomoregrapes (which I think it probably is), we'd be best to use the stylesheet-driven <blockquote for consistency. You could do it directly in each page, but it's fiddly.

**Comment by peterwebster** [comment]
@nomoregrapes the blockquote style seems to be as it was before? See the link at the top of the ticket.

**Comment by peterwebster** [comment]
Thanks @nomoregrapes : closing this now, and paging @KPalmerHeathman @DurHHHI for information about the change: site-wide style change for <blockquote
