### ISSUE TITLE
Page title font size in WP

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#203]
These are thought to be too large. Perhaps drop a point size or two, for further feedback.

**Comment by peterwebster** [comment]
Also: could you reduce the line spacing before and after lists, by about 20%.

**Comment by peterwebster** [comment]
And finally: reduce the vertical padding in table cells by about 10%.  The examples that gave rise to the suggestions were in:

http://community.dur.ac.uk/henson.project/index.php/abbreviations/

**Comment by peterwebster** [comment]
- [x] Cell padding
- [x] Line spacing
- [x] Title font size

**Comment by peterwebster** [comment]
Looks to me like these are all done @nomoregrapes ? Closing ticket, and paging @DurHHHI @KPalmerHeathman for info.

**Comment by nomoregrapes** [comment]
Yep, just finished them now.
