### ISSUE TITLE
Editorial conventions: minor amendments

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#206]
"Under ‘Inconsistencies and idiosyncracies’, remove line gap below the word “Henson’

Not sure if ‘Standardisation of text introduced in the edition’ is clear.  Perhaps ‘Editorial changes to the appearance of the text’, or similar phrase?  

Then perhaps revise the sentence, perhaps like this: 
‘As Henson’s practice on some textual matters varies, editorial standardisation has been undertaken as follows:’

**Comment by KPalmerHeathman** [comment]
I've made the second 2 changes but cannot seem to get rid of that line gap without also getting rid of the first bullet point. Also, doesn't it make it inconsistent with the other subheadings?

**Comment by peterwebster** [comment]
See #203 for the the outstanding point. Otherwise, closing this down.
