### ISSUE TITLE
Add New Journal fails

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#208]
@nomoregrapes in issue #197 Katie noticed that we have a missing file in volume 14, due to a mistake in the control sheet.
Seeing an opportunity to test the Add New Journal feature, I just tried to create a new journal and paste in the XML, and it failed. On test, in the logs in the last five minutes. Could you check it out today?

**Comment by nomoregrapes** [comment]
I removed the ability to set a few fields (issues, visibility, save to github) when you first create the journal. They would have required more work, and made the code less maintainable. You can edit the journal as soon as you've created it.

As a bonus, the content is default filled with the standard XML. If you click in that box you can do Control+A (select all) and delete it before pasting in all the XML you might have.

**Comment by peterwebster** [comment]
This one we discussed this morning, a bug in relation to the saving of the date.

**Comment by nomoregrapes** [comment]
This is now fixed.
I've tested it in creating a journal and editing a journal. You could try it on TEST by editing those two (00-11-12 and 00-11-13) to put in the dates.

**Comment by peterwebster** [comment]
The date isn't showing in the edit view for either https://henson-test.durham.ac.uk/journals/00-11-13/edit and the pages won't load. @nomoregrapes

**Comment by nomoregrapes** [comment]
I looked a second after your comment and it seems the server was restarting due to my push (bit delayed compared to when it normally does).

The dates aren't there (yet), because it saved them as blank during the bug.
I've added one date in, it works now.
