### ISSUE TITLE
Total figures in Organisations page not updating

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#209]
https://henson.durham.ac.uk/organisations is showing zero while the others seem to be working.

Same on test.

**Comment by nomoregrapes** [comment]
It's not wrong.

There are 69 orgs (over 0), it rounds down to 100s.
I think it was expected there would be more orgs, but shall I change this to 10s. I.e. "over 60"?

**Comment by peterwebster** [comment]
Apologies @nomoregrapes I remember we've been round the houses on this one before.
As it isn't clear when there will be many more organisations or places, on those two pages remove the number and just have the text:
"Search below for organisations mentioned in the Journals" 
"Search below for places mentioned in the Journals

Perhaps comment out the code for now, as we may in time restore this as and when the numbers look more convincing.

In Journals and People, I think I prefer the rounding to 100. Journals has this already, but People needs changing.

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes . Closing this one down now.
