### ISSUE TITLE
Long list - first section strikethrough

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#21]
![vol15-hhh](https://user-images.githubusercontent.com/32575577/31669755-d98c98ee-b34d-11e7-8bf1-26c9f1733431.jpg)

@KPalmerHeathman @peterwebster @williamsonphilip 

I have just come across this beauty (see attached photo). With Henson striking out a substantial part of the top page in his own dark pen, would you still include the section or employ silent editing and copy only the list below?

**Comment by dpl0js** [comment]
@DurHHHI Definitely engage in silent editing at the top of the page!

**Comment by DurHHHI** [comment]
@dpl0js Fabulous! Thanks.
