### ISSUE TITLE
Revise Publication Type categories tab in Search

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#210]
Another little puzzle for you @DurHHHI . 

As we've been discussing in #162 there are now letter-like things under two categories of publication. This doesn't matter all that much, save for at this point, where search resuls are filtered by Book, Periodical, or Other (which includes Poems and *also* Other:Letter.)

Two choices: the manual labour of recategorising existing ones so they fit in the correct category, or just hide this filter (which would be the fastest thing to do). How many are we dealing with?   https://henson-test.durham.ac.uk/?f%5Bhas_model_ssim%5D%5B%5D=Reference&q=church&search_field=all_fields

**Comment by peterwebster** [comment]
I'd welcome your thoughts on this one @DurHHHI

**Comment by DurHHHI** [comment]
@peterwebster ! Sorry, I completely missed this. Hide the filter is my two cents.

**Comment by peterwebster** [comment]
Agreed @DurHHHI 

@nomoregrapes could we remove (comment out) the Publication Type filter in search results, as we've discovered a wrinkle in the data which results in misleading results.  It could potentially be reenabled in the future if we decided to reclassify some References to iron out the issue.

**Comment by nomoregrapes** [comment]
so...
On search, remove the left-hand "Publication Type" filter? Keep the other filters there when relevant (e.g. Type, Volume, etc).

**Comment by peterwebster** [comment]
Since we're proceeding in #162 with renaming Other:Letter to Periodical:Journal:Letter and thus removing the issue (since all letters are now badged as in one or other type of periodical and are thus filtered as such), I can close this one down. @DurHHHI FYI.
