### ISSUE TITLE
Default search in Places doesn't match Persons/Organisations

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#211]
In the other two, the search option selected defaults to match the page. In Places it is still set to 'Journals and annotations'
https://henson-test.durham.ac.uk/places  

The behaviour in search will need to match the others, as per #186

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Indeed it is. Many thanks @nomoregrapes
