### ISSUE TITLE
WP Search box on mobile

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#212]
Need to adjust mobile style.

Only issue is that the search box doesn't fit (and thus causes the vertical blue bar down the right).

**Comment by nomoregrapes** [comment]
This is now done.

**Comment by peterwebster** [comment]
On my phone, the options in the dropdown are often too long to fit in the space once selected, and I'm reluctant to reduce the size of the text box.
We could do the same here as we did on the repo: remove the dropdown and have just the box, defaulting to Journals and Annotations.

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Magic, thanks @nomoregrapes . Closing this one down.
