### ISSUE TITLE
Formatting issues in display of references

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#213]
Transferring various things from #162 for clarity. @DurHHHI

**Comment by peterwebster** [comment]
**Page ranges and p. or pp.**

@nomoregrapes asked:  "Should pageRange be preceded with "p" (and "pp" if the range includes a hash)? Or is it fine as it is?"
@DurHHHI replied: " no pp. or p. to be included, just the page number(s). So example ref14 is fine as stands."

Is this the case for all publication types? Or, is what we're doing already correct across all types. 

Hilary confirms: "@peterwebster - there should be no pp. or p. for any of the publication types - I don't believe I saw any when searching across types, but just in case, no. pp. or p. ;)"

So, this is OK.

**Comment by DurHHHI** [comment]
@peterwebster - there should be no pp. or p. for any of the publication types - I don't believe I saw any when searching across types, but just in case, no. pp. or p. ;)

**Comment by peterwebster** [comment]
**Poems**

@DurHHHI : "Poems are missing publication place and publication year."

So https://henson.durham.ac.uk/references/ref61 should read:
_Hymns selected from Faber_ (Place, Year)

**Comment by peterwebster** [comment]
**Letters**

@DurHHHI :  "With the Other:Letter option –  ( https://henson-test.durham.ac.uk/references/ref108 ), it should reflect as H. H. Henson, letter, 'The church and the law', _Westminster Gazette_, 7 Sep 1907, 1. with letter, inserted between author and article title. 
The format, if possible, also needs to account for capital L Letter if there is no author attributed to the letter. Ex. Letter, 'The church and the law', _Westminster Gazette_, 7 Sep 1907, 1. 

The type Periodical:journal:letter  should look exactly the same, although it has not been used. It will be at some point.

**Comment by peterwebster** [comment]
**Edited collections: spacing**

In edited collections - there appears to be a space between ‘ed.’ and the comma (ex. ‘ed. , Church problems’).

**Comment by peterwebster** [comment]
**Across all type:  spacing between subtitle and title**

Where there is a colon separating title from subtitle, there appears to be an additional space between front title and the colon (ex. church problems : a view of modern Anglicanism). This should be removed.

**Comment by peterwebster** [comment]
**Date format**

June and July should be printed out in full:  https://henson.durham.ac.uk/references/ref40

cc @DurHHHI

**Comment by nomoregrapes** [comment]
A lot of these are issues I haven't been able to test before, the URLs of examples really helps.

Still in progress & notes...
**Letters** not showing "letter", this works on dev but not on test. I need to check why.
**Edited collections** spacing, was a trailing space in the data. I've visually fixed it, I've also updated the references ingest so most fields will get trailing spaces removed when ingesting.

**Comment by nomoregrapes** [comment]
Letters was only showing for Other:Letter:letter, and we seem to be going with Other:Letter.

All the formatting tweaks in this issue should now be done, and on test.

**Comment by peterwebster** [comment]
**Testing**

- [x] Letters
- [x] Date format
- [x] Titles and subtitles
- [x] Edited collections spacing
- [x] Poems

**Comment by peterwebster** [comment]
These all look good to me on test, so closing this one down.
