### ISSUE TITLE
Stylesheet treatment of <hi> elements without attributes

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#214]
Volume 18 has (for various reasons) a number of <hi elements that perform no functions, but are hard to remove by script without upsetting the well-formedness.

@nomoregrapes must these come out, or will the stylesheet simply disregard them?

In the case below, the <hi in the first paragraph is superfluous, but that in the second paragraph has a real impact.

`<p>
<hi><persName id="112">Ella</persName> went off to Scotland by the morning express.</hi>
         </p><p>
<hi rend="b u">The "Times" announces that the Government have granted a Select Committee of the House to inquire into the measure of responsibility attaching to the Directors of the Peruvian Amazon C</hi>
<hi rend="b sup u">y</hi>
<hi rend="b u"> for the Putumayo atrocities</hi>`

**Comment by nomoregrapes** [comment]
So long as every tag is respectively closed, this is still well-formed and won't be an issue.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI here's the answer to the issue we had with volume 18. <hi tags without any attributes:

`<hi>words</hi>`
are just ignored. See it in action  https://henson-test.durham.ac.uk/journals/04-11-20

Does that resolve the issue?

**Comment by DurHHHI** [comment]
@peterwebster Yes perfect - no manual removals necessary unless caught between tags. Woot!
