### ISSUE TITLE
Unknown tag: term

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#215]
In the XML for [01-01-19](http://henson.durham.ac.uk/journals/01-01-19) there are some `<term xml:id="3">` tags.

Term isn't one of our annotation types, so are those supposed to be something else, or is it an annotation type that was abandoned?
Not causing a problem in my view, as the system just ignores them.

There is however a mistake in that file that stops it being well-formed XML. You might spot it, or you can wait for our new XML-checking tool which will point it out.

**Comment by DurHHHI** [comment]
@nomoregrapes definitely not something katie and i were implementing as per old rules

**Comment by peterwebster** [comment]
Yes: term was in the first version of the scheme but was subsequently dropped. If they are doing no harm, they I don't intend to remove them.  @nomoregrapes 

XML issue deal with.
