### ISSUE TITLE
Circled symbols

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#22]
Do we wish to do anything to mark the fact that this symbol has been circled for extra emphasis?

![image](https://user-images.githubusercontent.com/32575539/31674119-e7e39f7c-b358-11e7-8332-fe2bd2684ef4.png)

**Comment by dpl0js** [comment]
@DurHHHI I would be inclined to just record that there is a symbol here, in the normal way.

**Comment by peterwebster** [comment]
That seems sensible to me @KPalmerHeathman @DurHHHI : I shall close the ticket unless @williamsonphilip disagrees.

**Comment by peterwebster** [comment]
Closing this now.
