### ISSUE TITLE
Rewording in annotation pop-ups

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#221]
Tiny change:  where it currently reads 'Other journal mentions', change to 'Other journal references'

It also needs to be changed here:  https://henson-test.durham.ac.uk/people/person117 (and in the same place for each annotation type).

**Comment by nomoregrapes** [comment]
This is done.
I will change issue assignment from me to Peter when I've pushed it to test-server.

**Comment by peterwebster** [comment]
@nomoregrapes I see this on test, many thanks. Closing ticket now.

**Comment by peterwebster** [comment]
I spoke too soon: we should change it here too  https://henson-test.durham.ac.uk/?utf8=%E2%9C%93&search_field=all_fields&q=law   @nomoregrapes

**Comment by nomoregrapes** [comment]
Done and on testing

**Comment by peterwebster** [comment]
Magic @nomoregrapes : closing now.
