### ISSUE TITLE
Rearrangement of date picker

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#223]
As discussed:

1. All drop downs to default to [select year / select month / select day] 
(I realise this will pull the sizing around)

2.  Select a particular day [to match the narrative text above]
[ select year / select month / select day ]

3. Select a range of dates
 [box A to box B as it is at the moment.]
[

**Comment by nomoregrapes** [comment]
This is now done and [on testing](https://henson-test.durham.ac.uk/journals)

* I've been able to simplify the code so it's more readable/maintainable
* The date search should correctly find dates within multi-day-journals where it wasn't always doing that before.
* If any option is unset, it will use 1900/Jan/01 as needed.
* The top of the results should now report the date searched for, with an X so you can remove the constraint.

**Comment by peterwebster** [comment]
@nomoregrapes this looks good to me, and Katie has had a look to. Go ahead and do the same on WP.

**Comment by peterwebster** [comment]
@nomoregrapes although, perhaps align the search box on the left with the headings and the two picker boxes below it; in FF it is slightly displaced left.

**Comment by nomoregrapes** [comment]
Fixed that alignment issue.
Just need to copy this to WP now.

**Comment by nomoregrapes** [comment]
Done on WP. Back to you.

**Comment by peterwebster** [comment]
Tested and working fine on WP, and looks good on mobile. Closing this down now.
