### ISSUE TITLE
Attempts to access management pages to redirect to homepage

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#224]
We should review all the pages such as the dashboard, annotation/new, annotation/1234/edit etc to check that they all redirect to the homepage.

(At the moment, this https://henson-test.durham.ac.uk/journals/new is accessible when not logged in, although one can't save (I think).

Better to redirect here (although less convenient for the team) because we don't really want lots of attempted logins via Github.

**Comment by peterwebster** [comment]
All the new annotation views redirect correctly.

**Comment by peterwebster** [comment]
As are all the annotation/edit views.  Looks like there's just an issue with the one, journals/new

**Comment by nomoregrapes** [comment]
Journals the admin check was missing from the new page (and missing if you clicked save). Now added.
Not yet pushed to test-server, I'll change this issue from me to Peter when I do that.

As a double-check, I've looked at the code for all other pages and nothing is missing.

**Comment by peterwebster** [comment]
Looks as though this is pushed to test now @nomoregrapes : all great. Closing ticket now.
