### ISSUE TITLE
Allow the editing of the type field for references

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#227]
At present, it is not possible to change the type for a reference in the GUI, so misclassified ones in the TSV can't be undone without depublishing it, creating a new reference with new ID, and manually amending the XML.

**Comment by peterwebster** [comment]
For now, in order to replace one annotation with another with the correct type, create single line TSV and ingest as Update.

**Comment by nomoregrapes** [comment]
This is done.
It will be on the test_server soon, or I've forgotten a step in doing the deployment.

FYI, it's my understanding that these are all the possible values for "type".
```
	Periodical:journal:article
	Periodical:news:article
	Periodical:news
	Book:monograph
	Book:sermons
	Book:edited collection
	Other
	Other:Book chapter
	Other:Letter
	Other:Poem
```
Some, but not all, alter how the reference is displayed.

**Comment by peterwebster** [comment]
@DurHHHI could you check over this list for completeness? I think we're missing:

periodical:news:letter
periodical:journal:letter

**Comment by peterwebster** [comment]
@nomoregrapes it doesn't seem to be deployed to test just yet.

**Comment by DurHHHI** [comment]
hi there @peterwebster and @nomoregrapes - yep agreed, periodical:news:letter and periodical:journal letter are missing

These are the type fields I have listed from the google sheets:

Book:monograph
Book:sermons
Book:edited collection
 
Book chapter
 
Poem
 
Periodical:journal:article
Periodical:journal:letter
Periodical:news:article
Periodical:news:letter

**Comment by nomoregrapes** [comment]
Technical note: the colons are used to split this into 3 fields: Type, TypeSub, and TypeMinor so the code can deal with it in different ways.
If the main Type isn't "Book" or "Periodical" then the ingest classes it under "Other". I hopefully had a reason for doing that, but this explains the slight difference in my list.

**The type can now be edited on test_server, including TypeMinor=letter.**
If you select a combination that isn't in our list, then it shows you a warning (but won't stop you clicking update/save).
![ref_editing_type](https://user-images.githubusercontent.com/1181194/56731015-55bd6c00-6751-11e9-812a-6a5bb1e6de28.png)

**Comment by peterwebster** [comment]
Can @DurHHHI test and try to break this?

In the meantime, I note that:

- book:edited collection
- periodical:news:letter
- periodical:news:article

all give the error message, when they are real types.

**Comment by peterwebster** [comment]
To add to the documentation: on creating a new reference, it does not define the type, so it is necessary to hit Edit again and set it.

**Comment by peterwebster** [comment]
@DurHHHI I set up this example for testing purposes; I suggest you try changing it to different types and see if you spot anything.
Note that it tends to show whatever data there is, so if (say) you want it to be a periodical:news:letter but there's something in the VolumeDetails field, that will be shown. It includes by default rather than excluding.

**Comment by peterwebster** [comment]
I've now tested this quite extensively @nomoregrapes and you can consider it done with now.

For documentation: the error message about not seeing a defined type doesn't obstruct the actual process of editing.

**Comment by peterwebster** [comment]
Changes made to documentation, closing now.
