### ISSUE TITLE
Henson - pencil (or light pen) with dark pen

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#23]
![vol15-hhh-pg286](https://user-images.githubusercontent.com/32575577/31773232-0294de08-b4da-11e7-98c7-e0b328f9cd47.JPG)

I've just come across this section in Vol 15 where it looks like Henson has gone over specific words in dark pen. Is there a particular way you might like to note this (i.e. bold underline, italics, or new unique indicator)?

@KPalmerHeathman @peterwebster

**Comment by peterwebster** [comment]
It looks as though this is just a case of clarifying what he has written for legibility (rather than emphasising it as particularly important). I'm not sure there's a case for picking it out.

**Comment by dpl0js** [comment]
agreed.

**Comment by DurHHHI** [comment]
Excellent! Yes, assumed as much, but thought best to check. Closing the thread.
