### ISSUE TITLE
slanted and straight quotation marks

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#230]
https://henson.durham.ac.uk/journals/05-01-10-01-12

Hey @peterwebster - apologies, just saw this today and wonder if the quotation presentation is a fluke, or if there needs to be further intervention. All LHS quotation marks presenting slanted, with RHS presenting straight.

FYI @KPalmerHeathman

**Comment by peterwebster** [comment]
Apologies @DurHHHI @KPalmerHeathman : not sure what happened here. In the XML they showed as straight; I went in and just deleted and retyped as straight, and they are now OK. Keep an eye out for these, although I think that for 14 and 15 we're now too far gone to be intervening offline and reingesting whole volumes, so it's a manual fix. Annoying, I realise.
