### ISSUE TITLE
Rogue Date

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#232]
I think the date range data here is incorrect   https://henson.durham.ac.uk/journals/02-12-04-12-07

**Comment by DurHHHI** [comment]
?? Not sure what you mean @peterwebster - apologies - just checked and 4 December appears to be a Thursday in 1902. 

@KPalmerHeathman

**Comment by peterwebster** [comment]
Ah, it's wrong on test. I think perhaps @nomoregrapes deliberately broke it to test the date sorting.... :-)
