### ISSUE TITLE
Date display in periodical:journal:letter

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#233]
Thus far, the reference type of periodical:journal:letter has not been used. However, we expect it will be.

At the moment, it displays thus:  https://henson-test.durham.ac.uk/references/ref123456

The issue is that the GUI does not show the Date(year) or Date(month) fields, only Date(full). By virtue of being published in a journal, these will not have full dates. So, they need to show Date(month) and Date(year), not Date(full)

NB. This behaviour is what distinguishes the type from periodical:news:letter  (example in comment below)

**Comment by peterwebster** [comment]
Also @DurHHHI : anything that we subsequently ingest described as periodical:news:letter will display like this one, so you can now use this in place of other:letter
https://henson-test.durham.ac.uk/references/ref987654

This means that the issue in #162 is a retrospective one.

**Comment by peterwebster** [comment]
@DurHHHI I previously wrote:

"So, if these start to present themselves before Gregory can get to this, @DurHHHI will either need to:

(i) treat them as Other:Letter (which we are now marking as periodical:news:letter, or;
(ii) hide them"

Assuming that Gregory can fix the issue this week, is there any retrospective work to do by hand in existing entries?

**Comment by nomoregrapes** [comment]
I have updated the code just a little so when displaying a reference...
* If it is a Book/book chapter/poem, and dateYear exists, then "dateMonth, dateYear" is displayed.
* If it is a Periodical, and dateYear exists then displays "(dateMonth, dateYear)".
* Regardless of type, if the above has not been done, display "dateMonth, dateYear" if possible or fall-back to dateFull(e.g. 25 Apr/June 2019).
* When dateMonth is displayed, then it's Apr/June/etc, and if it doesn't exist the comma is dropped (so only dateYear will display).

This ensures that if dateYear exists then dateFull will be ignored for the display.
It can be good to still save a dateFull, because that can get used in searching/ordering.

I've completed this, but it's not yet on the test_server (due to current issues).

**Comment by nomoregrapes** [comment]
The updates are now on test_server, so please go ahead and edit/test as needed.
If dateYear is filled in then dateFull should never be displayed.

**Comment by peterwebster** [comment]
Could @DurHHHI review various types of publications to make sure that this hasn't upset anything, and also confirm the following?

Two things from me:
(i) I think that all the months that are abbreviated need a following period: Jan., Feb. etc.
(ii) periodical:news:letter and periodical:journal:letter should match other:letter in having the string 'letter' after the author, as at https://henson-test.durham.ac.uk/references/ref200

**Comment by peterwebster** [comment]
@DurHHHI should a full date be given in brackets? 
Compare https://henson-test.durham.ac.uk/references/ref200 (other:letter) 
and
https://henson-test.durham.ac.uk/references/ref782610  (periodical:news:letter)

**Comment by DurHHHI** [comment]
> @DurHHHI should a full date be given in brackets?
> Compare https://henson-test.durham.ac.uk/references/ref200 (other:letter)
> and
> https://henson-test.durham.ac.uk/references/ref782610 (periodical:news:letter)

The second link isn't working for me, @peterwebster so can't see the comparison.

**Comment by DurHHHI** [comment]
> Two things from me:
> (i) I think that all the months that are abbreviated need a following period: Jan., Feb. etc.
> (ii) periodical:news:letter and periodical:journal:letter should match other:letter in having the string 'letter' after the author, as at https://henson-test.durham.ac.uk/references/ref200

@peterwebster re: 'two things':
i) Yes, all abbreviated months (all months save May, June, July) require the period.
ii) Yes, the 'letter' string should be reflected in both periodical:news:letter and periodical:journal:letter as it is with other:letter

**Comment by DurHHHI** [comment]
> > @DurHHHI should a full date be given in brackets?
> > Compare https://henson-test.durham.ac.uk/references/ref200 (other:letter)
> > and
> > https://henson-test.durham.ac.uk/references/ref782610 (periodical:news:letter)
> 
> The second link isn't working for me, @peterwebster so can't see the comparison.

Ok, @peterwebster No, looking at Julia and Philip's final agreed template, date for periodical:news:letter and periodical:news:article is correct without brackets (though a period still needs to follow the abbreviated month)

**BUT** date should be in brackets (and currently is not) for periodical:journal:letter and periodical:journal:article

https://henson-test.durham.ac.uk/references/ref17
should be
H. H. Henson, 'The judgment of Christ', Christian World Pulpit, 60 (11 Dec. 1901), 369-74.

**Comment by peterwebster** [comment]
So, to confirm in our call shortly @nomoregrapes 

- [x] (i) DateFull should be without the brackets in periodical:news:letter and periodical:news:article
- [x] (ii) But date information (usually Month and Year) *should* be in brackets for periodical:journal:letter and periodical:journal:article
- [x] (iii) all abbreviated months (all months save May, June, July) require the period.


The issue with inserting the string 'letter' seems to be resolved.

**Comment by nomoregrapes** [comment]
With the addition of the dot, I'm going to assume the comma should be dropped.

Not `Jan., 1885` but should be `Jan. 1885` or `June 1885`, and `1 Jan. 1885` or `1 June 1885` etc.

**Comment by peterwebster** [comment]
Yes @nomoregrapes  drop the comma

**Comment by nomoregrapes** [comment]
It has been made so, and is on test_server.

**Comment by peterwebster** [comment]
May is being given a full stop but doesn't need one as it's not abbreviated.  https://henson-test.durham.ac.uk/references/ref782610
Other than that, we're good to go.

**Comment by peterwebster** [comment]
@nomoregrapes I see that this has literally just been pushed to test. If you're happy (I am), then close the ticket.

**Comment by nomoregrapes** [comment]
Yes.
