### ISSUE TITLE
Remove 'sermons and speeches' from search dropdown

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#235]
After having abandoned sermons and speeches (<event ) as an annotation type, #166 did most of the work. However, the search filter still shows Sermons and Speeches as an option, and should not.

Perhaps @nomoregrapes just comment out, so it could be reenabled at some future stage.

**Comment by peterwebster** [comment]
This is a loose end from #166 @DurHHHI

**Comment by nomoregrapes** [comment]
Removed, reasdy for you to confirm and close this.

**Comment by peterwebster** [comment]
Great @nomoregrapes . Closing now.
