### ISSUE TITLE
Reference annotation - spotted with new ingest

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#239]
I've been spending hours updating the GUI with the located sermon references from vol 14/15. I've noticed that if a month is provided in the reference but no day date, the ref automagically sets to the first of the month. If I edit the ref to not display the date then I lose month and year function altogether.

Ex. https://henson.durham.ac.uk/references/ref508
It should just reflect (Jan. 1905) but if editing to take out the day date '1' (which shouldn't be there in the first place), then I lose month AND year. If I attempt to just add YEAR, it doesn't display.

There are quite a few references with no date beyond month and year, so wondering if there is a quick fix.

**Comment by peterwebster** [comment]
OK @DurHHHI : I've just edited this reference  https://henson-test.durham.ac.uk/references/ref508/edit so as to remove the whole contents of the DateFull field, and replace with just Year and Month. This displays the year correctly.

So: the fix (for @nomoregrapes ) is: when DateMonth is not null, display it along with DateYear. This should only ever apply for periodicals; it shouldn't occur for books or book chapters.

**Comment by peterwebster** [comment]
But @DurHHHI there's more to this than just that. It looks as if, in ref.tsv, when there's a date in the form June 1905 or Dec. 1917, it has been placed in the DateFull field. However, the ingest expects to find whole dates in there, not partial ones, and so it defaults to the first of the month.

In my mind, dates with just a month and no day were to be dealt with using the DateMonth and DateYear fields, but I don't know whether I communicated that well enough.

For future new ones, this would be the way to deal with them (in conjunction with Gregory's fix). We need to think about what to do in the short term with existing ones. (Let's deal with that in a call.)

**Comment by peterwebster** [comment]
@DurHHHI putting this fix on Gregory's list for this week.

**Comment by peterwebster** [comment]
NB @nomoregrapes June, July to be written out in full, everything else is [xyz.], so Jan., Mar.
This is as elsewhere.

**Comment by nomoregrapes** [comment]
I'm taking #233 to be the display part of this issue, but this issue to be about how the data is stored.

The ingest doesn't do anything clever, and respects what columns you've used.
* date(full) should always be blank or a full and valid date.
* At times, the code tries to ensure dateFull using standard functions. This can cause dateFull to not display anything if it's "2/29/2019" or "29/2/2019". The standard functions know that "29/2/2020"(leap year) is valid.
* "28 Feb 2019" will be considered valid.
* "Feb 2019" will be considered valid, but will take it to mean "1 Feb 2019".
* "Feb 20" will be taken to mean "20 Feb 2019"(assumes current year was not specified).

You could add a somewhat-arbitrary dateFull as "1 Feb 2019" to allow searching/sorting, but should also set dateYear and dateMonth if you don't want the "1" to be displayed.

No work to do here.

**Comment by peterwebster** [comment]
@DurHHHI I think that this is resolved now by means of a fix in another ticket. Do take a look at Gregory's comments about what the ingest does with the different formats in the TSV in DateFull, and then (if you're happy in general) close this ticket down.

**Comment by peterwebster** [comment]
Closing this down now.
