### ISSUE TITLE
V14 daily XML to markup (Stage 3)

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#24]
In Dropbox (for now) are 23 XML files plus a copy of the stylesheet (styles.xml ) that should allow them to open in Firefox.

I suggest @DurHHHI and @KPalmerHeathman work through these and let me know any issues that arise. I may be able to iron some of these issues out for future volumes at the Stage 2 conversion, so working with these few will be a useful way of testing and amending my process.

For each issue, create a new ticket and paste in some or all of the XML.

NB. These will not parse in Firefox until you take out the <!011000 tags, but I think that removal will be a natural part of your work on each.
They also need renaming, as you'll see, but the numbers they have now are in the correct order (if not the precise date).

**Comment by KPalmerHeathman** [comment]
Thank you very much, Peter!

**Comment by DurHHHI** [comment]
You're so fast! Appreciated. 👍

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman one issue that also presented itself is when the <!011000 marker has any formatting applied to it, as was the case with the underlining for 0310100. This causes the script that effects the split not to recognise it, so we had two days in one file.

If you can avoid that in the Word stage that will help, but keep an eye out in future for any which slip through, which I won't catch automatically.

**Comment by peterwebster** [comment]
It's amazing what computers can do these days  ;-) @DurHHHI @KPalmerHeathman

**Comment by peterwebster** [comment]
Note also my nifty use of a Volume 14 label, so we can distinguish between issues in different volumes
