### ISSUE TITLE
Remove dropdowns from homepage

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#240]
After some deliberation, the decision was taken to remove the 'Particular date' and 'Range of dates' dropdowns from http://community.dur.ac.uk/henson.project/

As usual, perhaps best to comment out to allow reintroduction later if the feeling of the project changes again.

**Comment by nomoregrapes** [comment]
I have disabled this in the code.

I also deleted the text
`For access to the edition, either <strong>select</strong> a particular day or range of dates below, or use the <strong>search</strong> box above.`
which was in the "Welcome" (front/home page) on the Wordpress admin.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes . Closing this one down now (and paging @DurHHHI @KPalmerHeathman )
