### ISSUE TITLE
Data not available for edit in Reference edit

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#242]
There is data that is imported from TSV in the PeriodicalDetails field that gives a volume reference:  eg.  A periodical, 112

This is being stored and displayed correctly, but is not shown in the Edit view and so can't be corrected.

https://henson-test.durham.ac.uk/references/ref119/edit 

Christian World Pulpit, 59

**Comment by nomoregrapes** [comment]
This is implemented and on test_server.

**Comment by peterwebster** [comment]
Looking good, ready for deployment to prod. Closing ticket now.
