### ISSUE TITLE
Rescan of XML (dashboard)

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#245]
Normal use of the GUI has shown that if it is necessary to edit the XML in order to add, remove or change the ID of the XML that calls an annotation, the change is reflected is immediately reflected in the journal view, but not in the listings given in the relevant annotation pages.  The Rescan XML function on the dashboard isn't managing this well.

**Comment by peterwebster** [comment]
Example (on test server):
17 February 1901 ( https://henson-test.durham.ac.uk/journals/01-02-17-02-18 ): journal XML edited in GUI such that 'Mrs Hunt' (third line below the table) refers to annotation for A. L. Smith.

So: two things then need to happen.

- The link to 17 Feb 1901 to drop out of Mrs Hunt's annotation page:  https://henson-test.durham.ac.uk/people/person616
- A new link to 17 Feb to appear on Smith's page  https://henson-test.durham.ac.uk/people/person1170

**Comment by peterwebster** [comment]
However, a Rescan All XML only manages one of these tasks.

On the first process: it sometimes correctly picks up the altered annotation and appends it to the record for Smith, as in the case above.

*However* this also seems to be erratic: on production, a Rescan has not dealt with the annotation for Smith in this https://henson.durham.ac.uk/journals/10-05-22-06-02 , which should be listed at https://henson.durham.ac.uk/people/person1170 (this was spotted by @DurHHHI )

On the second process: since the scan process doesn't know what this annotation it is now seeing *used* to refer to, it cannot delete the entry in Hunt's record (I presume).

**Comment by peterwebster** [comment]
So, I think we either need to alter the Rescan process such that it removes items in the annotations record (for all types) that it has seen before but hasn't seen in the latest Rescan.
This, though, is I think quite complex.
Second option: allow a manual edit of annotations to remove defunct journal references.

**Comment by peterwebster** [comment]
Need to test another couple of instances to be sure what's happening, once prod restarted.

**Comment by peterwebster** [comment]
Hilary's example: (the two Smiths), on production:
06-11-08-11-11: XML redirected to 650 (the son, A.L.F Smith), now correct at 650, but not at 1170.
10-05-22-06-02 XML redirected to 1170 (the father, A. L Smith), but not reflected at either 1170 or 2474.

**Comment by peterwebster** [comment]
This issue ongoing, but can't test any further until #246 resolved.

**Comment by DurHHHI** [comment]
@peterwebster, for future reference, this example also not working:

11-07-09-07-15, "we went to Eton to spend the week–end with the Provost": Edmond Warre, updated correctly to 203, but still searchable in persons as separate entry 3415, with collected persons 'entries mentioned' list in 203 not reflecting the change. 

Flagged by JS.

**Comment by DurHHHI** [comment]
@peterwebster, for future reference, this example also not working:

Dennistoun extended family (ex. those associated with James George Dennistoun https://henson.durham.ac.uk/people/person556) not reflecting correctly, despite ID changes

**Comment by DurHHHI** [comment]
@peterwebster, for future reference, this example also not working:

Paget boys --> Tags with ID 625 (Francis) that should be moved to 2409 (Henry Luke): 11 October 1909, 2 July 1911, and 19 Nov. 1911.

**Comment by DurHHHI** [comment]
@peterwebster, for future reference, this example also not working:

Patrick Carnegie Simpson - retaining Pers 2015 and deleting 2402

**Comment by DurHHHI** [comment]
@peterwebster, another one - spotted by JS this morning:

William Walrond Jackson - https://henson.durham.ac.uk/people/person2468 and https://henson.durham.ac.uk/people/person93 - all entries reflect ID 93 now, but same old with the persons pages (and bulleted entry list)

**Comment by peterwebster** [comment]
The sum of this is now at #256, so closing this ticket as it is rather long and unwieldy.
