### ISSUE TITLE
Setting annotations to Publish All from Manage dashboard fails

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#252]
When new annotations are ingested, they are set to be viewable only by administrators. The dashboard  ( /manage ) has a set of Publish All options, to set them all to be publicly available once staff are satisfied with the ingest. These are failing, (but only in the case of Persons)

[From Resque, on worker 1, on 5th Feb]
Class: Items_Set_Public 
Arguments  --- people
Exception
    Resque::DirtyExit
Error
    Child process received unhandled signal

**Comment by peterwebster** [comment]
For reasons that are unclear to me, the unpublished ones are all from the new persons associated with the latest ingest. These were ingested safely (I think) before the issue with Helios arose in December/January.

**Comment by peterwebster** [comment]
@DurHHHI when we ingested 21 and 22, did this work correctly when you set all the annotations to publish? Or did you have to go through and Publish each one individually, as I think had been the case with 19 and 20? If it was OK, we can close this ticket, I think.

**Comment by DurHHHI** [comment]
Peter, yes, thank goodness, I did not have to go through the manual individual ‘publish’ in V21/22.

**Comment by peterwebster** [comment]
Closing issue, which was apparently transitory.
