### ISSUE TITLE
Henson doodles

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#26]
![vol15-hhh-pg311](https://user-images.githubusercontent.com/32575577/31830472-3361a37a-b5b8-11e7-9ce8-f0fe652de33c.JPG)

Just came across this beauty! How do folks suggest marking this addition, if at all. Happy Henson doodles.

**Comment by williamsonphilip** [comment]
Ah, interesting and tricky!   My first thought is to ask whether it would be possible somehow to embed an image in the text, or to have a separate file of images to which the reader could be directed by some symbol in the text.  Presumably other doodles might appear later?

**Comment by dpl0js** [comment]
I agree:  it would be nice to have such images, perhaps including the entire page as the equivalent of 'plates' in books.  [.....]

Perhaps for now keep a separate file of such pages, as Philip suggests, and approach the Cathedral on a volume by volume basis.

**Comment by peterwebster** [comment]
I would want to counsel against trying to embed these in the text, as the result is rarely good when they are of all shapes and sizes. They could certainly be described in footnotes.
The analogy of the plate image is perhaps a good way to think of these, that we deliver to users in some sort of separate section, outside the run of daily entries. The note can refer verbally to the gallery, and the gallery to the location of the doodle in the page. If, however, it is a requirement that readers viewing a day are able to click to see the image, then some revision is needed to the XML schema, as we'll need a new element. This (a) needs to be done relatively soon, and certainly before the developer arrives, and (b) only makes sense if we are to include images of all such doodles. As @dpl0js points out, this is by no means a certainty.

**Comment by dpl0js** [comment]
Thanks Peter, let's just keep thing simple, i.e. a note that refers the reader to the gallery (nice term!) for the full visual display of the few instances of such plates there are likely to be.

**Comment by peterwebster** [comment]
After discussion on Skype, closing this.

**Comment by peterwebster** [comment]
I've reopened this as I'm in the process of specifying what Gregory should be doing. For the notice of @KPalmerHeathman @DurHHHI , I added the CrossRef field to the Notes file. As and when there are any examples of this, just enter _gallery_ here, and it can then link to the gallery (but not to any specific image).
Do close the ticket again once you've seen this and are happy/clear about it.

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI just check you're happy with this,, and close the ticket?

**Comment by DurHHHI** [comment]
We are happy - thanks @nomoregrapes and @peterwebster !
