### ISSUE TITLE
Issues on test server

### ISSUE THREAD

**Issue by alisonrclarke** [peterwebster/henson#260]
* 500 error on hitting save, e.g. at https://henson-test.durham.ac.uk/journals/00-11-04/edit (but edits are successfully saved)
 * Pushing to GitHub does not work (after checking 'Save changes to GitHub')
 * Data ingest of annotations gives 500 error
 * Data ingest of journals control TSV fails

The issue only seems to be on the test server, not production, so it may be due to firewall issues.

**Comment by peterwebster** [comment]
Closing this ticket, as (i) is dealt with, and we're now not going to ingest new data to test, or make authoritative changes that need pushing to Github (this was never the case.)
