### ISSUE TITLE
Update number of items on journals page

### ISSUE THREAD

**Issue by alisonrclarke** [peterwebster/henson#262]

**Comment by peterwebster** [comment]
Agreed: the number given at https://henson.durham.ac.uk/journals ("Over XXXX journal entries....") should already update after each new ingest, but does not. I hadn't noticed this before, and am not sure when this broke. @alisonrclarke

**Comment by peterwebster** [comment]
If difficult, we could just make this text, as we've now reached a point at which no or little new entries should be added.

**Comment by peterwebster** [comment]
@alisonrclarke this is perhaps one to look at to begin with, but if it look like it's going to take more than a few minutes, set it aside. I have one more volume to ingest, in the next couple of weeks, after which there should be no more (at least until some more funding might be found), and so the text can just be fixed and the code to update it commented out.

**Comment by peterwebster** [comment]
We have the same issue at https://henson.durham.ac.uk/people, which is likely to be the same at root. @alisonrclarke

**Comment by peterwebster** [comment]
@alisonrclarke so this is could in fact dependent on #259 (dashboard refresh fails), so if we solve that, this issue disappears.

**Comment by peterwebster** [comment]
@alisonrclarke both these visible numbers have updated on production, and match the totals of journals and people in the repo, so I shall close this one now, while alerting @dpl0js 
https://henson.durham.ac.uk/journals
https://henson.durham.ac.uk/people
