### ISSUE TITLE
If an reference is added to an entry through the GUI, it is not reflected in that person's list of entries

### ISSUE THREAD

**Issue by alisonrclarke** [peterwebster/henson#263]

**Comment by peterwebster** [comment]
@alisonrclarke @dpl0js this has never been the case - the repo does not, on saving edits to a journal entry, rescan the contents of a journal entry and append new entries to the person's list.  It was always anticipated that this wouldn't need to happen, or at least rarely. However, there is (as per #254 ) a means of triggering a rescan of a range of entries, from the Dashboard.

However, now that more editing is to be done in the GUI, there is a case for amending the code such that that rescan happens automatically for any journal entry being edited, on Save.

{Note that this is connected to #256, but the two issues need separate solutions.]

**Comment by peterwebster** [comment]
@alisonrclarke as discussed, the solution for this is that, when a user saves from the edit view (eg. https://henson.durham.ac.uk/journals/00-11-04/edit ), then a Rescan of just that file is triggered.
This checks through that file, and appends new connections to the persons/places that are marked up. (eg https://henson.durham.ac.uk/people/person12 )
Olli implemented a function to rescan a range of files to solve #254, which is triggered from the dashboard, so there may be reusable code there.
Also in the dashboard is the Rescan All XML function, which does what it says on the tin.

**Comment by peterwebster** [comment]
This seems to be failing @alisonrclarke 

(i) I added dummy markup (at the very end, the text "Liddon testing") to https://henson-test.durham.ac.uk/journals/17-03-16  at 0945 today. It throws an error, though the change has been made in the XML.  
(ii)  Similarly  in https://henson-test.durham.ac.uk/journals/17-03-11, change made at 0947

The reference to Liddon in (i) should show up at:  https://henson-test.durham.ac.uk/people/person395  
That to Hutchinson in (ii) should show here: https://henson-test.durham.ac.uk/people/person3950

**Comment by alisonrclarke** [comment]
Looking at the error message it seems like it might be an issue with the Solr server used by the test env. I'll investigate further.

**Comment by peterwebster** [comment]
@alisonrclarke thanks:  I would suggest not spending too much time on fixing that, unless it means that it will also fail on production.

**Comment by peterwebster** [comment]
@alisonrclarke I've been testing this, and (at the moment) it seems that some changes are being picked up, but others aren't.

See, for instance, the example above,  https://henson-test.durham.ac.uk/journals/17-03-16 
where new person Liddon is now showing on his person page, but not Hutchinson

See also:  https://henson-test.durham.ac.uk/journals/17-03-23
where amended entry QUICK is OK, but neither Liddon nor Pusey House (both at the bottom, newly added) don't.
https://henson-test.durham.ac.uk/organisations/org225 (Pusey House)

I'll test a few more next week, and see whether I can figure out whether it is to do with the ordering of the amendments, or position in the page, or what.

**Comment by peterwebster** [comment]
Testing, June 1st

(i) 13.04:  17-03-24, two new annotations added, SUCCESS
(ii) 13.09: the same file, 17-03-24, changing one annotation to another, FAILS
(iii) 13.12 a different file, 17-03-25, changing one to another, FAILS
(iv) 1318: a different file, 17-03-26,  NEW annotation FAILS

I can't really see a pattern here, @alisonrclarke : is there anything helpful in the logs?

**Comment by alisonrclarke** [comment]
I can't see a pattern either, nor anything useful in the logs. I've tried re-editing some of the entries mentioned above and most worked as expected, but other changes did not take effect until I edited again. I'm wondering if there is some caching going on of the XML content, so that when the references are checked it still sometimes uses the old version of the XML.

To attempt to avoid that issue I've tried putting the rescan job on the queues rather than doing it straight away; I'm not sure whether it's helped at all. I've also added some debug logging (for now). 

@peterwebster could you try a few more entries and let me know what happens?

**Comment by peterwebster** [comment]
@alisonrclarke thanks Alison: I tried another five this morning (between 0907 and 0932) and they all seem to work now. I've tested new annotations, amendments to old ones, combinations of the two. I can't now see any other ways to test it, so let's push this to production and I'll test it there.

**Comment by peterwebster** [comment]
@dpl0js this change is now live on the production service: could I ask you to test a few examples?  It seems to be working.

For example:
I amended this file for Bishop Mackarness:  https://henson.durham.ac.uk/journals/31-05-31 
which was (within a few seconds) reflected at https://henson.durham.ac.uk/people/person1163

Similarly, I amended this for Soederblom ( https://henson.durham.ac.uk/journals/31-05-25 ) which flowed through correctly to:  https://henson.durham.ac.uk/people/person2166

**Comment by dpl0js** [comment]
@peterwebster Great! thank you. I have added James Meston, to the GUI, and checked him in at https://henson.durham.ac.uk/journals/21-10-25

I then added him to https://henson.durham.ac.uk/journals/28-11-07, which works, although this has not been added to the bulleted list.  The same applies to Dawson Walker on the same page. It could be just a question of delay.

**Comment by dpl0js** [comment]
@peterwebster It was indeed a question of delay. I'll do a couple more.

**Comment by dpl0js** [comment]
@peterwebster Interesting on Frank Buchman. I had added him through the GUI as a person some time ago, and added him to https://henson.durham.ac.uk/journals/28-11-11 at the same time. The entry wasn't showing up on a bulleted list. So I deleted him from XML and then added him again, and a bulleted list has now been created.

**Comment by dpl0js** [comment]
@peterwebster Another success story for a transfer through the GUI, both to the Person (James Barrie) and the journal entry https://henson.durham.ac.uk/people/person5449

However, James Meston now has a third bullet to his list, 18 June 1922, which is the entry in which James Barrie appears. I think this was because I cut and pasted his XML code and updated, before realising my mistake, and

I don't suppose we can now remove errors in the bulleted list. If not, lesson learnt.

**Comment by dpl0js** [comment]
@peterwebster another success story, again from the GUI: https://henson.durham.ac.uk/people/person5455

I'll leave it at that for now.

I am enjoying the larger window for editing now.

**Comment by peterwebster** [comment]
@dpl0js thanks for all these; I think we can probably close this ticket now, with thanks to @alisonrclarke 
I've transferred the point about Meston/Barrie to #256 to which it is most relevant.
