### ISSUE TITLE
Amend text to show that Persons/Places etc markup only applied to some volumes

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#265]
In all of these locations, we need a form of words that notes that the search will only find entries in volumes with markup. Otherwise , users need to use the free-text search instead.

https://henson.durham.ac.uk/people
https://henson.durham.ac.uk/organisations
https://henson.durham.ac.uk/places

**Comment by peterwebster** [comment]
@dpl0js could you possibly compose some suitable text?

**Comment by peterwebster** [comment]
Replacement text (for persons):

'The project has identified over 4,000 different people mentioned in the Journals available so far. Search for these below.

Please note that these search results will be fullest for the period to October 1921, and only partial to June 1926. The work to enable this search for entries after that date continues.

To retrieve results after June 1926, use the 'Journals and annotations' search at the top of the page.


For the other two: 

Search below for [places/organisations; DELETE AS APPROPRIATE] annotated in the journals available so far.

Please note that these search results will be fullest for the period to October 1921, and only partial to June 1926. The work to enable this search for entries after that date continues.

To retrieve results after June 1926, use the 'Journals and annotations' search at the top of the page.

**Comment by peterwebster** [comment]
See interaction between this issue and #262

**Comment by alisonrclarke** [comment]
Have made most of the changes to text but for now kept the dynamic text on the people page.

If the fix for #262 works then hopefully this will be fine; if not then I'll hard-code the number on the people page.

**Comment by peterwebster** [comment]
Noting that the text is amended; will close as and when #262 is closed.

**Comment by peterwebster** [comment]
Leaving #262 open, but closing this now as satisfactorily pushed to production.
