### ISSUE TITLE
Mystery word

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#27]
Neither of us can make out this word: 'an interesting conversation ? the Unemployed'. Does anyone else have any ideas?

![about](https://user-images.githubusercontent.com/32575539/31943177-c7310d02-b8bf-11e7-98a7-a815a392164f.png)

**Comment by williamsonphilip** [comment]
'Anent' is an old word, meaning 'about' or 'concerning'.  It is another instance of HHH's archaism, but it was still reasonably common among some of his generation.  It was still more common on Scotland, and may even still be used there.  I think leave, without explanation.

**Comment by KPalmerHeathman** [comment]
Thanks Philip!
