### ISSUE TITLE
Crayon list

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#28]
I've just come across this right at the end of Vol 15. We think it's a list of pages numbers, but can't yet see what links them together. Should we indicate that these numbers are in colour by bolding them?
![list](https://user-images.githubusercontent.com/32575539/31948299-6e627418-b8ce-11e7-88d9-85075d939242.png)

**Comment by williamsonphilip** [comment]
Um, tricky. If we knew that these were page numbers, and if we knew what these referred to and decided that they had significance, I might suggest that they be omitted but explained in a footnote  - something like 'Henson at some later date inserted a series of numbers, perhaps relating to ....'.  But if we don't know what the numbers refer to, maybe we silently omit here, but add a remark to the statement of 'Editorial policies'?  Perhaps he was just using the space like a piece of scrap paper, without relation to the (rather interesting) original journal list.

**Comment by dpl0js** [comment]
I agree, the numbers can be omitted.  I am sure we will come across similar instances in future volumes, so a reference in Editorial Policies to omission of Henson's very occasional use of the journals - usually front and back covers - as a scribble pad would indeed be appropriate.

**Comment by williamsonphilip** [comment]
Although, of course, please keep a note in case the significance of the scribble numbers become apparanet at some later stage!

**Comment by peterwebster** [comment]
Are @kpalmerheathman and @durhhhi happy that I close this ticket ?

**Comment by dpl0js** [comment]
fine by dpl0js
