### ISSUE TITLE
Split files not well-formed

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#29]
Hi Peter,
I've just opened the xml files from Vol14 to begin work on the xml. I haven't done anything yet, but when I try to run in Firefox, they all give an error, as below. How can I fix this?

![image](https://user-images.githubusercontent.com/32575539/31995230-72deb35a-b97b-11e7-9bfb-b653c3fc6c62.png)

**Comment by peterwebster** [comment]
(From a train)

As you work through populating the control sheet & renaming files, delete
the (!date - that's the problem. You don't need it in the file after this
point as the date info is held elsewhere.

**Comment by KPalmerHeathman** [comment]
Thank you - I knew it would be something small (and something you'd mentioned before and I'd forgotten). Sorry!
