### ISSUE TITLE
Agree procedure for periodic backup of Dropbox contents to Durham filestore

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#3]
There's no reason to suppose that Dropbox is anything but secure, but while using the free plan, if some sort of disaster should occur on their side we may not have any recourse to recover lost data. So, periodically we should download the contents of the folder to a Durham shared drive.

**Comment by dpl0js** [comment]
okay, sounds good.  Shall I ask Sebastian for advice when I am next at my University computer?

**Comment by peterwebster** [comment]
@dpl0js you could, but the process is quite straightforward, so one of the team could do it; we just need someone to take on the responsibility.

**Comment by peterwebster** [comment]
![image](https://user-images.githubusercontent.com/5520710/30206401-e8322d02-9483-11e7-8a51-409d64519c18.png)

@dpl0js it's just a question of selecting the folder and clicking Download, and saving the resulting file to somewhere suitable.

**Comment by peterwebster** [comment]
![image](https://user-images.githubusercontent.com/5520710/30206462-196bcb4e-9484-11e7-97a6-054a4185bd02.png)
It's just a question of selecting the folder, clicking Download and saving the resulting file somewhere suitable.

**Comment by peterwebster** [comment]
Hi @dpl0js : as Katie and Hilary are now here, is this something they should take on? If so, they would need Dropbox access, which I imagine they have.

**Comment by dpl0js** [comment]
Yes, we are just awaiting Katie's IT access, which has been held up because of some problems concerning her name.

**Comment by dpl0js** [comment]
Hi @peterwebster 
I have instructions now on how to move from dropbox to the University's Box facility.  But it requires encryption.  I have to contact the field team.

**Comment by peterwebster** [comment]
If it is something that needs you to contact the field team each time we want to do it, then it might be easier if I just do it. That's slightly less secure, but it might be enough as the risk is low. @dpl0js

**Comment by dpl0js** [comment]
Philip is working on a scheme to provide access for you to the University IT system.  It would be great if you can move the files for us then from within the UoD system.
