### ISSUE TITLE
Project Website

### ISSUE THREAD

**Issue by DurHHHI** [peterwebster/henson#30]
![screenshot-2017-10-26 cms request forms](https://user-images.githubusercontent.com/32575577/32050988-dddd273e-ba4a-11e7-9269-b0bfa030730c.png)

I'm in the process of requesting a project page through Durham. Julia and Philip, do you have a preference re: site url? I was leaning towards a simple dur.ac.uk/henson but thought best to just quickly confirm if we are on the same ... [web] page?

**Comment by dpl0js** [comment]
I had better check this with Boguslaw.  Hold on for now

**Comment by williamsonphilip** [comment]
That seems fine to me.  I guess that we could have 'Henson journals', but there's an advantage in brevity.  Also, this webpage will be different from the final journals website, and it will include perhaps material which is not just about the journals!  Another possibility might be 'Henson project', but again brevity seems best.

**Comment by dpl0js** [comment]
Okay, let's go with dur.ac.uk/Henson.  Thank you Hilary.

**Comment by peterwebster** [comment]
Returning to this from leave, I would concur, so I close the ticket.
