### ISSUE TITLE
insertion marks on p. 44

### ISSUE THREAD

**Issue by dpl0js** [peterwebster/henson#31]
Do you think we should indent the text (as H. does), as well as insert the superscript tags, around this passage on [44] of vol. 15? At first glance, it is a bit unclear to the uninitiated that H. added the comment some time later.

<!040601-120302>
[44]
Tuesday, June 4th, 1901.

I attended the Celebration in Henry VIIth’s Chapel, when the Bishop of London was the Celebrant, and a number of members of the London Diocesan Conference communicated.  
Afterwards I attended the meeting of the Conf: in the Church House.  The Bishop presided, and did very well.  There were animated debates both in the morning & in the afternoon. 
Armitage Robinson moved the amendment on the proposal to re-translate the Athanasian Creed in a remarkable speech, which made a deep impression on the Conference. [45] [symbol] I seconded the amendment.  Then the previous question was moved by Wace & seconded by Riley, & carried by a great majority.  On the whole we succeeded in effecting our purpose viz: discrediting this now fashionable notion of re-translating the Creed.
^Armitage Robinson and I were temperamentally opposed but we were often in agreement on ecclesiastical matters: while Charles Gore and I were almost always opposed on questions of ecclesl policy but attached to one another by genuine affection.^

**Comment by DurHHHI** [comment]
Hi Julia,
I'll bring @peterwebster into this conversation at this point, just to query whether indents made in the word transcription would automatically transfer for XML markup. My understanding is that, if indents are added, this needs to be done manually when working through the XML files. I might have misunderstood this point though, hence my throwing to Peter.

**Comment by peterwebster** [comment]
@DurHHHI is quite right: indentation is a word processing convention which does not transfer automatically. So, we've defined two kinds of indented text, which markup needs to be added at the XML stage: one for the freestanding quotations at the head of daily entries, and another for interpolated letters. If this is a third distinct and redurring type of use of indentation to indicate something (and I can't see the page image to comment) then we can amend the markup scheme to include it. @dpl0js

**Comment by dpl0js** [comment]
![henson 15_0026](https://user-images.githubusercontent.com/31702168/32174394-a03c5a4e-bd79-11e7-8658-1b6d36dd2b3a.jpg)
pls see p. 45 attached.  My experience so far suggests that this kind of retrospective comment is quite rare in the journals.  What do you think?

**Comment by peterwebster** [comment]
@dpl0js thanks for the image, which is very helpful. If I may say, the rareness of this kind of occurrence isn't the decisive consideration (from a mark-up point of view). The key point is, I think:  given that the fact that this is a later addition is indicated by the ^, is there additional significance in its being indented? If so, we should define another type of <div element - alongside those we have already for header quotations and letters - which Katie and Hilary will need to markup in the XML. When the developer is in post, (s)he can define in the stylesheet how that type of passage of text should be presented to the user to distinguish it, which may well be some sort of indentation.
If not, then it should perhaps remain simply as a standard paragraph with ^.
Whichever we settle on, indentation in Word will not be carried into XML.

**Comment by dpl0js** [comment]
@peterwebster Thank you; you are quite right:  this is an insertion like any other and should not perhaps be treated differently from others.  Perhaps @KPalmerHeathman @DurHHHI could keep a note of this page for drawing to the attention of the Developer.

**Comment by DurHHHI** [comment]
Have noted, and closing.
