### ISSUE TITLE
missing table?

### ISSUE THREAD

**Issue by dpl0js** [peterwebster/henson#35]
Hilary and Katie, could one of you please check to see if there should be a table on [58]?  Sorry if I am not quite in full command of tables vs lists yet!

**Comment by DurHHHI** [comment]
Hi Julia,
I've just now looked and, I agree - in this instance, keeping with what Katie and I did later in the transcription once conventions for tables and lists were clarified, I would make the list in question a table. I'll revise and, if you don't mind, send the revision over via email for you to copy and paste in.
