### ISSUE TITLE
Amend Stage 2 script to remove stray whitespace

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#36]
A wrinkle in the OxGarage conversion adds additional whitespace before superscript. 

So:
amend Stage2.sh to sed:

*whitespace*<hi rend="ss

to

<hi rend="ss

(and variations where the ss attribute is not given first.)

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman : I can fix this issue of additional whitespaces associated with superscript text for volume 15 and subsequent volumes, but need to ask you to fix it in the XML for volume 14. If you use the Search (or Find) tool in Notepad++ you should be able to pick them out.

**Comment by peterwebster** [comment]
When we spoke last week @DurHHHI mentioned that not only was there additional whitespace associated with superscript, but also with other punctuation. I realise that you've corrected it now, but if there's any way you can remember some places in volume 14 where this happened, I can see what the problem is.
cc @KPalmerHeathman

**Comment by DurHHHI** [comment]
Hi Peter,
I've noted a few examples via the Vol 14 control sheet - does that help at all? I didn't note each time I made a manual change, only recognizing about 75% through the manual fixes that there seemed to be a spacing issue with some punctuation beyond the superscript.

**Comment by peterwebster** [comment]
Thanks @DurHHHI : a supplementary question for you and @KPalmerHeathman 

In the case of the extra space before superscript, I can go through and remove all instances where you have this, which should cover the cases where there is Mr and Dr and the like.
However, it will also take out a space before a superscript ^ denoting an insertion, giving something like:

... I fully intend to do this for him.^As it turned out, I failed to do this.^ If I fail to do so I shall be as a wretched worm.

Is this a price worth paying? That is, are there more of the former type than the latter, such that you'd rather reinsert these?

**Comment by peterwebster** [comment]
So, the problem is this. OxGarage seems to add a single character of whitespace whenever there is a switch from one kind of <hi  (bold and superscript, say) to another kind of <hi (just bold) between two contiguous characters.

So, watch this further in vol 15. For volume 16, script the following, plus any others that are identified:

(i)  `*space*<hi rend="b">.  to <hi rend="b">.` 
(ii) `*space*<hi rend="sup to <hi rend="sup`
(iii) `*space*<hi rend="bold sup to <hi rend="bold sup`

(taking care that this is in the correct order in the script to look for b and not bold)

**Comment by peterwebster** [comment]
Can I press you for a decision on the matter in the comment two above this one? It is the only thing holding up volume 15 (which I'm sure you're desperate to have)
@KPalmerHeathman @DurHHHI

**Comment by KPalmerHeathman** [comment]
Hi @peterwebster, sorry we were in a project meeting, replying asap. We're fine with losing the space before a superscript denoting an insertion, as these are very rare and we can put them in manually.

**Comment by peterwebster** [comment]
"325 replacements made".
You're welcome @DurHHHI @KPalmerHeathman 

Closing ticket now, transferring part as note to self for later.

**Comment by peterwebster** [comment]
The comment above should of course have read:  "You're welcome ;-) "  @DurHHHI @KPalmerHeathman 

Note to self: jokes are hard.....

**Comment by DurHHHI** [comment]
23 minutes of tears until we saw that ;-) !!

**Comment by DurHHHI** [comment]
(above comment also meant to be read with a ;-) !) Thanks @peterwebster for keeping us smiling!
