### ISSUE TITLE
Remove extraneous digits in element IDs

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#37]
In a wholly admirable obedience to holy writ, @KPalmerHeathman and @DurHHHI have been expressing element IDs as "001", "023" etc.

In stage 4 revision of volume 4, I shall replace these with 1, 5, 27, 49 etc.

**Comment by peterwebster** [comment]
@nomoregrapes hi Gregory:  as per the above, there was some early inconsistency in formatting of element IDs in the XML:  001  but also just 1. Do I need to standardise this in the XML, or will the application tolerate both?

**Comment by nomoregrapes** [comment]
001 Vs 1 is helpful to know, I was going to soon ask which is preferred.

The application will tolerate any amount of spaces, it will only see it as 1.

**Comment by peterwebster** [comment]
Hi @nomoregrapes : thanks for this: if the application will tolerate the inconsistency (which should be in volume 14 only) I shall leave it as it is. Preference is 1,2,3, and it should be this way from that point on in the sequence.
Closing ticket.
