### ISSUE TITLE
Nesting superscript within person name

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#38]
Hi @KPalmerHeathman @DurHHHI : we discussed before some difficulty in marking up part of a person name as superscript. I've just tried to break this, but it seems to work, for example using:

`Mr <persName id="123">Cec<hi rend="sup">il</hi></persName>`

Could you try to replicate the problem you've had before, and paste the code in here, paying particular attention to the nesting of the tags?

(When you do, use the 'Insert Code' option in the toolbar, which will display the code as above.

**Comment by KPalmerHeathman** [comment]
Hi Peter, here's an example of the problem:

`We picked up <persName id="031">Lord W</hi>
            <hi rend="b sup u">m</hi>
            <hi rend="b u"> Cecil</persName>`

There is another which I will try to find.

**Comment by KPalmerHeathman** [comment]
`<hi rend="b u">I dined with <persName id="102">M</hi>
            <hi rend="b sup u">rs</hi>
            <hi rend="b u"> Romanes</persName>`

**Comment by peterwebster** [comment]
Yes, it's an issue with the nesting, as in both cases you've got <hi markup that spans either before or after the line of code you've quoted.

In the second example, you'd need to close the first <hi one before the <persName and open it again inside it, and then close before the closing <persName and open again after, like so:

`<hi rend="b u">I dined with</hi> <persName id="102"><hi rend="b u">M</hi> <hi rend="b sup u">rs</hi> <hi rend="b u"> Romanes</hi></persName><hi rend="b u">`

Fiddly, but it preserves the nesting. In the first example, there must be an <hi open already which needs to be dealt with too.
If Microsoft had implemented XML in Word properly you wouldn't have to do this....

I'll be incommunicado tomorrow, but see how you get on

**Comment by peterwebster** [comment]
*puts tutorial hat on*
Here's the problem @DurHHHI : 

`<hi rend="b u">I dined with <persName id="102">M</hi><hi rend="b sup u">rs</hi><hi rend="b u"> Romanes</persName> &amp; met <persName id="103">Canon Ainger</persName>, the Master of the <orgName id="016">Temple</orgName></hi>,`

Notice that the opening <hi is not closed before the <persName, which is from whence the problem stems. I think if you replicate what I did for this in the comment above, it should sort itself out. Let me know if not.

In this case, Firefox's error message got you to the right place, but you need to scroll along to the end of the .... ^

**Comment by peterwebster** [comment]
@DurHHHI this way of viewing it may help, with each little cluster of nested elements on its own line:
`<hi rend="b u">I dined with</hi>`
`<persName id="102"><hi rend="b u">M</hi> <hi rend="b sup u">rs</hi> <hi rend="b u"> Romanes</hi></persName>`
`<hi rend="b u"> &amp; met</hi>`
`<persName id="103"><hi rend="b u">Canon Ainger</hi></persName>`
`<hi rend="b u">the Master of the</hi>` 
`<orgName id="016"><hi rend="b u">Temple</hi></orgName>`

**Comment by DurHHHI** [comment]
Thank you Peter - that is very helpful! I'll need to watch for those closures! For the moment I've nestled the persName just on 'Romanes'.

Really appreciated!

**Comment by peterwebster** [comment]
If you're happy that this is dealt with, do close the ticket @DurHHHI . Copying @KPalmerHeathman in for information before it disappears from the list of Open Issues.
