### ISSUE TITLE
Imperfect conversion of Word styling to XML

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#39]
@DurHHHI and @KPalmerHeathman supply these examples from volume 14:

Ex. 21 Oct 1900 - Word file cleaned [went back to check], underline sections in XML absent
Ex. 28 Nov 1900 - Spacing issue with date; also no superscript underline
Ex. 27 Nov 1900 - "Daily News" line supposed to be all italics; underline of 'can' captured but no italics.

**Comment by peterwebster** [comment]
I'll need to return to this a little later in the week, but could you add a screenshot of what you see in Firefox for the first of these examples? @DurHHHI @KPalmerHeathman 
The XML seems to be OK, but perhaps it's a stylesheet issue.

**Comment by DurHHHI** [comment]
![peter 21-10-00 xml ex](https://user-images.githubusercontent.com/32575577/32221013-c5ad759e-be2b-11e7-90a3-5f779a365492.png)

**Comment by DurHHHI** [comment]
Bold underline for Henson's underline markup not appearing, also notice that there are additional spaces reflected both before and after superscript text

**Comment by peterwebster** [comment]
Thanks @DurHHHI : the latter issue is being dealt with at #36 .

**Comment by peterwebster** [comment]
Revised stylesheet supplied, awaiting feedback after testing.

**Comment by DurHHHI** [comment]
Yes, thanks Peter, knew it was being addressed after our conversation (and now clocking raise in #36). Just noticed that where I thought it was only affecting spacing in front of the superscript characters, it is front and back.

**Comment by KPalmerHeathman** [comment]
Thanks for the new stylesheet. Just tested and bold underline is still showing as just bold.

**Comment by peterwebster** [comment]
@KPalmerHeathman at which point?

**Comment by KPalmerHeathman** [comment]
In the same example as Hilary shared above, about picking up Lord Cecil. Everything bold in that entry should also be underlined, but is not displaying as such.

**Comment by peterwebster** [comment]
By and large you can only underline a character, so if you delete the stray whitespace either side of the m of Wm, the gaps disappear. The superscript m is underlined, but it is superscript so it looks as if there's a gap. If there's anything to be done with this, it will have to be at the developer stage.

**Comment by KPalmerHeathman** [comment]
Every bold sentence in that entry should also be underlined though, not just the superscript, but it's only bold at the moment.

**Comment by peterwebster** [comment]
This is what I'm seeing...

![image](https://user-images.githubusercontent.com/5520710/32282296-20b15b98-bf19-11e7-860e-4f7cf6659230.png)

**Comment by KPalmerHeathman** [comment]
I'm still seeing the below, even though I've saved the new stylesheet.
![clipping](https://user-images.githubusercontent.com/32575539/32282404-68672788-bf19-11e7-9273-62c73ce41b4b.png)

**Comment by peterwebster** [comment]
Could you double check the filename of the stylesheet at the very top of the XML file matches that of the XSL file, and that they're in the same directory?

**Comment by KPalmerHeathman** [comment]
Argh, they were saved in different places and it's all fine now. Sorry for being so slow!

**Comment by peterwebster** [comment]
Don't worry, it's a very common error. Has the new stylesheet solved all the issues that were first raised?

**Comment by peterwebster** [comment]
Closing this ticket now @KPalmerHeathman : do open it again if I'm wrong in thinking that the issue is resolved.
