### ISSUE TITLE
Date codes

### ISSUE THREAD

**Issue by dpl0js** [peterwebster/henson#41]
@KPalmerHeathman @DurHHHI 
Please can I clarify date codes with you.

Where there is a date span, do we exclude letters where they are free-standing, i.e. not book-ended by a journal entry.  E.G. vol. 15, [189-193] has only one date.  

But [230-39] has a date span even where it ends in a letter.  

Should 189-193 have a date span, too?

**Comment by DurHHHI** [comment]
A date span indicator for pg. 189-193 could be added but it is not required, only helpful to Katie and I as a speedy catch when we remove the date codes at XML stage and input the entry start and end dates into the control sheets.

**Comment by dpl0js** [comment]
@DurHHHI Thank you Hilary, then  I shall just leave the date code spans - and absence thereof - as they are.
