### ISSUE TITLE
Collecting strings to be marked up by script at Stage 2

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#43]
@DurHHHI @KPalmerHeathman you'll find in GDrive a new file called Replace. 

In it, could you fill out three columns: 

- B and G must be identical, B being the string of characters you want the script to pick out, and G the means by which it writes those back into the file surrounded by the requisite tags (which are in columns D, E, F and H.
- E is the ID of the person.

I'd like to try this out on volume 15, so (relatively soon) could you add in a few persons that we know will occur: I've suggested some - though without the correct ID numbers.

Once you have, I can download this, mash all the columns together and otherwise add things to create the script.

As I mentioned, we'll need to revise this as we go along. I've yet to decide how to manage those revisions to minimise the effort each time.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI thanks for adding some lines to this sheet; do you think that's all you have for now, or should I wait a day or two?

**Comment by peterwebster** [comment]
Note also that, as currently expressed, the result could be

`<persName id="113>Harold</persName><persName id="113">Knowling</persName>`

unless you're reasonably sure that he is seldom referred to by his full name. 
It will also catch other Harolds, which will need to be corrected.

@KPalmerHeathman @DurHHHI

**Comment by KPalmerHeathman** [comment]
Hi Peter,
I've changed Harold to avoid this, and added a few organisations and places to the list. I don't think there are many more, but I'll let you know by the end of the day whether it's ready to go.

**Comment by KPalmerHeathman** [comment]
We're ok to go now!

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI do you want to include Davidson/Cantuar? If so, he needs an ID....

**Comment by KPalmerHeathman** [comment]
Sorry @peterwebster, meant to take those out - rarely mentioned in 15 so we'll do it manually when we get to him.

**Comment by peterwebster** [comment]
Thanks @KPalmerHeathman : 
One point to note, for the next time we revise this script @DurHHHI :

The changes are applied in the order they are listed: that is, the script goes through the whole file marking up the first term, and then goes back to the beginning and does the second one etc.

So, if you have both 'Harold' and 'Harold Knowling', then we must do 'Harold' first, since if we don't, it marks up 'Harold Knowling' and then 'Harold' within that element, like so:

`I met with<persName id="113"><persName id="113">Harold</persName> Knowling</persName>`

To be successful in this game, think like a machine.

**Comment by peterwebster** [comment]
This of course means that 'Harold Knowling' will never in fact be found by the script. (Since it will only ever see:
`<persName id="113">Harold</persName> Knowling`

So, there is actually a choice to make: would you rather 
(i) have all Harolds marked up, and have to amend those which are not Mr Knowling, or:
(ii) have only 'Harold Knowling' marked up, and have to manually do those where he is referred to by first name only
What do you think @KPalmerHeathman @DurHHHI ?

**Comment by KPalmerHeathman** [comment]
My twopenn'orth is that most Harolds in vol 15 are young master Knowling, so we should mark up all Harold and manually amend the others. Unless @DurHHHI thinks otherwise?

**Comment by DurHHHI** [comment]
Nope, I think similar(wise) ;). @KPalmerHeathman

**Comment by peterwebster** [comment]
Marvellous: have amended both the script and the master list in GDrive.

Clearly we want to keep this under review as we go along. Could you use the GDrive as the place for such amendments, but use the CHANGE column to indicate what I need to revise (including deletions). @KPalmerHeathman @DurHHHI
