### ISSUE TITLE
Extraneous <seg tags in XML

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#44]
The conversion process for volume 15 has thrown up an eccentricity, in that it has inserted <seg tags at various places, which (in TEI terms) represents an arbitrary segmentation of the text below the paragraph level. 
This makes me suspect that these were keyed in some way which you have removed, but because Word leaves all sorts of invisible debris behind, it is carried through to the XML.

Could you possible look at the original transcript for:

(i) the italicised passage for May 11 1901 
(ii) on August 6th 1905, the passage beginning 'there was again a considerable...'

and let me know if there was anything unusual.

@KPalmerHeathman @DurHHHI

**Comment by DurHHHI** [comment]
Nothing unusual that I see, Peter - beyond that these passages were both sitting at the start or within a vertical marginal line.

![capture_1](https://user-images.githubusercontent.com/32575577/32779074-4cb9892a-c934-11e7-9c91-b23c87ca11e0.JPG)

----

![capture](https://user-images.githubusercontent.com/32575577/32779083-53abef0c-c934-11e7-88c7-bbcf09f0bc59.JPG)

**Comment by peterwebster** [comment]
Thanks @KPalmerHeathman : it will be some remnant of the code associated with the vertical line.

Note to self:  remove these manually in volume 15 but watch for recurrence in 16. If this occurs, amend the Stage 2 script.

**Comment by peterwebster** [comment]
Also, in 16, check for <anchor tags : three of these in V15, seemingly without reason.

**Comment by peterwebster** [comment]
In volume 16 we get:

`<seg xml:space="preserve">  </seg>`

where the gap is two characters of whitespace. Check again in volume 17 and amend script then.

**Comment by peterwebster** [comment]
No recurrence of the <anchor in volume 16

**Comment by peterwebster** [comment]
In 17, for the first time, several occurrences of:
`<cb/>`
Removed manually this time, amend script.

**Comment by peterwebster** [comment]
After disappearing in 16, many instances now of:
`<anchor xml:id="Hlk509847804"/>`

Possible that this a hangover of footnotes inserted and then removed, although not in positions that would suggest so. Check again in 18.

**Comment by peterwebster** [comment]
Also, more occurrences of <seg , as above. Amend script.

**Comment by peterwebster** [comment]
This has not reoccurred, so closing ticket now.
