### ISSUE TITLE
Spacing issues in XML

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#46]
We seem to be having some spacing issues in Vol 15 as well, I'm afraid. It's around superscripts again:
`<p>
            <hi rend="b">The Epiphany, Sunday, January 6</hi>
          <hi rend="b sup u">th</hi>
            <hi rend="b">, 1901.</hi>
         </p>`

We can take the spaces out manually of course, but it's going to take a lot of time. Is there a way @peterwebster can do anything  - we've not marked up many pages of Vol 15 yet so would be able to start again if necessary.

**Comment by peterwebster** [comment]
Thanks for pointing this out: how long do I have to decide what to do without holding you up? @KPalmerHeathman @DurHHHI   It will involve discarding what you've done already, *or* leaving it until after you've done the markup - but that risks introducing new errors and (I'm assuming) that you won't have to time to check for.

**Comment by DurHHHI** [comment]
@peterwebster We can continue to work on transcription for Vol 16, and editorial comment for the next few days if you have opportunity to play with the issue. I see us finishing the transcription check for 16 by end of the week. Would that give enough time?

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI could you take a look at the files you have and see whether it is *only* in the cases of "b sup u ?
Is it OK for "b" and "sup u ?

**Comment by peterwebster** [comment]
Actually, scratch that: I can that there's a problem for all three.

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI OK: I shall need to come back to this, but I'm halfway there. I haven't yet been able to remove the issue entirely so far, but (should I get no further) it should now be very obvious when you open the XML file which are the offending lines, which may be fixed with a single stroke on the backspace key.

**Comment by peterwebster** [comment]
In the sample files I've just sent, hopefully it will look like this in Notepad, where the problem lines are hard to the left. @KPalmerHeathman @DurHHHI 
![image](https://user-images.githubusercontent.com/5520710/33130702-1aa56a18-cf8c-11e7-8f07-dbd3e437fd90.png)

**Comment by DurHHHI** [comment]
Hi @peterwebster - This is exactly what the files look like. If we have to make manual adjustments, it is really handy to have the problem lines identified so easily. Many thanks! @KPalmerHeathman

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI OK, there is now another folder in Dropbox with the new files (V15_split_v2 ).
You're welcome :-)  speak to you guys tomorrow.
