### ISSUE TITLE
Dev/stylesheet: underlined superscript in bold underlined sections

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#47]
Text which is bold underlined and also includes superscript is supposed to retain only the bold underline, with the superscript not having its own separate underline. However, it seems that the superscript underline takes precedence in XML, even when it is correct in Word:

`<hi rend="b u">I proposed to M</hi><hi rend="b sup u">r</hi><hi rend="b u"> Talbot that the Burgesses of `

**Comment by peterwebster** [comment]
I'm not sure I'm grasping the issue: could you grab a screenshot from Firefox @KPalmerHeathman ?

**Comment by KPalmerHeathman** [comment]
Sorry, terrible at explaining!

Here in Word, Mr Talbot bold underlined with the underline not on the superscript:
![word](https://user-images.githubusercontent.com/32575539/33027663-a911dbd8-ce0b-11e7-936d-f90837161fd3.png)

Here in Firefox, with the underline reverting to the superscript:
![xml](https://user-images.githubusercontent.com/32575539/33027683-b619c37c-ce0b-11e7-890c-7445b66be35d.png)

**Comment by peterwebster** [comment]
OK, got it. I don't think there's anything that can be done at this stage; that's just how the browser deals with it. I'm now converting this ticket to a note to see whether it can be fixed in the stylesheet for the live site, but I'm not completely confident it can be. It may be an eccentricity we have to live with - or, we have to think entirely afresh about how it is handled. How big an issue do you view it as (in the final site)? @KPalmerHeathman @DurHHHI

**Comment by peterwebster** [comment]
@nomoregrapes you may recall we discussed this on Monday, so I'm assigning this to you for reference.

**Comment by nomoregrapes** [comment]
I can do this as desired for underlines, and even for double underlines.

It will require me to work a lot more trickery to avoid the strike-through being superscript'd, maybe that doesn't bother you so much?

Working example of double underline being striked-through, with a superscript element in the middle:
![henson-line-styles](https://user-images.githubusercontent.com/1181194/35969682-91828628-0cbf-11e8-86d0-91d3d4a7c51c.png)

**Comment by peterwebster** [comment]
@nomoregrapes sorry for the delay in replying on this. This looks good to me. Thoughts @KPalmerHeathman @DurHHHI ?

**Comment by KPalmerHeathman** [comment]
Sorry if I'm being dense here, but what is the strike-through representing?

**Comment by peterwebster** [comment]
@KPalmerHeathman I think @nomoregrapes is just showing what the interaction between superscript, underlining and strikethrough would be, should they occur together. The point was: are we happy that superscript text is struck through in this way (ie. that the line is vertically discontinuous)? @DurHHHI

**Comment by KPalmerHeathman** [comment]
Ah I see, thanks @peterwebster and @nomoregrapes. I don't have the transcription styleguide in front of me right now, but I don't think we are using strikethrough at all anyway - if Henson crosses something out, we take it as gone. @DurHHHI might think differently?

**Comment by DurHHHI** [comment]
Hi all! @nomoregrapes @peterwebster @KPalmerHeathman I personally think the above example, with the superscript interrupting the unbroken horizontal underline, looks just fine. The presentation is still very clear for the reader. As K says, we won't be working with much Henson strikethrough in the text, if at all - but it is good to see how it'll all reflect visually if we do come across strikethrough excerpts.

**Comment by peterwebster** [comment]
OK: I think we're agreed that this works well @nomoregrapes . As it is already made, let's leave it in the stylesheet, even if it is unlikely to be used very much; it allows a change of mind later. @KPalmerHeathman @DurHHHI

**Comment by peterwebster** [comment]
After discussion on 22/5, team decided that where there is superscript AND underlining, the underlining should jump up with the superscript character(s).  @nomoregrapes

**Comment by nomoregrapes** [comment]
[This is the example](http://10.245.28.108:3000/journals/01-01-10) of superscript with underline (the line now jumps up). Seems good on Chrome & Firefox, would anyone like to test it on Safari and Internet Explorer?
![journal-styles](https://user-images.githubusercontent.com/1181194/42158479-739678aa-7de8-11e8-92ad-f6e43a5576e2.png)


I noticed the styling wasn't functional at all since recent changes (u to underline, etc), all fixed now.

**Comment by KPalmerHeathman** [comment]
Fine on IE. I've never been able to access the website on Edge...

**Comment by DurHHHI** [comment]
<img width="1231" alt="screen shot 2018-07-02 at 2 45 50 pm" src="https://user-images.githubusercontent.com/32575577/42167719-c26af1c2-7e06-11e8-9441-ee7ac4a5cc82.png">

**Comment by DurHHHI** [comment]
This is a screenshot from chrome - just showing what seems to be a slightly different placement between the first and second underline of M**r** Talbot.

**Comment by peterwebster** [comment]
Some differential vertical positioning of the underlining of superscript, for information. Not *at the moment* a high priority.

**Comment by peterwebster** [comment]
@nomoregrapes assigning to you for information, but ignore this until August.

**Comment by peterwebster** [comment]
@nomoregrapes this one is still on the low priority list, but I flag it up as it is now, in fact, August.

**Comment by peterwebster** [comment]
As this has not been raised during the acceptance period, closing ticket.
