### ISSUE TITLE
Zoo or 300?

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#49]
Would anyone like to offer a judgement on Henson's monthly accounts for Feb 1907? Zoo or 300?
![image](https://user-images.githubusercontent.com/32575539/33183155-9eff6c04-d06e-11e7-8922-79c1a384d6a9.png)

**Comment by dpl0js** [comment]
@KPalmerHeathman I think this means the zoo:  as we have discussed, he likes going there!  He was fascinated by the livestock at Birkenhead and Liverpool docks in 1885!

**Comment by peterwebster** [comment]
As I think this is resolved, I close this ticket.
