### ISSUE TITLE
How miserable are these ?, which make hypocrites of us all.

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#50]
![image](https://user-images.githubusercontent.com/32575539/33381413-ddd1499c-d515-11e7-99fc-c436ebe70e27.png)

Can anyone clear up the mystery word here?

**Comment by dpl0js** [comment]
@KPalmerHeathman The closest I can get to this at the moment is 'cares'.  But I will pay close attention to the passage when I check the volume.

**Comment by KPalmerHeathman** [comment]
Thanks @dpl0js , it's p. 407 of the journal.

**Comment by KPalmerHeathman** [comment]
Here's the full passage in case @williamsonphilip or @peterwebster can decipher it:
![image](https://user-images.githubusercontent.com/32575539/33436126-14cd61f8-d5dc-11e7-98e4-f1b3395c6b92.png)

**Comment by williamsonphilip** [comment]
The meaning seems to be that H was put on the spot by Lang, and ended up saying things he regretted.  This looks like a contemporary or colloquial term for such situations.  I guess a possibility might be 'jars' (which sort of makes sense) - but does H use a reverse 'j' elsewhere?

**Comment by KPalmerHeathman** [comment]
It does look very much like his usual lower case j, but reversed - I can't think of a previous example of this reversal. Henson's c can sometimes descend below the line though, to complicate matters:
![image](https://user-images.githubusercontent.com/32575539/33438268-409ffbdc-d5e2-11e7-9e43-7b0fe0614765.png)
I'm stuck between it's a j, and it's a c followed by ', and a contraction for something we're not thinking of.

**Comment by dpl0js** [comment]
I think 'jars' is spot on:  see OED (n), 6b, 'A dissension, dispute, quarrel, now used chiefly of petty (esp. domestic) broils.  See Bunyan and Dryden entries especially.

**Comment by peterwebster** [comment]
Coming to this late, I would agree that 'jars' works. As I think this is probably resolved @KPalmerHeathman I'll close the ticket.
