### ISSUE TITLE
Crayon numbers 

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#51]
![image](https://user-images.githubusercontent.com/32575539/33436031-c2bde928-d5db-11e7-90ae-ee1b1f51abe8.png)
Hello all. Would anyone like to offer any suggestions on how we should deal with words or numbers written in coloured crayon?

**Comment by dpl0js** [comment]
@KPalmerHeathman Could it be inserted in bold superscript, thereby indicating that it is a later insertion? A note in the Editorial policies would cover such action.  I see that there is a similar reference on p, [450] - back to [441].

**Comment by williamsonphilip** [comment]
Yes, the meaning of the 'v.' is vide, see, so 'see p. 450'.   This is H reading the journal at the time of preparing Retrospect, and making cross references.

**Comment by KPalmerHeathman** [comment]
Thank you @williamsonphilip , I am aware of the meaning, I was merely enquiring as to how it should be rendered in the edition as we don't yet have an editorial policy for text, as opposed to underlining/marginal lines, in crayon.

**Comment by peterwebster** [comment]
I would be reluctant to insert it, since it relates to the entry as a whole, rather than to a specific point on a line. How about in a footnote? @KPalmerHeathman @dpl0js

**Comment by dpl0js** [comment]
Yes, a footnote sounds like a good solution.

**Comment by peterwebster** [comment]
Closing this as dealt with @KPalmerHeathman @DurHHHI
