### ISSUE TITLE
This list

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#52]
Hi Peter,
I can't work out what I'm doing wrong here, but this list won't run - Firefox says the problem is with the </list> but I just don't see it...
`<hi rend="b">[111]</hi>
         </p>
         <p>Copies of <ref id="13">"Preaching to the Times"</ref> have been sent to:-</p>
         <list type="unordered">
            <item><persName id="216">Gow</persName></item>
            <item><persName id="109">The Archdeacon</persName></item>
            <item><persName id="76">Carissima</persName></item>
            <item><persName id="77">Marion</persName></item>
            <item><persName id="300">>Ellison</persName></item>
            <item><persName id="62">Kirshbaum</persName><item>
            <item><persName id="301">Burrows</persName></item>
            <item><persName id="302">Miss Anson</persName></item>
            <item><persName id="303">Ryder</persName></item>
            <item>Auntie</item>
            <item><persName id="202">Eyre</persName></item>
            <item><persName id="211">Woolcombe</persName></item>
            <item><persName id="59">Gerald</persName></item>
            <item><persName id="304">Cox</persName></item>
            <item><persName id="65">Thesiger</persName></item>
            <item><persName id="305">Gilbert</persName></item>
		</list>`

**Comment by peterwebster** [comment]
Line 5, there's an opening item tag instead of a closing one after Kirshbaum @KPalmerHeathman

**Comment by KPalmerHeathman** [comment]
*headdesk*
Thank you!
