### ISSUE TITLE
Non-crayon marginal lines

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#55]
We don't currently have a style policy on how to render marginal lines added in black at the time of writing, rather than in colour later.  We're differentiating between black and coloured underlining already. I've just come across this in volume 17:
![image](https://user-images.githubusercontent.com/32575539/34994314-00f4ec1e-facb-11e7-9edd-31d3c06d4210.png)
Any suggestions for how to deal with this?

**Comment by dpl0js** [comment]
Dear Katie, Can't we just leave the marginal lines in black, as with black underlining added at the time of writing?  Perhaps we can explain in 'editorial policies' the nature of black marginal strokes.  They are a frequent occurrence in the later volumes.  Sorry if I have missed something.

**Comment by KPalmerHeathman** [comment]
I thought the reason we were converting crayon marginals to italics was because marginal lines wouldn't pull through in the XML stage? @peterwebster, would you be able to confirm whether this is the case?
If it's not possible to use marginal lines, I assume we'll either need to italicise as for crayon marginals, or come up with a new way of differentiating between them.

**Comment by dpl0js** [comment]
I have just checked the rev'd transcription style sheet (bottom p. 14) and there doesn't seem to be a problem with vertical lines; we just did away with them when they are coloured.

**Comment by peterwebster** [comment]
Sorry to come late to this @KPalmerHeathman @dpl0js . It is certainly true that (a) vertical marginal lines in the Word transcription will not survive the conversion to XML, and (b) this applies whatever the colour. So, we need to represent these by italics and/or some other text effect, and differently if we want to distinguish between black ones and coloured.

**Comment by dpl0js** [comment]
Thanks Peter, I think we do need to distinguish black from coloured marginal lines.  How about 'small capitals' in the font menu?

**Comment by peterwebster** [comment]
Is it the case that black marginal lines correspond to a whole block of text (a quotation, as in this case), whereas the colours refer to a sentence or sentences within a paragraph? @KPalmerHeathman @dpl0js 

FWIW, I dislike small caps for anything more than a word or two, just for the visual effect.

**Comment by KPalmerHeathman** [comment]
The coloured margin strokes often correspond to a whole block of text as well. 

We haven't used just bold, without underlining, yet?

**Comment by dpl0js** [comment]
Thanks Katie, bold without underlining sounds like a good solution.

**Comment by peterwebster** [comment]
This sounds good to me.

**Comment by peterwebster** [comment]
I think this is now settled and so I close the ticket. Can I leave @dpl0js to revise the style guide?

**Comment by KPalmerHeathman** [comment]
@dpl0js, @williamsonphilip, @peterwebster, @DurHHHI 
I've reopened this because we've realised that bold is not a good solution for this after all, because if/when there are underlined words or sentences within a black marginal lined section, we won't be able to differentiate between black and crayon underlining as the whole section will be bolded. We're going to need a solution to this as the black marginals are not going away during the rest of 17 at least.

**Comment by dpl0js** [comment]
Thanks Katie,
Peter, have we run out of options, apart from small capitals?  Might we see the full effect of small capitals, in bold, where there is some coloured underlining?

**Comment by peterwebster** [comment]
I think we have indeed run out of combinations of bold, italic and underline, and I woudl still say that small capitals are really only suitable for a word or two. So, I think we'll need to return to placing a symbol before and after the passage of text concerned. So:

*There are three ranks of truths.... careful disquisition. [with a closing * 
+There are three ranks of truths.... careful disquisition. [also with a closing +]
~ There are three ranks of truths.... careful disquisition. ~
#There are three ranks of truths.... careful disquisition.#


I have no strong preference for any of these.

**Comment by peterwebster** [comment]
@dpl0js as I think @KPalmerHeathman and @DurHHHI are in transcription-checking mode for the next volume, can I press you for a decision on this?

**Comment by dpl0js** [comment]
I agree with Philip: a single + for one marginal stroke and ++ for a double stroke.  If HH uses a plus sign for etc, it would be in the middle of a sentence; usually he uses &c.

**Comment by williamsonphilip** [comment]
Ah: my suggestion  was not so much whether Henson himself used the symbol +, but how readers might at first sight read it as meaning either another type of ampersand (common in many handwritten documents), or indeed as a plus.  So I thought that perhaps one of the more unusual symbols suggested by Peter might be better, e.g.  ~ and ~~

**Comment by dpl0js** [comment]
Apologies, I was in too much of a rush yesterday and failed to read the github trail properly.  
~ and ~~ is fine with me.

**Comment by dpl0js** [comment]
I have just realised that there is no need for ~~ in relation to double vertical lines.  This is because we are not distinguishing between single and double underlining.

**Comment by KPalmerHeathman** [comment]
We are distinguishing between double and single underlining. In volume 17 I've been using ~~ for double marginal, is this a problem?

**Comment by dpl0js** [comment]
This is fine for style.  My point in the earlier comment was that we don't distinguish between double and single underlining in colour - do we? apologies if I am mistaken in this:  I probably need a reminder.

**Comment by KPalmerHeathman** [comment]
Just to confirm that I've found double colour underline today, which I have bold double-underlined.

**Comment by dpl0js** [comment]
Thank you Katie, much appreciated. J

**Comment by peterwebster** [comment]
Have we therefore reached agreement on this? If so, could I leave it with @dpl0js to make whatever amendments to style guides that are needed? @KPalmerHeathman @DurHHHI

**Comment by dpl0js** [comment]
Yes, please continue with bold double-underlining.

**Comment by peterwebster** [comment]
@dpl0js @KPalmerHeathman if you guys are clear on this one, could you close this ticket?
