### ISSUE TITLE
Won't run, but I can't work out why?

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#57]
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="styles.xsl" ?><text><body>
         <p>
<hi rend="b">[353]</hi>
         </p>
         <p>
<hi rend="b">All Saints Day, Tuesday. November 1</hi>
<hi rend="b sup u">st</hi>
<hi rend="b">, 1904.</hi> 
         </p>
         <p>Kirshbaum celebrated.  There were 15 communicants.  <hi rend="b u">I made a vain attempt to see Caroe, the architect, who has designed that hapless Farrar monument</hi>.  Then I saw the Dean with reference to the dinner.  Thus my morning was frittered away, <hi rend="i">but I succeeded in reading through Bevan's interesting sketch, ‘Jerusalem under the High Priests'.</hi>  
         </p>
         <p>In the afternoon I travelled to Oxford in order to attend the Gaudy.  In the train I read through most part of Bp. Ryle's little book on "Criticism &amp; the Old Testament".  It is timely &amp; honest.  <hi rend="i b u">In Hall I sat next Lang, and was churlish to him</hi>.</p>
         <p>
            
         </p>
         <p>
            &lt;!021104>
         <p>
<hi rend="b">[354]</hi>
         </p>
         <p>
<hi rend="b">All Souls Day, Wednesday, November 2</hi>
<hi rend="b sup u">nd</hi>
<hi rend="b">, 1904.</hi>
         </p>
         <p>
<hi rend="i b u">I went across to college, &amp; made my peace with Lang</hi>: then to the chapel where I preached a brief sermon to the fellows, &amp; afterwards celebrated the Communion.  After service I took Compton for a turn round the Parks, &amp; then lunched with Rashdall at New College.  I looked up Alan Henderson in Ch.Ch.: &amp; I took him to Queen's where I had tea with Albert.</p>
         <p>There was a good muster of fellows &amp; quondams at dinner.  <hi rend="b u">Wood made an excellent Latin speech</hi>: &amp; the Mallard Song was sung with immense zeal.  We were all garnished with medals commemorating the Mallard procession on Jan<hi rend="sup u">y</hi> 14<hi rend="sup u">th</hi>.</p>
         <p>
            
<hi rend="i b u">Lang had a long talk with me, in which he earnestly disavowed approval of the Bp. of London's action, &amp; professed himself my friend, though in opposition on many points.  He appeared to be sincere</hi>
<hi rend="i bold">.</hi>
         </p>
         <p>
            
         </p>
         </body></text>

**Comment by KPalmerHeathman** [comment]
Sorry, should be:
`<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="styles.xsl" ?><text><body>
         <p>
<hi rend="b">[353]</hi>
         </p>
         <p>
<hi rend="b">All Saints Day, Tuesday. November 1</hi>
<hi rend="b sup u">st</hi>
<hi rend="b">, 1904.</hi> 
         </p>
         <p>Kirshbaum celebrated.  There were 15 communicants.  <hi rend="b u">I made a vain attempt to see Caroe, the architect, who has designed that hapless Farrar monument</hi>.  Then I saw the Dean with reference to the dinner.  Thus my morning was frittered away, <hi rend="i">but I succeeded in reading through Bevan's interesting sketch, ‘Jerusalem under the High Priests'.</hi>  
         </p>
         <p>In the afternoon I travelled to Oxford in order to attend the Gaudy.  In the train I read through most part of Bp. Ryle's little book on "Criticism &amp; the Old Testament".  It is timely &amp; honest.  <hi rend="i b u">In Hall I sat next Lang, and was churlish to him</hi>.</p>
         <p>
            
         </p>
         <p>
            &lt;!021104>
         <p>
<hi rend="b">[354]</hi>
         </p>
         <p>
<hi rend="b">All Souls Day, Wednesday, November 2</hi>
<hi rend="b sup u">nd</hi>
<hi rend="b">, 1904.</hi>
         </p>
         <p>
<hi rend="i b u">I went across to college, &amp; made my peace with Lang</hi>: then to the chapel where I preached a brief sermon to the fellows, &amp; afterwards celebrated the Communion.  After service I took Compton for a turn round the Parks, &amp; then lunched with Rashdall at New College.  I looked up Alan Henderson in Ch.Ch.: &amp; I took him to Queen's where I had tea with Albert.</p>
         <p>There was a good muster of fellows &amp; quondams at dinner.  <hi rend="b u">Wood made an excellent Latin speech</hi>: &amp; the Mallard Song was sung with immense zeal.  We were all garnished with medals commemorating the Mallard procession on Jan<hi rend="sup u">y</hi> 14<hi rend="sup u">th</hi>.</p>
         <p>
            
<hi rend="i b u">Lang had a long talk with me, in which he earnestly disavowed approval of the Bp. of London's action, &amp; professed himself my friend, though in opposition on many points.  He appeared to be sincere</hi>
<hi rend="i bold">.</hi>
         </p>
         <p>
            
         </p>
         </body></text>
`

**Comment by peterwebster** [comment]
Between the two days, the date tag is missing an opening bracket (but it can come out anyway), and there is also a missing closing </p tag  

@KPalmerHeathman

**Comment by KPalmerHeathman** [comment]
Oh no, it should be two separate files but didn't split because of the unfinished date tag in the middle (didn't spot that one because I'd already taken out the one at the start). Is there a way I can split the file?

**Comment by peterwebster** [comment]
The fastest way is just to create a new XML file and cut and paste. Save a copy, and cut the irrelevant bits out of each one to make two days. @KPalmerHeathman

**Comment by KPalmerHeathman** [comment]
Thanks 👍
