### ISSUE TITLE
Formatting of bibliographic references in the pop-up boxes (not the static bibliography).

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#60]
[picking up on an email of yesterday]

All the data for this is in the Publications sheet in GDrive, separated out into different columns. Gregory's (@nomoregrapes ) application will assemble the text the user sees from these different fields, and can format that assemblage however we wish (inserting commas, full stops, brackets etc where required.) 

If as a team you would care to define how they should appear, Gregory and I can work out how to implement it.

At the minute, the following is how I've specified that it should behave, in terms of which fields are shown and under which circumstance.

**if Type=Book, show:**
Author/Editor, Title, Subtitle (if not empty), Description (if not empty), PlaceOfPublication, Publisher, Date(Year), CrossRef. 

**If Type=Book Chapter, show:** 
Author/Editor, Title,, Subtitle (if not empty), Description (if not empty), VolumeDetails, PlaceOfPublication, Publisher, Date(Year), CrossRef. 

**If type=periodical, show**: 
Title; Periodical; whichever of the three date fields is not empty, PageRange, CrossRef.

@dpl0js @williamsonphilip @DurHHHI @KPalmerHeathman

**Comment by peterwebster** [comment]
@dpl0js I wonder whether you've been able to give this any consideration.

**Comment by dpl0js** [comment]
Thanks for the reminder.  

Your suggestions seem fine.  Does the question now concern other categories of publication to which we should extend the same treatment, i.e. newspaper articles, poems, and reports?

**Comment by peterwebster** [comment]
Hi @nomoregrapes in the references pop-up, for books, I think this is what is required:

[Author/Editor] comma space [Title (in italics)] semi-colon [Subtitle (if not empty), in italics] space open bracket [PlaceOfPublication] comma space [Date(Year)] close bracket period line break [CrossRef].

So:  H. H. Henson, _Light and leaven: historical and social sermons to general congregations_ (London, 1897).

It looks as though both Description and Publisher may not be required to be visible, but I would comment out the code rather than deleting it for now, as this could possible change once the team get to see this in action.

**Comment by peterwebster** [comment]
For book chapters, it should be:

[Author/Editor] comma space single quote [Title] semicolon space [Subtitle (if not empty)] close single quote comma space  [VolumeDetails] space open bracket [PlaceOfPublication] comma space  [Date(Year)] comma [PageRange] period linebreak [CrossRef]

So  [ref id=24 looks like:
 H. H. Henson, 'The early English constitution', in Henry Offley Wakeman and Arthur Hassall, eds., _Essays introductory to the study of English constitutional history_ (London, 1887), 1-44.


As above, I think Description and Publisher *may* no longer be required.

**Comment by peterwebster** [comment]
And for periodicals:

[Author/Editor] comma space single quote [Title] semi-colon space [Subtitle if not empty] single quote comma space [Periodical in italics] comma space [whichever of the three date fields is not empty] comma space [PageRange] period linebreak [CrossRef].

So:   H. H. Henson, 'The clergyman in politics', _Westminster Gazette_, 14 Oct. 1905, 2.

**Comment by peterwebster** [comment]
@nomoregrapes in all three cases, the semi colon before the Subtitle is conditional on Subtitle not being empty, of course.

**Comment by peterwebster** [comment]
With these three, I suggest that @nomoregrapes implements these and then @DurHHHI can spend some time checking over them in the GUI. That will smoke out any issues to be fixed or ways in which this needs to be extended.

**Comment by williamsonphilip** [comment]
Dear Peter and Julia,

The style which I thought we had for essays in volumes was as follow.  These are in the earlier conventions, and this is how I have been doing them:

H. H. Henson, 'The early English constitution', in Essays introductory to the study of English constitutional history, ed. Henry Offley Wakeman and Arthur Hassall (London, 1887), pp. 1-44.

i.e. title of volume followed by names of editors (not vice versa); and use of p. or pp. here (in essays, but not in periodicals).

I was just following a common practice.  I have not strong views … is the other way is easiest for the system, that's OK.

Best wishes,
Philip




________________________________________

**Comment by DurHHHI** [comment]
Hi @williamsonphilip, when the team agreed to move to a (with slight revisions) 'historical journal' template (emails from early April), editor followed by book title was the established convention from historical journal template examples and what I understood to have been agreed within the team. I have been transferring titles to TSV in this style. It would take some time to correct now (as I would have to go to google sheets and correct in the TSV) but this can be done at this stage if you feel strongly about book title before editor/s. 

If this correction needs to be made, please do look through the publications file in the google sheets and check the 'complete reference' column on the transferred references to see if there is anything else you do not like so I can batch corrections. If everything is satisfactory, hopefully there will be no more changes to bibliographic style moving forward as this can take time to re-enter/correct - especially as the file will continue to grow once we start tagging refs in XML markup of 17 onwards.

**Comment by williamsonphilip** [comment]
Dear Peter,

OK, no need to go back and make corrections.  As I wrote, I have not strong views.

I've probably got rather lost in the continuing conversations.  The editorial conventions on OneNote still read as I recalled them.  I think the historical journal style was mentioned for static sheets.  But it is plainly right that there should be consistency across the whole website.

Philip

________________________________________

**Comment by peterwebster** [comment]
Following on from the conversation between Philip ( @williamsonphilip ) and Hilary ( @DurHHHI ) earlier this morning, Hilary is right to say that to move the positioning of the editor name does involve manual changes in each individual entry. However, we can easily insert pp. if that is what is required (the application makes this insertion, and so only one change would need to be made, by Gregory.

**Comment by williamsonphilip** [comment]
Whatever is simpler (which seems to mean not pp.).

**Comment by DurHHHI** [comment]
I support that too (no. pp.).

**Comment by peterwebster** [comment]
OK: Gregory, the requirement for book chapters remains as expressed above @nomoregrapes

**Comment by williamsonphilip** [comment]
Sorry, could we pause this a little?  Julia and I have realised that there is now a difference between the style in persons notes (in some cases where publications are given), and the style in the publications folder.  The issue relates to title/editor and pp. (or editor/title and no pp.).  It is probably the case that the number of instances in the persons file is not many, i.e. less than in the publications file.  If so, I guess this means we could either (a) change in persons notes (tonight I'll look through those not yet transferred) - not sure how we can deal with those already transferred, or (b) not bother about the few inconsistencies in the persons files.  In any event, consistency in future!  More on this (a solution) early in the morning!

**Comment by peterwebster** [comment]
Superseded by #101
