### ISSUE TITLE
Punctuation within or outside elements

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#61]
@nomoregrapes and I discussed yesterday the issue raised by @KPalmerHeathman @DurHHHI : that, if we are using icons to denote the presence of an annotation, the icon will be placed in the middle of a word if our markup is of the format:
 `Boswell</persName>'s`

The similar issue arises with:
 `Henson</persName>,`
 `Henson</persName>!`
 `Henson</persName>?`

I propose (once the XML is finalised) to go through vols 14-16 and rewrite all these so the punctuation appears within the tag.
After that, could Katie and Hilary markup to *include* the punctuation within the tag?  Eg.

 `Boswell's</persName>`

Comments?

**Comment by peterwebster** [comment]
And also in cases of a period, colon, semi-colon and possibly others.

**Comment by DurHHHI** [comment]
Thanks @nomoregrapes , @peterwebster - does this mean a manual correction to existing XML tag markup, or can this be done under the boot? Has a decision about an icon as visual display been finalised? If so, is it possible to place the icon at the beginning of the tag? HHH's laundry dinner lists generally separate individuals by ';' or ','. For visual clarity, would it not be helpful to position these possible icon tags beside the individual and not following the punctuation? I might not be understanding fully, so apologies if so. @KPalmerHeathman

**Comment by peterwebster** [comment]
After a conversation with @DurHHHI @KPalmerHeathman , this to clarify that we have not yet taken a firm decision on the placing of the icon. What do you think to the idea of the icon *before* the term @nomoregrapes ?

**Comment by peterwebster** [comment]
@nomoregrapes makes the salutary point that this might mean in cases:

- the [icon] Dean
- Lord [icon] Melbourne 

Could Hilary possibly pick out an XML file where icon-before might be the best option, so we can test? @DurHHHI

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI as I've just sent you volume 17 for markup, can you start including the trailing punctation inside the tags? If we decide to have the icon after, it will look better, and if we put it before, then no-one will know.

In the meantime, if you guys could pick out some XML examples with different styling of names, so we can do some testing, that would be great.

**Comment by peterwebster** [comment]
@nomoregrapes @KPalmerHeathman @DurHHHI as a bigger testing event is approaching, I think that seeing the markup in 14 and 15 as it currently is will give us an opportunity in the meeting on 22/5 to decide

**Comment by peterwebster** [comment]
Closing this now, as it has not proved to be an issue.
