### ISSUE TITLE
Formatting in TSV annotations

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#64]
Hi @nomoregrapes : just to flag up (if I haven't mentioned it before) that the TSV annotations have standard text effects marked up with HTML tags <i or <b or <u .

Also (I haven't mentioned this before), there are also in some places (mostly Notes) some diacritics : French e acute accents and the like. Which would you prefer:  &eacute; or the full Unicode equivalent?

**Comment by peterwebster** [comment]
By which I meant [ampersand]eacute;

**Comment by peterwebster** [comment]
@nomoregrapes just to flag up that there are several instances of the e acute accent in the persons file you're about to receive, which won't display correctly. No rush for next week, but we should decide this.

**Comment by nomoregrapes** [comment]
In my mind, `&#233;` and `&eacute;` are the same. The latter is better only because you can tell what it is when you're writing/editing it.

It seems like Excel encodes characters when you save anyway. That's another issue, and I'm getting closer to fixing.

**Comment by peterwebster** [comment]
OK: I need to take a while to check which the TEI demands (I think it's full unicode), and that's what we need to observe in the XML. Given that's what we'll need to do there, it will help @KPalmerHeathman and @DurHHHI to be consistent. Reassigning to me from @nomoregrapes to think on.

**Comment by peterwebster** [comment]
As @DurHHHI is closing in on a finalised file of <ref , in which there are some e acute accents, let's say this.

As far as Hilary and @KPalmerHeathman are concerned, wherever they see one of these (TSV or XML), insert: ampersand ecute semi colon, as Gregory has it above.

In the XML, I shall add a conversion of this to the Unicode version (#233), as the TEI insists on it.

Assigning to @nomoregrapes for implementing in both circumstances.

**Comment by peterwebster** [comment]
@DurHHHI could you proceed on this basis?

**Comment by DurHHHI** [comment]
@peterwebster and @nomoregrapes - yes, no problem - will update existing entries.

**Comment by peterwebster** [comment]
Just to confirm that this should be, without the typo I included above @DurHHHI 

`&eacute;`

**Comment by DurHHHI** [comment]
Thanks @peterwebster - haven't done this yet -- there will be more accent identifiers required too, so ok to update beyond &eacute; ?

**Comment by peterwebster** [comment]
@DurHHHI which ones have you seen so far? Umlauts, e grave ?

**Comment by DurHHHI** [comment]
@peterwebster Yes, exactly those - don't believe I've spotted anything beyond the above yet.

**Comment by DurHHHI** [comment]
http://sites.psu.edu/symbolcodes/codehtml/

**Comment by DurHHHI** [comment]
@peterwebster If believe this has been done now with all character symbols updated to HTML entities - in both TSV and XML 
most changes to e acute, which makes sense [nee/ne] - but umlauts, grave, and circumflex in the mix in XML as well.

**Comment by peterwebster** [comment]
Thanks @DurHHHI : assigning to me as a reminder to amend the Stage 7 script for rewrite from HTML to Unicode

**Comment by peterwebster** [comment]
@DurHHHI 

Does this list cover the lot, do you think?
eacute
Eacute
egrave
Egrave
Agrave
agrave
Acirc
acirc
Ecirc
ecirc
Ouml
ouml
auml
Auml
Uuml
uuml

**Comment by DurHHHI** [comment]
@peterwebster  I would add:

ocirc
Ocirc

aacute
Aacute
iacute
Iacute

agrave
Agrave
igrave
Igrave

**Comment by peterwebster** [comment]
So, I now have a working script that takes HTML entities in the XML and converts to Unicode
` sed -i 's/eacute;/#x00E9;/g'`

**Comment by peterwebster** [comment]
If @nomoregrapes is happy that the application now can deal with these being expressed as HYML entities in the TSV but as Unicode in the XML, then this ticket can be closed.

**Comment by nomoregrapes** [comment]
I don't need to do anything for `&#233;` type characters to be recognised & displayed.

**Comment by peterwebster** [comment]
Super @nomoregrapes : closing ticket now.
