### ISSUE TITLE
Sort By options in Journal search results

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#65]
After meeting on Tuesday:

(i) remove Reference Name and Last Name from drop-down list of options
(ii) default to sort by date (rather than relevance)

**Comment by nomoregrapes** [comment]
This is done.
The "journal date" sort order lists no-date results(i.e. not journals) first. When I tried to do the opposite it messed up the ordering completely. I might be able to order results by a specific type order (e.g. journals, then people, then orgs...) before it then orders them by date or relevancy.

**Comment by peterwebster** [comment]
Could you grab a screenshot for me @nomoregrapes ?

**Comment by peterwebster** [comment]
Could @KPalmerHeathman and @DurHHHI take a look at this and feedback?  That is, after a search in the Journals screen, do the results sort by date by default?

**Comment by KPalmerHeathman** [comment]
Yes, results appearing in date order.
