### ISSUE TITLE
Daily page view: pop-up behaviour

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#66]
When user has a pop-up annotation window open, it should close when:

(i) they hit the cross icon, top right [already implemented]
(ii) when they click on any other annotation icon in the page
(iii) when they click elsewhere in the page

**Comment by peterwebster** [comment]
Remove white space after icon.

On hover, expand icon to obscure the following character.

**Comment by nomoregrapes** [comment]
Done a few of these.

As a tickable list...
 - [x] Close when they hit the cross icon, top right
 - [x] Close when when they click on any other annotation icon in the page
 - [x] Close when when they click elsewhere in the page
 - [x] Remove white space after icon.
 - [x] On hover, expand icon to obscure the following character.

**Comment by nomoregrapes** [comment]
I've done the final part "_Close when when they click elsewhere in the page_".

If you're happy with all the ways that popups can close, then we can close this ticket.

**Comment by peterwebster** [comment]
Can @DurHHHI and @KPalmerHeathman test this out and report back?

**Comment by DurHHHI** [comment]
@peterwebster  - pop ups closing when another one is clicked on. Great!
