### ISSUE TITLE
Journals page

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#67]
Search box at top: filter should default to Only Journals

Implement date pickers:  suggest From and To, both with drop-down pick lists (year, month, day).

Of these, only the Year From is required.

**Comment by peterwebster** [comment]
Also need to revise introductory text  [PW and rest of team]

**Comment by peterwebster** [comment]
Add search box in body of page to match Persons, Organisation pages etc.

**Comment by nomoregrapes** [comment]
- [x] search box at top defaults to "Journals only"
- [x] Date picker partially implemented, see screenshot
- [x] Date picker, add "Search" button and make load journal entries(on results page).
- [x] Introductory text - awaiting from team
- [x] Search box in body. Autocomplete (like people) won't work. I've added it, but it doesn't make a lot of sense to have it there (see screenshot)

![journals-page](https://user-images.githubusercontent.com/1181194/40840086-1bfe8e38-659d-11e8-8afa-a19fd823a830.png)

I've designed a date picker based on our discussions, it's probably easiest to try it on the [journals page](http://10.245.28.108:3000/journals).
* If you change "-full year-" to a month, then the end month is enabled, and "-full month-" can be changed.
* If you then change "-full month-" to a specific date, the end date is enabled.
* If you specify June 31 on either side, it will jump down to June 30.
* 1904 was a leap year (so Feb 29 is allowed).
* If the end date is before the start date, it will jump to match the start date.
* Take as little or as much time to specify the range, then hit "Search".

**Comment by peterwebster** [comment]
Hi @DurHHHI : here's something we could test at some point this week, with me 'looking over your shoulder' on Skype as discussed.

**Comment by peterwebster** [comment]
@nomoregrapes curiously, when the page first loads, the EndDate in the picker defaults to 31 December 1900; it should probably just be empty? I see that this is because on first load the YearTo defaults to 1900, and so the DateTo matches it, but it would be better to have them all default to blank. Not urgent however.

**Comment by peterwebster** [comment]
Now superseded by #223
