### ISSUE TITLE
Date formatting in journal view 

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#68]
Change rules for dates in top left corner:

Sun 7 October 1900

Do this also in ranges:

Sun 7 October 1900 -  Mon 8 October 1900

In same view, should read 'Pages 100 to 104'

**Comment by nomoregrapes** [comment]
This is now done.

![pages](https://user-images.githubusercontent.com/1181194/40494664-48d27c3e-5f6d-11e8-933a-fefc3f5b0ffb.png)

**Comment by peterwebster** [comment]
I like this @nomoregrapes so I'll close the ticket now - many thanks.
