### ISSUE TITLE
Sorting in annotation view pages

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#69]
In all cases, sort search results for journal pages in chronological order.

**Comment by peterwebster** [comment]
@nomoregrapes has done this, so to be tested on 7 June.

**Comment by peterwebster** [comment]
Hi @nomoregrapes : we had a look at this just now, and there seems to be an issue with the sorting by date:
![image](https://user-images.githubusercontent.com/5520710/41662965-3b117cf2-749a-11e8-9aae-3b935b7d03f9.png)

**Comment by peterwebster** [comment]
I'm not quite sure which rules it is applying.

**Comment by nomoregrapes** [comment]
The date field is being ingested/saved as a String, not as a date.
I'll need to fix this.

**Comment by peterwebster** [comment]
Oddly, it sorts fine in certain other circumstances, so I wonder whether it isn't to do with the application of the various filters rather than the underlying data.

**Comment by nomoregrapes** [comment]
I have now fixed this.

Spent longer trying to fix it, because I was using the example below which is correct if you pay attention to the year! 
![search_ordered_by_date](https://user-images.githubusercontent.com/1181194/42222358-e43adde6-7ecc-11e8-8978-426ebdd681d2.png)

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI take a few minutes to try various searches, with lots of different combinations of filters, and in various different places around the site, to test this?

**Comment by KPalmerHeathman** [comment]
@nomoregrapes jsut tried to check this and the website seems to be down - ok if this is planned :)

**Comment by DurHHHI** [comment]
![chronological sort](https://user-images.githubusercontent.com/32575577/42330246-a4ca4062-806a-11e8-930e-26824faa7419.JPG)

**Comment by DurHHHI** [comment]
@peterwebster - checking today, sort working well and in chronological order save for under issues/controversies. I don't know if this is intentional. I sorted for virgin birth and 'issue' pick up reflects out of date.

**Comment by DurHHHI** [comment]
[Now dealt with at #149 , ignore here ]

@peterwebster Same issue (perhaps meant to be reflected this way) when working within annotations - see below example for Winnington Ingram.

![chronological sort persons](https://user-images.githubusercontent.com/32575577/42330632-7e17fb48-806b-11e8-94cd-21e681d567ad.JPG)

**Comment by peterwebster** [comment]
Assigning to @nomoregrapes re the sorting of results for certain issues/controversies. How are these currently sorted?

**Comment by nomoregrapes** [comment]
Yep, I'll be able to work on this.

* [Winnington Ingram needing mentions ordered](http://10.245.28.108:3000/people/person166)
* [results with unordered topics](http://10.245.28.108:3000/?utf8=%E2%9C%93&search_field=all_fields&q=virgin+birth) (might be trickier to fix)

**Comment by nomoregrapes** [comment]
Yep, I can work on this.

* [Ingram](http://10.245.28.108:3000/people/person166) needing mentions ordered
* [virgin birth results](http://10.245.28.108:3000/?utf8=%E2%9C%93&search_field=all_fields&q=virgin+birth) with topics unordered

**Comment by nomoregrapes** [comment]
I've now sorted both types of ordering.

For front/back matter, they have to get listed after dated entries. As these lists are short and not full search results (they're just journal mentions), I think that should look okay. [example](http://10.245.28.108:3000/references/ref8)

**Comment by peterwebster** [comment]
Could @KPalmerHeathman @DurHHHI have a look at the sorting of search results, trying out with a variety of search criteria? Hopefully we can knock this one on the head soon.

**Comment by KPalmerHeathman** [comment]
In search results I have journal entries displayed in chronological order, but they are still displaying as date code, rather than 'Journal entry for....'
![image](https://user-images.githubusercontent.com/32575539/43828360-30feca28-9af4-11e8-839a-d3782c39fc37.png)

**Comment by KPalmerHeathman** [comment]
same with 'person807' etc in search results for Persons. This is in Firefox.
![image](https://user-images.githubusercontent.com/32575539/43828411-57aae350-9af4-11e8-80ce-6bd75d9488a6.png)

**Comment by KPalmerHeathman** [comment]
Journal mentions displaying correctly in chronological order on a person page though, as in Winnington-Ingram above.

**Comment by peterwebster** [comment]
*ping* @nomoregrapes

**Comment by peterwebster** [comment]
This error seems to be a product of development process, and is fixed on restart of the system, so assigning to me to sign off before soft launch. @KPalmerHeathman has a knack of looking at the system just as @nomoregrapes has partly broken it..

**Comment by peterwebster** [comment]
Having spent some time around the GUI, happy to close this one now.
