### ISSUE TITLE
Table-like formatting in journals

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#7]
In XML there is the possibility of rendering certain things as tables. Although inelegant, it may be that there are table-like things in the journals for which we should consider this. Could either @dpl0js (or Katie or Hilary as they come across them) let me know of examples that I may consider?

**Comment by peterwebster** [comment]
Initial test from DOCX to XML (OxGarage) suggests that the table formatting persists; need to check how the TEI handles these and what transformation necessary in Stage 2 script.

**Comment by dpl0js** [comment]
Would these examples from vol. 15 do?  Please let me know if I have misunderstood the request.
[Tables.docx](https://github.com/peterwebster/henson/files/1357181/Tables.docx)

**Comment by peterwebster** [comment]
Thanks @dpl0js this is what I needed. Some of these are lists, and others more like tables,  which (when convered from Word) will come out like:

1. Dr J.E. Sinclair 1 Queen Anne's Gate
2. W.J Roberts Foreign Office Downing Street

or

Offertories £675
Seat Rents £300
Grant to Clergy Fund £75
£1610

That is, unless the keyers either make them a list or put them in a table, they simply lose their structure and come out as lines of text. Should we consider amending the transcription guidelines (and thus have Katie and Hilary redo existing ones)?

**Comment by dpl0js** [comment]
Okay, so the lists\tables have to be hard by the margins, not centred, as HHH often does? So not actually in table form but not in continuous text form either?

**Comment by peterwebster** [comment]
Reopening this issue as the discussion continues. 

When the developer is in place, (s)he may well be able to centre tables and lists in the view the user sees, but for that to be possible, they must be marked up as either table or list in the XML. If all the transcribers do is use tabs to space the columns and Format-Paragraph to indent, then it is lost in the conversion from Word to XML and what emerges is just a paragraph for each row, as above.

So, I think we should probably amend the transcription guidelines such that they use the list option in Word for lists, and the table for anything with three or more columns, and Katie and Hilary do the same as they review existing transcriptions. @dpl0js

**Comment by dpl0js** [comment]
I'm with you now; so, for example,

Offertories:-
At 8 a.m.              1.1.6
"  11   "	                 2.16.
"   4 p.m.              3.7.
"   7    "                 2.11.   
                              poundsign9.15.6

would have to be numbered thus:

Offertories:-
1. At 8 a.m.              1.1.6
2.  "  11   "	           2.16.
3.  "   4 p.m.                3.7.
4.  "   7    "                  2.11.   
                              poundsign9.15.6

**Comment by peterwebster** [comment]
Yes, if numbered lists are what is needed; Word also supports unnumbered lists:

- At 8 a.m. 1.1.6
- " 11 " 2.16.
- " 4 p.m. 3.7.
- " 7 " 2.11.
- poundsign9.15.6

**Comment by dpl0js** [comment]
Ah, the bullet point.  Thank you, and sorry for being slow to catch on.

**Comment by peterwebster** [comment]
Or, if you're concerned about how the ditto marks look, then it goes in a table so the amounts always line up beneath each other in the second column. That way, the total figure is also aligned @dpl0js 

| At 8 am | 1.1.6 |
|  " 11 | 2.16 |
|   | £9.15.6 |

**Comment by peterwebster** [comment]
Or, if you're concerned about how the ditto marks look, then it goes in a table so the amounts always line up beneath each other in the second column. That way, the total figure is also aligned @dpl0js

In the XML, this involves <table, <row and <cell tags, but looks something like this to the user:
![20171006_113527xx](https://user-images.githubusercontent.com/5520710/31274534-3b86d198-aa8b-11e7-8247-48d0a38baa35.jpg)

**Comment by dpl0js** [comment]
[At 8 a.docx](https://github.com/peterwebster/henson/files/1362427/At.8.a.docx)
In word, then, it would look as in the attached?  Where would the tags go?

**Comment by peterwebster** [comment]
They are in effect already there, in the underlying code (which is a form of XML very particular to Microsoft), and my Stage 2 process extracts that code and transforms it into a form we can use more easily. The same applies to bold, underlining, lists, tables etc.
If we were to start amending *the XML* so things are in tables/lists that were not made so in Word, then you need to start putting in the tags.

**Comment by peterwebster** [comment]
As I think we've deal with this in discussion, closing this ticket now.

**Comment by dpl0js** [comment]
@peterwebster Fine with me.
