### ISSUE TITLE
Implement HTML formatting in annotation popups

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#70]
Some annotations have <i and <b and other HTML formatting. This needs recognising in the stylesheet.

See also #64 ( what to do about e acute)

**Comment by nomoregrapes** [comment]
Done, as demonstrated by italics in Davis narrative on [00-11-05-11-08](http://10.245.28.108:3000/journals/00-11-05-11-08)
![annotation-formatted](https://user-images.githubusercontent.com/1181194/40968547-b8308ee2-68ad-11e8-867b-6248128a4bb8.png)

The html tags are also considered on [individual annotation pages](http://10.245.28.108:3000/people/person41).
Bold should take place too, I don't have an example.

**Comment by peterwebster** [comment]
Could @KPalmerHeathman and @DurHHHI take a look at a few of these and feed back?

**Comment by DurHHHI** [comment]
Looks good - checked across several entries.

**Comment by peterwebster** [comment]
OK, closing this one now: thanks all.
