### ISSUE TITLE
Search result list: formatting

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#71]
In list of search result, remove filename for results in journal pages.

Format results in Notes just as Note 48.

Results from references: remove the ID

Results for organisations should print the organisation name.

**Comment by peterwebster** [comment]
Also, remove whitespace after person name and any others.

**Comment by peterwebster** [comment]
For names, if there is a Title, print: Surname, Title FirstName

Bloggs, Sir Frederick

**Comment by nomoregrapes** [comment]
All the above comments have been done as requested.

I've kept the journal date format as "7 Oct 1900" as it lines up nicely in results. However, I'll stick to that format or the agreed "Sun 7 October 1900" throughout the website. There shouldn't be a need for any other date formats.

![search-results](https://user-images.githubusercontent.com/1181194/40493035-c76cfa78-5f69-11e8-8e2e-054de539679b.png)

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI could you have a root around and see how all these changes are looking?

**Comment by peterwebster** [comment]
Hi @nomoregrapes there still seems to be an issue with the file name display
![image](https://user-images.githubusercontent.com/5520710/41103580-5cd5d524-6a61-11e8-8f97-a6fbef7513e4.png)

**Comment by peterwebster** [comment]
Also in the screenshot above, we should print the Person Name, not person50

**Comment by peterwebster** [comment]
We still have orgnames printing rather than the full name

![image](https://user-images.githubusercontent.com/5520710/41103796-e2b8edf2-6a61-11e8-9d0f-3d7a283f1b9e.png)

**Comment by peterwebster** [comment]
Also the notes @nomoregrapes : I wonder whether these changes got committed?

![image](https://user-images.githubusercontent.com/5520710/41103970-49c5d280-6a62-11e8-90b1-284b8d7a704b.png)

**Comment by nomoregrapes** [comment]
I was noticing it kept ignoring the special function to render our data types. Turns out an unrelated minor bug can upset it. Now fixed.

**Comment by peterwebster** [comment]
![image](https://user-images.githubusercontent.com/5520710/41662659-7e382d10-7499-11e8-8549-bdf567dd6443.png)

**Comment by peterwebster** [comment]
This looks good, many thanks @nomoregrapes . Closing the ticket now.
