### ISSUE TITLE
Implement OR operator in search

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#73]

**Comment by nomoregrapes** [comment]
The default operator to join words is set as "OR". So adding in "OR" will not make any difference.
Using the "AND" operator will make a difference, as we expected/observed.

**Comment by peterwebster** [comment]
Reopenting this as a note to me to include a note to these operators in whatever 'search tips' we might consider providing.

**Comment by peterwebster** [comment]
See #97
