### ISSUE TITLE
Search filter options

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#74]
In pick list for main search, enable:

- 
- Places
- Publications [references]
- Sermons/speeches  [ie. events]

**Comment by peterwebster** [comment]
For publications (reference) search, include:

Author/Editor
Title
Subtitle
VolumeDetails
Periodical

**Comment by nomoregrapes** [comment]
For drop down list on main search box.

**Comment by nomoregrapes** [comment]
This is how the search(dropdown) options now stand...
![search-options](https://user-images.githubusercontent.com/1181194/41282464-07cf22d2-6e2c-11e8-9699-4ee37b87c70a.png)

We've dropped the word "only", and added the remaining types (excluding Notes and Topics).
"Everything" is at the top so it's default (and tempts you to see what options there are), followed by the 3 primary types that have links on the right.

A final option will be added (as per #83) for "Find on this page".

**Comment by DurHHHI** [comment]
Like the look - and clear search default to 'everything'. We'll see if sermons & speeches stays!

**Comment by peterwebster** [comment]
@nomoregrapes this is looking good now, many thanks.

As things have changed in relation to the Publications (over at #101 ) could you confirm which fields are being included in the Publications search?

**Comment by peterwebster** [comment]
In publications search, include Editor/Translator

**Comment by nomoregrapes** [comment]
For publications, the fields being searched are now
* title
* subtitle
* volume details
* periodical details
* translator/editor

**Comment by peterwebster** [comment]
We'll have to test this once the most up-to-date TSV is ingested.

**Comment by peterwebster** [comment]
Could @DurHHHI test this out? See if the search finds publications by their editor, subtitle, details of volumes in which an item is contained, periodical titles.

**Comment by DurHHHI** [comment]
@peterwebster 
Yes, this seems to be working!
