### ISSUE TITLE
Wordpress: date picker on home page

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#76]
Implement same date look up as in #67

**Comment by nomoregrapes** [comment]
Done. Viewable [online](http://community.dur.ac.uk/gregory.j.marler/wordpress/)

**Comment by peterwebster** [comment]
Tested this with @durhhi today, which throws a Blacklight exception; perhaps it isn't plumbed in yet.

**Comment by nomoregrapes** [comment]
I had downgraded/broken the repository site. Noticed someone was using the site, and so I reverted my changes.

I'll probably keep the site working for the rest of the day. Tomorrow I may have to break it again.

**Comment by peterwebster** [comment]
Break away, as I can't test the WP-Samvera link anyway from here @nomoregrapes
