### ISSUE TITLE
Wordpress: menu widget layout

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#77]
Move Henson and journals to left

Create new menu: Essays

Project blog on the right.

**Comment by nomoregrapes** [comment]
3 widget columns now at the bottom of the [wordpress pages](http://community.dur.ac.uk/gregory.j.marler/wordpress/).

The pages in them can always be changed later.

**Comment by peterwebster** [comment]
Reassigning to me now, to marshal the production of the essays.
