### ISSUE TITLE
Wordpress: navigation bar

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#78]
Wordpress top navigation to match that in repository

**Comment by peterwebster** [comment]
Eventually, nav bar will need link to something called Guidance/Help for Readers, which directs some page or pages in WP.

**Comment by nomoregrapes** [comment]
[wordpress](http://community.dur.ac.uk/gregory.j.marler/wordpress/) top bars now make a fairly good match with the repository.

**Comment by peterwebster** [comment]
Hi @nomoregrapes : I suggest I feed back on all the various changes to the WP homepage in one go, across several tickets.  Just for now though, there's a spacing issue with the search box (Firefox, laptop monitor)

![image](https://user-images.githubusercontent.com/5520710/40724519-21e587fa-6419-11e8-96bd-2cf08fe1f5ab.png)

**Comment by nomoregrapes** [comment]
There's a meeting tomorrow about the structure/content of the Wordpress part. I'm not expecting much change for me to do, but I'll add tickets here if that is the case.

That Firefox positioning issue should be fixed now.
