### ISSUE TITLE
Formatting of unordered lists

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#80]
Where there are unordered lists (<ul ), stylesheet should *not* supply bullet points.

**Comment by nomoregrapes** [comment]
This is done.

As an example http://10.245.28.108:3000/journals/03-05-14 shows an ordered list (numbering provided by the style) followed by an ordered style (no numbering/bullets, which may be used when Henson used greek letters numbering).
![lists](https://user-images.githubusercontent.com/1181194/40483402-c7bedd9e-5f4f-11e8-8efa-4827595668cb.png)

**Comment by peterwebster** [comment]
Thanks @nomoregrapes : could @DurHHHI and @KPalmerHeathman take a look at some examples and see if we may now close this ticket?
