### ISSUE TITLE
Annotation pop up positiongin

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#81]
Avoid annotations being positioned such that they sit partly outside the main text window.

**Comment by nomoregrapes** [comment]
Done.
Would be good to check this works for other people too. [example](http://10.245.28.108:3000/journals/00-11-11)
![annotation-rightside](https://user-images.githubusercontent.com/1181194/40980397-33d1d5a2-68d0-11e8-8f2f-2dc2613e1d64.png)

**Comment by peterwebster** [comment]
@KPalmerHeathman as you have a Windows machine, could you take a look at this and feed back?

**Comment by KPalmerHeathman** [comment]
Are they meant to be positioned as in the Frank Capon example or no?

**Comment by peterwebster** [comment]
![image](https://user-images.githubusercontent.com/5520710/41102934-e23bd602-6a5f-11e8-84a5-53d18c286fc4.png)

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI and I discussed this the other day, and I'm now slightly uncertain what the issue was that we were trying to solve in the first place.
@nomoregrapes in the example above, I think the horizontal positioning is fine; I don't mind it sitting over the edge of the blue border. Presumably  if a user with a lower screen resolution sees this, the box will be pushed further to the left?

There is one other tweak which we thought was needed. In the Capon example, the icon next to his name is over to the left, but the box appears right. I guess that this is because the positioning is in relation to the opening <persName tag. If so, it should probably be in relation to the closing one, so this annoation in fact appears at the same vertical position, but over to the left.

**Comment by DurHHHI** [comment]
@peterwebster, yes, I believe Katie was only commenting on the 'tweak' - where, in this example, Frank Capon's annotation box is so far away from his closing persname tag. That said, it doesn't look awful if a difficult fix - the content can still be easily read.

**Comment by peterwebster** [comment]
@nomoregrapes I should say that this tweak is not a massive priority.

**Comment by nomoregrapes** [comment]
What we were trying to fix: in cases where the marked name was close to the right, the annotation would popup spilling out to the right of the screen so you couldn't read it.

The fix involves some maths and calculating positions (which is unusual to do in HTML/CSS). This edge case is due to the name wrapping round onto a second line. I'm not sure if it's possible to be aware of that, but I might have a look if I get to this (low priority). I think there are some more annotation style changes to come first anyway.

**Comment by peterwebster** [comment]
@nomoregrapes see new labels: critical / medium priority / low priority
Tickets will no doubt get promoted and demoted as we go along, but you get the idea

**Comment by peterwebster** [comment]
Given that there is some maths to do here, and not a usual HTML/CSS use, closing this for now. For reopening if it is raised.
