### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#82]
Remove alternating shading from tables.

Experiment with lightening the border as well.

**Comment by nomoregrapes** [comment]
I have removed the background shading on alternate rows. I also removed the outside line of the table.

It looks considerably fainter without changing the shade of grey. I think the next step would be if we remove the lines altogether, and the table will just keep the things lined up.

Some examples
http://10.245.28.108:3000/journals/00-10-07
![table1](https://user-images.githubusercontent.com/1181194/40482353-6b88eff4-5f4c-11e8-865d-840d3c53e3a4.png)



http://10.245.28.108:3000/journals/01-02-18-03-07
![table2](https://user-images.githubusercontent.com/1181194/40482356-6f585304-5f4c-11e8-9548-23a9bb6995a3.png)

**Comment by peterwebster** [comment]
Hi @nomoregrapes : let's see what the team think of it as it stands: snap reactions @KPalmerHeathman @DurHHHI ?

**Comment by KPalmerHeathman** [comment]
I quite like retaining the lines - as discussed on Tues, we're not creating a facsimile, and the lines will be easier on the eye, especially in the money tables.

**Comment by DurHHHI** [comment]
I support keeping the lines too (as in the above example) - I think it does read easier, especially in the longer tables.

**Comment by peterwebster** [comment]
OK, I concur. Closing ticket now @DurHHHI @KPalmerHeathman @nomoregrapes
