### ISSUE TITLE
Find on this page

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#83]
In search drop-down, add 'Just this page', probably last.

If possible, have this appear only on journal pages.

**Comment by nomoregrapes** [comment]
This was a handy little task for me at the end of the day.
![journal_highlight](https://user-images.githubusercontent.com/1181194/40987080-a6619738-68df-11e8-80dd-f7211e1753f5.png)
Click the magnifying glass to open the extra search field. Finds/highlights as you type. Click button again to remove highlighting & the search box.

Currently on all pages, but it only searches within the "primary content" (the journal entry, or narrative when viewing an annotation)

Should I have excessive time left, I might revisit this to see if it can highlight the search term that made you find the journal.

**Comment by peterwebster** [comment]
Tested this today on Hilary's machine: Chrome on a Mac. The box opens but it doesn't find/highlight, or respond to Return.  Same on Windows desktop with Firefox.

![image](https://user-images.githubusercontent.com/5520710/41104290-eaa0fb6c-6a62-11e8-99e0-9d8702cfb997.png)

**Comment by peterwebster** [comment]
Suggest that 'On This Page' is made an option in the general search box, and we lose the purple second box entirely. 

What does @DurHHHI think?

**Comment by DurHHHI** [comment]
@peterwebster and @nomoregrapes - yes, support :)

**Comment by nomoregrapes** [comment]
It actually works now.
Moved it to be an option in the drop down.
Changed the highlight colour to a light-blue, as this relates to the search button and is more distinct from annotation highlights. In my screenshot, my cursor is hovering on the "three lectures" annotation, so you can compare with that colour.
![journal-findonpage](https://user-images.githubusercontent.com/1181194/41410594-d637a08a-6fd1-11e8-8fde-8de22e0f6a2b.png)

**Comment by peterwebster** [comment]
Tested this just now with @DurHHHI , looks good. Closing ticket.
