### ISSUE TITLE
Vols 14 and 15: XML retroprocessing to move punctuation within tags

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#84]
Not for Henson, Henson: or Henson.

For Henson's, and similar, write script to move the apostrophe s within the tag.

**Comment by peterwebster** [comment]
Hi @KPalmerHeathman @DurHHHI : I'm now nearly finished with this 

As my script looks for `</persName>'s` there is one instance where it has missed its target, due to an intervening <hi tag. This will need to be altered by hand. V15, p.401.

	` <hi rend="i b u"></hi><persName id="664"><hi rend="i b u">M</hi><hi rend="i bold superscript underline">rs</hi><hi rend="i b u"> Prothero</hi></persName><HERE'S WHAT NEEDS TO BE CORRECTED ->>>><hi rend="i b u">'s brother</hi> <persName id="665"><hi rend="i b u">D</hi><hi rend="i bold superscript underline">r</hi><hi rend="i b u"> Butcher</hi></persName><hi rend="i b u"> talked to me for some while. ........
	          <p>
<hi rend="b">[402]</hi>`

**Comment by peterwebster** [comment]
Incidentally, I've found no instances at all of Jones' or Williams' or Perkins' : does HHH just not use that style?  @DurHHHI @KPalmerHeathman

**Comment by peterwebster** [comment]
Also, in Henson Master Data > Stage 6 you'll find a file called cat_for_checking.xml. This is the whole of volume 15 wrapped up in one file, with this script run. Could you have a root around and see if all is it should be @KPalmerHeathman @DurHHHI 
Not urgent: this week or next for this.

**Comment by DurHHHI** [comment]
thanks @peterwebster - have corrected the tag on pg. 401, V15

**Comment by peterwebster** [comment]
Thanks @DurHHHI : do let me know when you've had a chance to look at the file for the whole of 15.

**Comment by DurHHHI** [comment]
@peterwebster yes, reminder to query this with you on Skype today

**Comment by peterwebster** [comment]
@DurHHHI with apologies for the bombardment of things, could you take 10 minutes today just to check this. I think it's probably OK, but it would be good to close it down.

**Comment by DurHHHI** [comment]
@peterwebster I've been looking around and have not noticed an issue since these changes have taken place. Might be a slight issue with automatic ids in XML 17 - easily fixed manually when Katie and I eventually return to work through those files again, but possibly something to note moving forward for future volumes.

**Comment by peterwebster** [comment]
Hi @DurHHHI I'm not sure what you mean by automatic IDs: what's the issue?

**Comment by DurHHHI** [comment]
@peterwebster I knew it would be the correct terminology, but what I meant was the IDs that are included in the 'replace' google sheet.

**Comment by peterwebster** [comment]
Hi @DurHHHI there's an opportunity to revise the numbers in the script that does that automatic markup before I run it for each new volume. If any of those IDs are wrong, that can be addressed in this deduplication script that I run just before a volume goes live. I don't think there should be any systemic problems there, unless I'm missing something?

**Comment by DurHHHI** [comment]
ok thanks @peterwebster  - ok to close?
