### ISSUE TITLE
Volumes 14/15: alter nesting of elements and <hi

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#85]
Develop script to rewrite nesting of <hi and <persName to avoid the underlining of the icon.

ie. <persName <hi Bloggs </hi </persName

NOT

<hi <persName Blogss </persName <.hi

**Comment by peterwebster** [comment]
FYI: @KPalmerHeathman @DurHHHI this missed the boat in the scramble of the last few weeks, and so now goes onto the someday-maybe pile, in relation to 14 and 15 at least. It can, of course, be amended manually in the interface, but life may be too short for that.

@nomoregrapes could you confirm that, as Katie and Hilary observe this revised nesting practice from now on, the existing stylesheet will display correctly? It won't come on stream until you're packed up and gone, so we should test it before you go.

**Comment by nomoregrapes** [comment]
Yes, that should work as I think you want it to.
An example in [00-11-15-11-21](http://10.245.28.108:3000/journals/00-11-15-11-21) shows Harry Ramsey double-underlined, but not the icon.
![journal-underline-person](https://user-images.githubusercontent.com/1181194/42871103-6c7c3bb4-8a71-11e8-9af2-fb42c856f1b9.png)


` <persName xml:id="95"><hi rend="doubleunderline">Harry Ramsey</hi></persName> stayed in `

**Comment by peterwebster** [comment]
OK, many thanks @nomoregrapes , you're done with this one.

@KPalmerHeathman @DurHHHI : for volumes 14 and 15, where there are instances of this, it will be a case of amending them in the editing interface, if you have time and inclination. I should be able to generate a list of which files it occurs in.

In XML for 16 that is already marked up, you'd need to review the files and reverse the ordering of the markup. Again, I should be able to flag up where there are instances of this. (Ticket at #155 )

And from now on, mark up <persName <hi  ..... </hi  </persName

**Comment by peterwebster** [comment]
As per email, this is a manual fix in 14 and 15. Once you're happy that you know what to do from now on, close this ticket @DurHHHI @KPalmerHeathman

**Comment by peterwebster** [comment]
@DurHHHI what does the H&K return label mean?

**Comment by DurHHHI** [comment]
@peterwebster I can delete this label if it messes with your organisation Peter - apologies if so. Just an easy way for me to see what items need to be checked and/or require a manual fix once editing with the website is possible.

**Comment by peterwebster** [comment]
@DurHHHI not a problem, just interested,,

**Comment by DurHHHI** [comment]
Hi @peterwebster @KPalmerHeathman has worked through this with the 14/15 entries that she has manually made public one by one. We've noted and will catch any remaining that might be lurking since the entire V14/15 has been made public when we move in and out of the repository. I think safe to close and we'll address as/when/if we see them?
