### ISSUE TITLE
Cross Refs: needs ingest to fixed

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#87]
This is now done (required some work I didn't expect).

When multiple cross references are listed, should they be separated by a semi-colon? This would be help as the display of names uses a comma.

Example, the "See also" on http://10.245.28.108:3000/people/person76
On a person page...
![see-also](https://user-images.githubusercontent.com/1181194/40481111-479797e8-5f48-11e8-8692-14428e7cc913.png)
And when the person pops up on a journal...
![cross-ref-popup](https://user-images.githubusercontent.com/1181194/40481114-4a886dec-5f48-11e8-9e23-bdc9511e14e3.png)

**Comment by peterwebster** [comment]
For me, I like the semi-colon @nomoregrapes 
Could @DurHHHI and @KPalmerHeathman do some browsing and look for some annotations with cross references, and see how they're working?

**Comment by KPalmerHeathman** [comment]
I like the semi-colon too. Will have a look at some more!

**Comment by nomoregrapes** [comment]
I should also make clear, the "See also" could be a mix of data types (people, orgs, etc..). There's no icon or distinction in the list.
If you click something in that list, you get to it's page (e.g. the page of a person) which has an obvious icon, the narrative, journals mentions, and it's own cross refs.

**Comment by peterwebster** [comment]
@nomoregrapes thanks for the note about the mix of types; I don't think we need any icon or other distinction, it looks good as it is.

**Comment by KPalmerHeathman** [comment]
I think icons will look cluttered in this context - it's self-explanatory as it is.

**Comment by peterwebster** [comment]
@nomoregrapes just rounding this up: let's confirm that the semi-colon is good, and that we don't need icons here. Once you've seen this, could you close the ticket?

**Comment by peterwebster** [comment]
All done,, closing ticket
