### ISSUE TITLE
Forward slash symbol

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#9]
How should we treat this?

A miserable wet day.  I spent most part of the morning in writing an Advent letter to the Hospital congregation.  / In the afternoon I went to town, and attended Evensong at Westminster Abbey.  The singing was most beautiful.  After service I called on Armitage Robinson.  He shewed me over the house which is very large, rambling, & costly to keep up.  He said S. Margaret’s was worth poundsign500 per annum.  He was very eager that my arrival should be hastened: & alarmed me by the tidings that all his curates were leaving, having been preferred to livings.  The music & choir at S. Margaret’s cost poundsign1200 yearly.  This alarms me much.  On my return to Ilford, I wrote to Mr John Talbot, asking him whether he could by any means hasten the issue of the official announcement.  I received an earnest letter from Jimmie Adderley begging me to persuade Lord S. to appoint him to this Hospital.

The forward slash here is in red crayon. Should as we be treating it as a [symbol] or as a bold underline? What does it mean?

**Comment by peterwebster** [comment]
The options are, I think, @dpl0js ,

- to treat this as a symbol (and so insert [symbol] ) or
-  (as it is often in colour) leave it in place but with bold & underlining?

As with the other symbols, it isn't clear what it indicates, and it perhaps does not warrant being treated as a distinct thing.

**Comment by dpl0js** [comment]
@peterwebster I think the latter, that is, a different form of highlighting the text later on.  

On p. 24 of the transcription style sheet, point 9, I suggested using italics.  But this would be unclear.  So yes, use bold.  

But do we need to underline it as well?

**Comment by peterwebster** [comment]
@dpl0js  Consulting the transcription guidelines (I'd forgotten about this section), it would seem that italicisation would be fine. If you agree @KPalmerHeathman and @DurHHHI do please close the ticket.
