### ISSUE TITLE
Wordpress wording changes

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#91]
Decisions made this morning regarding the [wordpress frontend](http://community.dur.ac.uk/gregory.j.marler/wordpress/)

* Don't show a title (Welcome) on the homepage
* Add logos to footer for: AHRC, Durham Uni, Durham Cathedral
* Top bar, change `Everything` to `Whole journals`
* Sidebar, second box rename as `Search project commentaries (exc journals)`
* Sidebar, rename "From the repository" to `Selection from the journals` and drop subtitles (have a single list)

**Comment by peterwebster** [comment]
@nomoregrapes this all seems sensible. One point:

"Rename as Search project commentaries..."   - the "excl. journals" is redundant, since the positioning below 'Search the Journals" makes it clear, I think.

**Comment by nomoregrapes** [comment]
All these are done, and I think covered by other tickets.
