### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nomoregrapes** [peterwebster/henson#92]
Look at creating a different logo. Could use "H Henson" signature or his family seal.

@KPalmerHeathman to send some signatures & the seal.
@nomoregrapes to use them to make some possible logos for consideration.

**Comment by nomoregrapes** [comment]
Between tasks & when waiting for ingests, I've made a few possibilities.
Trying to use Henson's signature, but not wanting to make it too wide, the title is as much the logo as the log itself. One of the lone "H" logos is probably best.

See images below(full page to show how it works in context), click to view full size.

**Purple H**
![logo_purple_h](https://user-images.githubusercontent.com/1181194/41464864-b55e996e-7093-11e8-8ff1-42efe5cd4735.png)

**Purple H2**
![logo_purple_h2](https://user-images.githubusercontent.com/1181194/41464867-b7733066-7093-11e8-8e19-f2d89b41a008.png)

**White H**
![logo_white_h](https://user-images.githubusercontent.com/1181194/41464869-b92e34f0-7093-11e8-8350-aa468aecb457.png)

**White HHH (small)**
![logo_white_hhh_small](https://user-images.githubusercontent.com/1181194/41464875-bdc1b302-7093-11e8-9e6f-8377bb2ab998.png)

**Hat with H**
![logo_white_hat](https://user-images.githubusercontent.com/1181194/41464872-bb0a3c42-7093-11e8-9965-a23cbe90dc0a.png)

**Comment by nomoregrapes** [comment]
I'm not chasing this up.
If / when a logo is agreed, a note to myself that I'll need to change it in multiple places:
 - [ ] Wordpress termplate
 - [ ] Repository template
 - [ ] Repository error pages (404 and 503)

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI @dpl0js @williamsonphilip 
May I ask for first impressions/preferences for these several logo choices that Gregory has produced for us?

**Comment by dpl0js** [comment]
@dpl0js - Thanks Gregory, I like white HHH the most.

**Comment by DurHHHI** [comment]
Thanks @nomoregrapes for the logo support! I support any of the above options - the white HHH is a good one - save the bishop's hat. This is only because the digitised journals start in 1900, well before Henson became bishop.

**Comment by peterwebster** [comment]
From @williamsonphilip 

"Not, I think the mitre.  Aside from the good comment below, I rather doubt that Henson would have favoured such anglo-catholic headgear, though he may have needed to wear it sometimes (1937 coronation?).

I favour simplicity, so of these the white single H.  But to have a radical thought; is a logo necessary? The webpage design - particularly the top  banner of The Henson Journals  -  is distinctive in itself.  No one is going to mistake this site for any other site!

**Comment by KPalmerHeathman** [comment]
I like the white H.H.H. best.

**Comment by peterwebster** [comment]
@nomoregrapes let's implement the white HHH and live with it for a while (but not urgently)

**Comment by nomoregrapes** [comment]
Done.

**Comment by peterwebster** [comment]
Many thanks @nomoregrapes . I'm now going to say that this is closed, until such a time as anyone raises an issue.

**Comment by peterwebster** [comment]
@dpl0js raises the logo, on two grounds: firstly that the current 'three Hs' design is "spindly, quite unlike H’s character", and also on the ground that it may not be necessary at all. 

Looking back at this ticket, I see that the same second point was raised earlier. I would, however, want to hold out for a logo of some description for the sake of variety in the design, which is already relatively plain.

However, it may be that this particular logo is unacceptable. Could I ask everyone to review the versions that Gregory created (given above) and see whether any one of the others is preferable on reflection.
@williamsonphilip @KPalmerHeathman @DurHHHI

**Comment by DurHHHI** [comment]
@peterwebster Apologies if I'm out in left field here, but I do like the logo. Out of the options Gregory put together, the 'H. H. H.', to me, is most distinctive and pulls directly from the journals. 

The original image Gregory played with of the cathedral backdrop was also quite nice (though less easy to spot in the original purple) and, given the revised timeline, could support as a clerical symbol, fitting both Henson's time at Westminster, Hereford, and Durham. 

Before he was signing as 'H. H. Hereford' or 'Herbert Dunelm', while he utilised the 'H. H. H.' we also see 'H. Hensley Henson' (screenshot example attached). For a logo option, the 'H. H. H.' is short and concise where 'H. Hensley Henson', I imagine, would crowd the logo area significantly.

<img width="330" alt="screen shot 2018-10-01 at 10 01 48 am" src="https://user-images.githubusercontent.com/32575577/46279797-0f5cb180-c562-11e8-9665-12fcdd03739f.png">

**Comment by KPalmerHeathman** [comment]
Not sure I see the issue with the current logo being unlike Henson's writing, as it is actually Henson's writing, cut directly from the journal page images.  I also think the current one is quite simple and elegant, and agree with Peter on the point of variety.

**Comment by peterwebster** [comment]
After email exchanges today, @nomoregrapes to investigate using the Herbert Dunelm signature form as an alternative logo.

**Comment by peterwebster** [comment]
Superseded now by #217
