### ISSUE TITLE
Testing ingest of XML in final TEI-compatible markup

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#93]
Hi @nomoregrapes : as discussed just now, there's a handful of files on OneDrive, Stage 6 Final > Test-040618
If these ingest OK, I'll let you have amended XML for the whole of volumes 14 and 15.

To recap, the things that are different are:

(i) element ID attributes are expressed as

>  xml:id="123"

(ii) attribute values for <hi are written out in full
(iii) <event within <listEvent
(iv) <teiHeader inserted

**Comment by peterwebster** [comment]
@nomoregrapes despite this, it might be prudent to adjust your stylesheet to allow for both sets of <hi attributes (i as well as italic), as I'm not 100% confident that I've been able to deal with all the possible combinations, so there may be some examples of i, b, u that slip through. Less than elegant in coding terms, but prudent under the circumstances.

**Comment by nomoregrapes** [comment]
(i) is done.
Other work should be done, will test with next ingest of vol14.

**Comment by nomoregrapes** [comment]
@peterwebster the new TEI doesn't work as XML is supposed to have only one root node. We need to wrap the head in a `<TEI xmlns="http://www.tei-c.org/ns/1.0">` and that should be TEI compliant but also allow me to access the body tag which is at the same level.

Files would look like...
```
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="styles.xsl" ?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
<teiHeader> standard tags/title.... </teiHeader>
<body>Actual content <p>markup</p> etc...</body>
</TEI>
```

**Comment by nomoregrapes** [comment]
I've put a really bad hack in for now so it works for Julia & the team tomorrow. Volume 14 is in, but we should reingest a version with `<tei>` tags.

**Comment by peterwebster** [comment]
Schoolboy error, apologies: this got overlooked. @nomoregrapes 

Refining your example, the hierarchy needs to be TEI > text > body tags, as per this.  Fixing 14 now

```
<TEI version="3.3.0" xmlns="http://www.tei-c.org/ns/1.0">
<teiHeader>..... </teiHeader>
 <text><body>
   .....
  </body>
 </text>
</TEI>
```

**Comment by peterwebster** [comment]
Chapter and verse here  http://en.guidelines.tei-c.org/html/ref-TEI.html  @nomoregrapes

**Comment by peterwebster** [comment]
OK @nomoregrapes : fixed XML for volume 14 now in OneDrive, Master Data/Stage6/14v2

Hopefully that will work now.

**Comment by peterwebster** [comment]
@nomoregrapes XML for volume 15 now also in OneDrive, MasterData>Stage6>15

**Comment by nomoregrapes** [comment]
@peterwebster I'm not seeing the fixed 14, or XML for 15 on OneDrive.
![onedrive](https://user-images.githubusercontent.com/1181194/41985907-85f67b9a-7a2c-11e8-81c1-f1f445e1eb03.png)

**Comment by peterwebster** [comment]
@nomoregrapes it should be there...?

![image](https://user-images.githubusercontent.com/5520710/42019457-2138effe-7aad-11e8-820e-5ba422bdab17.png)

**Comment by nomoregrapes** [comment]
Ah, found it. Don't know why it wasn't showing yesterday.

**Comment by nomoregrapes** [comment]
TEI-compatible markup tested and is fine.
