### ISSUE TITLE
Testing of examples of different <div types

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#94]
Hi @KPalmerHeathman @DurHHHI 

It occurs to me that we (or at least I) haven't seen examples of all three of our different types of <div  (letter, quote, verse). I think there are certainly letters in 14 and 15, possibly quotes, possibly not verse (since we may have defined that in response to finding one in 16.)

Could you (not urgently, but perhaps within a week or so):
(i) have a look in Gregory's GUI for examples of each in 14 and 15
(ii) if they exist, do they look OK?
(iii) if they don't exist, let me know, as we'll have to invent some to test before @nomoregrapes leaves us.

**Comment by DurHHHI** [comment]
@peterwebster - all div types exist in 14 & 15 - hoping it helps, here are some screenshot examples:

Div letter (Routledge ex) :

![div type letter ex](https://user-images.githubusercontent.com/32575577/41107665-b6d3d8ba-6a6a-11e8-8dc6-377efd278508.JPG)

Div quote :

![div type quote ex](https://user-images.githubusercontent.com/32575577/41107730-d5be4904-6a6a-11e8-8b9d-91526877be6d.JPG)

Div verse (teach me to number...) : 

![div type verse ex teach me to number](https://user-images.githubusercontent.com/32575577/41107740-dc2b1862-6a6a-11e8-92f4-23560e7deba5.JPG)

**Comment by peterwebster** [comment]
@DurHHHI note that some of these screenshots are now obsolete since the work that @nomoregrapes documents in #100  .
In the div verse example, are the three lines each in their own <p tags?

**Comment by nomoregrapes** [comment]
In that verse, the lines are in their own `<p>` tags and all wrapped in one `<div type="verse">`, which is how it should be(in my view). Spacing between Ps will be single spacing.

Is there anything in this ticket not covered by ticket 100?

**Comment by peterwebster** [comment]
Agreed that this is now wholly covered by #100 so closing this one.
