### ISSUE TITLE
Implement hiding of XML elements

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#96]
Certain elements are set to display=no - stylesheet needs to recognise this and show no icon.

**Comment by peterwebster** [comment]
This applies to organisations:
`I celebrated in <orgName id="10" display="no">S. Margaret's</orgName> at 8 a.m.: and in the Abbey after mattins.`  

Persons: 
`<persName id="100" display="no">Rashdall</persName> preached an excellent sermon`

Places (I faked this example)
`I travelled to <placeName id="10" display="no">Falconhurst</placeName> to dine &amp; sleep.`

Events (also fake)
`I went to the Workers' Institute and <event id="123" display="no">lectured about suffrage</event>`

**Comment by peterwebster** [comment]
Could @DurHHHI possibly confirm whether there are any publications that will need the same treatment?   (cc @KPalmerHeathman )

**Comment by DurHHHI** [comment]
Yes, @peterwebster - There will be some refs in publications that are currently set as do not index.

**Comment by DurHHHI** [comment]
@peterwebster Also notice currently one 'transferred do not index' in notes

**Comment by peterwebster** [comment]
@DurHHHI what's the story with the hidden footnote? If it is just the one, and there is no prospect of it ever been resurrected, it might be neatest to take it out of the XML; presumably that's only one file.

**Comment by peterwebster** [comment]
Agreed not to script footnote instances, but to do so for <ref

**Comment by peterwebster** [comment]
@DurHHHI to manually insert display="no" attribute in the XML in the one case of a hidden footnote

**Comment by DurHHHI** [comment]
@peterwebster completed manual insert

**Comment by peterwebster** [comment]
Assigning to @nomoregrapes : there are instances already of display=no in almost all semantic elements, so let's have the stylesheet cater for it in every case, as I'm sure that by the end of the project it will be used for each. <persName, <orgName, <placeName,, <event , <ref, <note

**Comment by nomoregrapes** [comment]
This is done.
No icon or mouseover-highlighting will appear.

Hidden feature: If you know it's there, you will be able to right-click on a name(etc), and then click "Inspect Element" and the person id will be in the HTML markup. This might be good for debugging, if you wonder why a name isn't highlighting.

**Comment by peterwebster** [comment]
This needs to be tested once the revised 14 and 15 are ingested.

**Comment by peterwebster** [comment]
Also, include the Inspect Element feature in user documentation.

**Comment by peterwebster** [comment]
Could @KPalmerHeathman and @DurHHHI take a look at 14 and see whether those persons/places etc who should be "hidden" in the XML are so - that is, they have no popups associated with them.

**Comment by KPalmerHeathman** [comment]
Persons hidden have no popups, but appear in search results as a clickable profile, which then gives an error message.

**Comment by peterwebster** [comment]
Could you pick out an example and put a screenshot here @KPalmerHeathman @DurHHHI 
If the person was set to index=no in the TSV, this should not be the case.

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/42097188-66055f34-7baf-11e8-8665-591f73c0bf3d.png)

**Comment by KPalmerHeathman** [comment]
![image](https://user-images.githubusercontent.com/32575539/42097229-7e106d44-7baf-11e8-85c5-89d097c9d6ea.png)

**Comment by KPalmerHeathman** [comment]
But, instead of getting an error as I did when I clicked on them this morning, I now get: 
![image](https://user-images.githubusercontent.com/32575539/42097257-9538642c-7baf-11e8-87d7-da8742f48e67.png)

**Comment by peterwebster** [comment]
OK, so there's a discussion to be had here @KPalmerHeathman @DurHHHI .

There are in fact two possible ways of dealing with a person/place/org etc. for whom we decided there would be no annotation.

1. As we imagined originally, all trace of the fact we know who they are is invisible: no popup, no index results.
2. Or, as here, the popup is not there but the bare fact of the name appears in the search (as it will necessarily in the full text search.)

So, is 2 bad? That is, is having a name in the name index without an annotation unequivocally bad?

If it is not, we perhaps want to review the names of those who are set to hide, since *the names* will be visible in this scenario.

**Comment by peterwebster** [comment]
@nomoregrapes these two examples are persons 3 (Father Hector) and 5 (Hirch)

**Comment by nomoregrapes** [comment]
I think I know the problem why Father Hector is showing.
He was ingested early on before index=no was used. Later on I did an update ingest, but it just skips index=no (it needs to proactively delete the already ingested person). **I have no fixed this, but need to repeat for other annotation data types.**
![search-hector](https://user-images.githubusercontent.com/1181194/42171955-96f89a10-7e12-11e8-8905-c4729c06ba79.png)


For 2. above... as Peter says, the journal entry will appear in the search results because "Hector" is a word that literally appears. Person 3 will not exist, so now there is only 1 result.

**Comment by nomoregrapes** [comment]
This is now fixed for all data types, and reingest of annotations done.

Father Hector and Mrs Hirst don't show up as people. If you agree, then we can close this ticket?

**Comment by peterwebster** [comment]
@DurHHHI @KPalmerHeathman could you spend some time trying to find any trace of our markup for persons/places who are hidden? There should be no popups in the text, and no search results for the actual person (except, if you search everything, you'll find the name as a free text result, which is correct)

**Comment by KPalmerHeathman** [comment]
I found a trace: the full stop is still pushed along the line as if there was an icon present, as in Inner Temple in this entry:
http://10.245.28.108:3000/journals/04-11-10

**Comment by peterwebster** [comment]
What say you, @nomoregrapes ?

**Comment by peterwebster** [comment]
@KPalmerHeathman but other than that, we're done?

**Comment by nomoregrapes** [comment]
My bad. I had an extra space after the invisible tag.

@KPalmerHeathman can now close this issue?

**Comment by peterwebster** [comment]
If @DurHHHI is in the office, we could check this and close it down? 
http://10.245.28.108:3000/journals/04-11-10   (Inner Temple)

**Comment by peterwebster** [comment]
Could @DurHHHI or @KPalmerHeathman take a look at this and see whether it is fixed,, and if so close the ticket?

**Comment by KPalmerHeathman** [comment]
Fixed, closing ticket.
