### ISSUE TITLE
Create and write a search tips/help page (Wordpress)

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#97]
To include:

AND is a real operator
OR is the default behaviour, so the operator is unnecessary.

**Comment by peterwebster** [comment]
Alerting @nomoregrapes to the presence of this new ticket.

**Comment by peterwebster** [comment]
There's now a blank WP page called help, which can be linked to as per #121

**Comment by peterwebster** [comment]
http://community.dur.ac.uk/henson.project/index.php/help/

Could @KPalmerHeathman and @DurHHHI take a look at this and let me know what you think? There will be links to the Journals etc pages once they are in their final location.

**Comment by DurHHHI** [comment]
@peterwebster The help page looks good, Peter. 👍Is it worth adding JS' email address should a reader want to contact her directly with a journal query? This might not be done on standard 'help' web pages, and ignore if so.

**Comment by peterwebster** [comment]
@DurHHHI better to use a generic email account, but is there one for the project?

**Comment by DurHHHI** [comment]
@peterwebster No, I do not believe so.

**Comment by peterwebster** [comment]
Added this now @DurHHHI
