### ISSUE TITLE
Excluding a portion of the Title field in ref.tsv from the italicisation

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#98]
After discussion with @nomoregrapes , decided that to avoid creating new fields, we should deal with this directly in the field.

@DurHHHI in ref.tsv, you'll have to have this.

`The history of the reformation of religion in Scotland, with which are included Knox's confession and the book of discipline <span class="no-italic">[1559-66]</span>`

This will mean that the title is italicised, but the date and brackets are not.

Could @nomoregrapes confirm that this will work?

**Comment by DurHHHI** [comment]
Thanks @peterwebster and @nomoregrapes - I will work to this moving forward for italicized book titles once Gregory confirms that it will work.

**Comment by peterwebster** [comment]
@DurHHHI Gregory and I just discussed this, go ahead on this basis  :-)

**Comment by nomoregrapes** [comment]
Oddly none of the references with this markup are used in journal entries (they get used in later volumes?).

So I temporarily tagged a reference in a journal entry...
![ref_annotation](https://user-images.githubusercontent.com/1181194/42100986-a63fa01e-7bb9-11e8-8aec-19e73202cee0.png)

**Comment by peterwebster** [comment]
Could @durHHI test and feedback? As @nomoregrapes  has dummied this up, search for Knox and check it, then we'll need to ask Gregory to reverse it.

**Comment by DurHHHI** [comment]
Not finding anything in 15 that will work with this as a pop up test - but searching for Knox directly in the search, finding 'span' command still visible.

![knox span capture](https://user-images.githubusercontent.com/32575577/42172211-465ce164-7e13-11e8-8187-53157a45278c.JPG)

**Comment by peterwebster** [comment]
So, two things going on here.
@nomoregrapes is on the case with the display in the search results.

@DurHHHI can you search for '4 boys at school' in order to find the example Gregory has mocked up, and see if it is acceptable?

**Comment by DurHHHI** [comment]
Hi @peterwebster - I did exactly that yesterday and sourced the correct entry but could not find the mocked up ref example.

**Comment by peterwebster** [comment]
OK @DurHHHI : what we'll need to do is, once we have access to the editing functions in the interface, we can create a couple of examples ourselves to test, and then remove.

**Comment by nomoregrapes** [comment]
Span is no longer visible in search results.

I think this ticket is just left for testing. Awaiting either later volumes (in which ref 130 gets mentioned) or awaiting ability for you guys to have edit control so you can fake it then put it back.

**Comment by peterwebster** [comment]
Faked this, tested it, reverted to correct content. All fine.
