### ISSUE TITLE
Spacing issue in search results filter box on left

### ISSUE THREAD

**Issue by peterwebster** [peterwebster/henson#99]
![image](https://user-images.githubusercontent.com/5520710/41103634-847827ee-6a61-11e8-93f1-5684609ff1a3.png)

**Comment by peterwebster** [comment]
Apologies, I didn't have time to annotate this during a call with Hilary: the issue is with the positioning of the numbers in the Item Type box.

**Comment by nomoregrapes** [comment]
Fixed, and ready to close when confirmed.
![search-facets](https://user-images.githubusercontent.com/1181194/41279772-47e0d458-6e25-11e8-8741-f11f71979e52.png)

**Comment by DurHHHI** [comment]
Looks great!
